force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Label changed to Item Master from Inventory Item</description>
    <label>Item Master</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Item__c/fields/Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Cost_Category__c</fullName>
    <label>Cost Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repairs and Maintenance</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>IT &amp; Communications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory_Item__c/fields/Cost_Price__c.field-meta.xml
<CustomField>
    <fullName>Cost_Price__c</fullName>
    <inlineHelpText>GST not included</inlineHelpText>
    <label>Cost Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Inventory_Item__c/fields/Supplier_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Part_Number__c</fullName>
    <externalId>true</externalId>
    <label>Supplier Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ItemMasterListController.cls
public with sharing class ItemMasterListController {
    /**This is the list which will be passed to Visualforce Page and in turn passed to Flow from Visualforce**/
    public List <Inventory_Item__c> lstSelectedIMs {get;set;}
    public String finishURL {
        get{
            return Label.CreatePOFinishURL;
        }
        set;
    }
    public ItemMasterListController(ApexPages.StandardSetController listcontroller) {
      
        Set <Id> prSelectedIdSet = new Set <Id>();
        lstSelectedIMs = new List <Inventory_Item__c >();
            
        for (Inventory_Item__c pr : (List<Inventory_Item__c>) listcontroller.getSelected()) {
            prSelectedIdSet.add(pr.Id);
        }
        
        /**Querying on the Selected records and fetching fields which are required in Flow **/
        this.lstSelectedIMs = [select Id, Name, Supplier_Part_Number__c, Cost_Category__c, Cost_Price__c from Inventory_Item__c 
            where Id in: prSelectedIdSet order by Name asc];
    }
}