force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Label changed to Item Master from Inventory Item</description>
    <label>Item Master</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{00000}</displayFormat>
        <label>PO No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Account_Brand__c.field-meta.xml
<CustomField>
    <fullName>Account_Brand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Brand</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Account Brand)</relationshipLabel>
    <relationshipName>Purchase_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>PO Approved</fullName>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Supplier_Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>PO Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Master</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/No_of_Items_Still_Pending__c.field-meta.xml
<CustomField>
    <fullName>No_of_Items_Still_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of Items Still Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/No_of_PR_Items__c.field-meta.xml
<CustomField>
    <fullName>No_of_PR_Items__c</fullName>
    <defaultValue>0</defaultValue>
    <label>No. of PR Items</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/PO_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>PO_Item_Status__c</fullName>
    <label>PO Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Non-PR Related</fullName>
                <default>true</default>
                <label>Non-PR Related</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/Purchase_Request__c.object-meta.xml
<CustomObject>
    <label>Purchase Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>PR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Item_Name_Formula__c</fullName>
    <formula>IF(NOT(ISBLANK( New_Item_Name__c )) &amp;&amp; ISBLANK( Item__c ) ,
New_Item_Name__c,Item__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <formula>Purchase_Order__r.PO_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Purchase_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Item</label>
    <referenceTo>Purchase_Order_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Purchasing Review</fullName>
            </value>
            <value>
                <fullName>Approver Review</fullName>
            </value>
            <value>
                <fullName>For Approval - Review Complete</fullName>
            </value>
            <value>
                <fullName>For Item Review</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>For Ordering</fullName>
            </value>
            <value>
                <fullName>Pick List</fullName>
            </value>
            <value>
                <fullName>Packing List</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Approved - For Ordering</fullName>
                <isActive>false</isActive>
                <label>Approved - For Ordering</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Defective</fullName>
                <isActive>false</isActive>
                <label>Defective</label>
            </value>
            <value>
                <fullName>For Item Approval</fullName>
                <isActive>false</isActive>
                <label>For Item Approval</label>
            </value>
            <value>
                <fullName>For Pricing Approval</fullName>
                <isActive>false</isActive>
                <label>For Pricing Approval</label>
            </value>
            <value>
                <fullName>For Quoting</fullName>
                <isActive>false</isActive>
                <label>For Quoting</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Ready for Collection</fullName>
                <isActive>false</isActive>
                <label>Ready for Collection</label>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
                <isActive>false</isActive>
                <label>Sent to Supplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PR Supplier - This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</description>
    <inlineHelpText>This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</inlineHelpText>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Supplier accounts are allowed. Please check the Supplier selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreatePOsFromPRs.cls
public with sharing class CreatePOsFromPRs {
    @InvocableMethod(label='Process PRs to Create POs' description='Process a list of PRs to create POs' category='Cinch+Strike')
    public static List<InvocableOutput> createPOs(List<InvocableInput> inputList) {
        List<InvocableOutput> outputList = new List<InvocableOutput>();
        List<Purchase_Request__c> requestList = new List<Purchase_Request__c>();
        Id AccBrandId;
        for (InvocableInput input : inputList){
            requestList.addAll(input.purchaseRequestList);
        }
        // 1. Create a map of suppliers and PR items
        Map<Id, List<Purchase_Request__c>> supplierIdPRListMap = new Map<Id, List<Purchase_Request__c>>();
        
        for (Purchase_Request__c pr : requestList){
            if (!supplierIdPRListMap.containsKey(pr.Supplier__c)){
                List<Purchase_Request__c> prList = new List<Purchase_Request__c>();
                prList.add(pr);
                supplierIdPRListMap.put(pr.Supplier__c, prList);
            }
            else {
                List<Purchase_Request__c> tempList = supplierIdPRListMap.get(pr.Supplier__c);
                tempList.add(pr);
                supplierIdPRListMap.put(pr.Supplier__c, tempList);
            }
        }
           
        // 1.5 5/31/2023 : Associate Brand Name
        InvocableInput param = inputList[0];
        if(param.AccountId!=null){
        AccBrandId = param.AccountId;
        }
 
        // 2. Create PO headers
        List<Purchase_Order__c> poList = new List<Purchase_Order__c>();
        for (Id supplierId : supplierIdPRListMap.keySet()){
            Purchase_Order__c po = new Purchase_Order__c();
            po.Status__c = 'Draft';
            po.Supplier__c = supplierId;
            po.PO_Date__c = system.today();
            po.Account_Brand__c = AccBrandId;
            poList.add(po);
        }
        if (poList.size() > 0){
            insert poList;
        }
        //3. Create a map of Supplier and PO Ids
        poList = [select Id, Supplier__c from Purchase_Order__c where Id in :poList];
        Map<Id, Id> supplierIdPOIdMap = new Map<Id,Id>();
        for (Purchase_Order__c po : poList){
            supplierIdPOIdMap.put(po.Supplier__c, po.Id);
        }
        // now create the PO Items
        List<Purchase_Order_Item__c> poItemList = new List<Purchase_Order_Item__c>();
        List<Purchase_Request__c> prList = new List<Purchase_Request__c>();
        for (Id supplierId : supplierIdPRListMap.keySet()){
            Id POId = supplierIdPOIdMap.get(supplierId);
            Map<String,ItemAttribute> itemMap = new Map<String, ItemAttribute>();
            for (Purchase_Request__c pr : supplierIdPRListMap.get(supplierId)){
                String itemIndex = (pr.Item__c != null) ? String.valueOf(pr.Item__c) : pr.Item_Name_Formula__c;
                if (!itemMap.containsKey(itemIndex)){
                    ItemAttribute attr = new ItemAttribute();
                    attr.prCount = 1;
                    attr.quantity = pr.Quantity__c;
                    attr.itemName = pr.Item_Name_Formula__c;
                    attr.itemId = pr.Item__c;
                    itemMap.put(itemIndex, attr);
                }
                else {
                    ItemAttribute temp = itemMap.get(itemIndex);
                    temp.itemName = pr.Item_Name_Formula__c;
                    temp.itemId = pr.Item__c;
                    temp.prCount = temp.prCount + 1;
                    temp.quantity = temp.quantity + pr.Quantity__c;
                    itemMap.put(itemIndex, temp);
                }
                pr.Purchase_Order__c = POId;
                prList.add(pr);
            }
            for (String itemRef : itemMap.keySet()){
                ItemAttribute attr = itemMap.get(itemRef);
                Purchase_Order_Item__c poItem = new Purchase_Order_Item__c();
                poItem.Purchase_Order__c = POId;
                poItem.Inventory_Item__c = attr.itemId;
                poItem.No_of_PR_Items__c = attr.prCount;
                poItem.No_of_Items_Still_Pending__c = attr.quantity;
                poItem.Quantity__c = attr.quantity;
                poItem.Name = attr.itemName;
                poItem.PO_Item_Status__c = 'Draft';
                poItemList.add(poItem);
            }
            
        }

        if (prList.size() > 0){
            update prList; // update to link to PO
        }
        if (poItemList.size() > 0){
            insert poItemList;
        }
        // associate the PR to the PO Item
        prList = [select Id, Purchase_Order__c, Item__c, Item_Name_Formula__c from Purchase_Request__c where Id in :prList];
        poItemList = [select Id, Name, Purchase_Order__c, Inventory_Item__c from Purchase_Order_Item__c where Id in: poItemList];
        for (Purchase_Order_Item__c poItem : poItemList){
            for (Purchase_Request__c pr : prList){
                if (poItem.Purchase_Order__c == pr.Purchase_Order__c && ((poItem.Inventory_Item__c == pr.Item__c && pr.Item__c != null) || (pr.Item__c == null && pr.Item_Name_Formula__c == poItem.Name))){
                    pr.Purchase_Order_Item__c = poItem.Id;
                }
            }
        }
        
        update prList;

        InvocableOutput output = new InvocableOutput();
        output.purchaseOrderList = poList;
        outputList.add(output);
        return outputList;
    }
	
    public class ItemAttribute {
        public Decimal prCount {get;set;}
        public String itemId {get;set;}
        public String itemName {get;set;}
        public Decimal quantity {get;set;}
        public ItemAttribute(){}
    }
    public class InvocableInput {
		@InvocableVariable(label='List of Purchase Requests' required=true)
		public List<Purchase_Request__c> purchaseRequestList;
        
        //5/31/2023 : Added new variable to accept AccountId
        @InvocableVariable(label='Account Brand associated with Purchase Requests')
        public String AccountId;
    }

    public class InvocableOutput {
		@InvocableVariable(label='List of Purchase Orders')
		public List<Purchase_Order__c> purchaseOrderList;
    }
}