force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/Purchase_Request__c.object-meta.xml
<CustomObject>
    <label>Purchase Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>PR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/fields/Destination_Store__c.field-meta.xml
<CustomField>
    <fullName>Destination_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Unit that will receive this item or service</description>
    <inlineHelpText>Unit/Location</inlineHelpText>
    <label>Destination Store</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Purchase Requests (Destination Store)</relationshipLabel>
    <relationshipName>Purchase_Requests_Destination</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Details_for_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Details_for_Supplier__c</fullName>
    <label>Details for Supplier</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item_Master_Cost_Category__c.field-meta.xml
<CustomField>
    <fullName>Item_Master_Cost_Category__c</fullName>
    <formula>TEXT(Item__r.Cost_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Master Cost Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Item_Name_Formula__c</fullName>
    <formula>IF(NOT(ISBLANK( New_Item_Name__c )) &amp;&amp; ISBLANK( Item__c ) ,
New_Item_Name__c,Item__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <formula>IF(  New_Item_Formula__c , &apos;&apos;,  Item__r.Supplier_Part_Number__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Part Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/PO_Creation_Checker__c.field-meta.xml
<CustomField>
    <fullName>PO_Creation_Checker__c</fullName>
    <description>0 = No Error
1 = No Supplier and with PO
2 = No Supplier
3 = with PO (Not Cancelled)</description>
    <formula>IF(ISBLANK(Supplier__c) &amp;&amp; NOT(ISBLANK(PO_Status__c)) &amp;&amp; PO_Status__c != &apos;Cancelled&apos;, 1,
  IF(ISBLANK(Supplier__c), 2,
    IF(NOT(ISBLANK(PO_Status__c)) &amp;&amp; PO_Status__c != &apos;Cancelled&apos;, 3, 0)
  )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PO Creation Checker</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/PR_Cost_Price_GST_exc__c.field-meta.xml
<CustomField>
    <fullName>PR_Cost_Price_GST_exc__c</fullName>
    <label>PR Cost Price (GST exc)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PR Supplier - This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</description>
    <inlineHelpText>This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</inlineHelpText>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Supplier accounts are allowed. Please check the Supplier selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Total_Cost_Price_GST_exc__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost_Price_GST_exc__c</fullName>
    <formula>Cost_Price_GST_exc__c *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total PR Cost Price (GST exc)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PurchaseRequestListController.cls
public with sharing class PurchaseRequestListController {

    /**This is the list which will be passed to Visualforce Page and in turn passed to Flow from Visualforce**/
    public List <Purchase_Request__c> lstSelectedPRs {get;set;}
    public String finishURL {
        get{
            return Label.CreatePOFinishURL;
        }
        set;
    }
    public PurchaseRequestListController(ApexPages.StandardSetController listcontroller) {
      
        Set <Id> prSelectedIdSet = new Set <Id>();
        lstSelectedPRs = new List <Purchase_Request__c >();
            
        for (Purchase_Request__c pr : (List<Purchase_Request__c>) listcontroller.getSelected()) {
            prSelectedIdSet.add(pr.Id);
        }
        
        /**Querying on the Selected records and fetching fields which are required in Flow **/
        // 5/31/2023 : Added additional fields for querying
        this.lstSelectedPRs = [select Id, Item__c, Item_Name_Formula__c, PO_Creation_Checker__c , Part_Number__c,  Quantity__c, Item_Master_Cost_Category__c, PR_Cost_Price_GST_exc__c, Total_Cost_Price_GST_exc__c, Details_for_Supplier__c,
            Supplier__c, Destination_Store__c  from Purchase_Request__c 
            where Id in: prSelectedIdSet order by Supplier__c, Item__c asc];
        system.debug(lstSelectedPRs);
    }
    
}