force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Services_Received__c/Services_Received__c.object-meta.xml
<CustomObject>
    <label>Services Received Items</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Received Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/ServicesReceived__c.object-meta.xml
<CustomObject>
    <label>Services Received</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Services Received</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Received</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Services_Received__c</referenceTo>
    <relationshipName>Services_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WDSRWrapper.cls
public class WDSRWrapper{
         public ServicesReceived__c SR {get; set;}
         public string RecordTypeName {
                 get{
                     return getRecordTypeName(SR.RecordTypeId);
                 }
        }
         public string ItemName {get{
                Services_Received__c item = skedWDServicesReceive.getSRItem(SR.Item__c);  
                return  item.Name;
         }}     
        
    
          //Helper method
        public string getRecordTypeName(String recordTypeId) {
        try {    
                return ServicesReceived__c.SObjectType
                       .getDescribe()
                       .getRecordTypeInfosById()
                       .get(recordTypeId)
                       .getName();
            } catch(Exception e) {
                return null;
            }
        }
        
     }