force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/Purchase_Request__c.object-meta.xml
<CustomObject>
    <label>Purchase Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>PR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item_Name_Formula__c.field-meta.xml
<CustomField>
    <fullName>Item_Name_Formula__c</fullName>
    <formula>IF(NOT(ISBLANK( New_Item_Name__c )) &amp;&amp; ISBLANK( Item__c ) ,
New_Item_Name__c,Item__r.Name )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quote_Item__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item - Not Needed</label>
    <referenceTo>Quote_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quoted_Created__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Created__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Purchasing Review</fullName>
            </value>
            <value>
                <fullName>Approver Review</fullName>
            </value>
            <value>
                <fullName>For Approval - Review Complete</fullName>
            </value>
            <value>
                <fullName>For Item Review</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>For Ordering</fullName>
            </value>
            <value>
                <fullName>Pick List</fullName>
            </value>
            <value>
                <fullName>Packing List</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Approved - For Ordering</fullName>
                <isActive>false</isActive>
                <label>Approved - For Ordering</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Defective</fullName>
                <isActive>false</isActive>
                <label>Defective</label>
            </value>
            <value>
                <fullName>For Item Approval</fullName>
                <isActive>false</isActive>
                <label>For Item Approval</label>
            </value>
            <value>
                <fullName>For Pricing Approval</fullName>
                <isActive>false</isActive>
                <label>For Pricing Approval</label>
            </value>
            <value>
                <fullName>For Quoting</fullName>
                <isActive>false</isActive>
                <label>For Quoting</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Ready for Collection</fullName>
                <isActive>false</isActive>
                <label>Ready for Collection</label>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
                <isActive>false</isActive>
                <label>Sent to Supplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PR Supplier - This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</description>
    <inlineHelpText>This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</inlineHelpText>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Supplier accounts are allowed. Please check the Supplier selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QU-{000000}</displayFormat>
        <label>Quote No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier [From Quote]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Item__c/Quote_Item__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QUI-{000000}</displayFormat>
        <label>Quote Item No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Item__c/fields/Purchase_Request_No__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Request_No__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Request No.</label>
    <referenceTo>Purchase_Request__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote_Item__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>Quote_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateQuotesFromPRs.cls
public with sharing class CreateQuotesFromPRs {
    @InvocableMethod(label='Process PRs to Create Quotes' description='Process a list of PRs to create Quotes' category='Cinch+Strike')
    public static List<InvocableOutput> createQuotes(List<InvocableInput> inputList) {
        List<InvocableOutput> outputList = new List<InvocableOutput>();
        List<Purchase_Request__c> requestList = new List<Purchase_Request__c>();
        for (InvocableInput input : inputList){
            requestList.addAll(input.purchaseRequestList);
        }
        // 1. Create a map of suppliers and PR items
        Map<Id, List<Purchase_Request__c>> supplierIdPRListMap = new Map<Id, List<Purchase_Request__c>>();
        
        for (Purchase_Request__c pr : requestList){
            if (!supplierIdPRListMap.containsKey(pr.Supplier__c)){
                List<Purchase_Request__c> prList = new List<Purchase_Request__c>();
                prList.add(pr);
                supplierIdPRListMap.put(pr.Supplier__c, prList);
            }
            else {
                List<Purchase_Request__c> tempList = supplierIdPRListMap.get(pr.Supplier__c);
                tempList.add(pr);
                supplierIdPRListMap.put(pr.Supplier__c, tempList);
            }
        }
        // 2. Create Quotes headers
        List<Quote__c> quList = new List<Quote__c>();
        for (Id supplierId : supplierIdPRListMap.keySet()){
            Quote__c qu = new Quote__c();
            qu.Status__c = 'Not Started';
            qu.Supplier__c = supplierId;
            quList.add(qu);
        }
        if (quList.size() > 0){
            insert quList;
        }
        //3. Create a map of Supplier and Quote Ids
        quList = [select Id, Supplier__c from Quote__c where Id in :quList];
        Map<Id, Id> supplierIdQuoteIdMap = new Map<Id,Id>();
        for (Quote__c qu : quList){
            supplierIdQuoteIdMap.put(qu.Supplier__c, qu.Id);
        }
        // now create the Quote Items
        List<Quote_Item__c> quItemList = new List<Quote_Item__c>();
        List<Purchase_Request__c> prList = new List<Purchase_Request__c>();
        for (Id supplierId : supplierIdQuoteIdMap.keySet()){
            Id QUId = supplierIdQuoteIdMap.get(supplierId);

            for (Purchase_Request__c pr : requestList){
 
                if (pr.Supplier__c == supplierId){
                    Quote_Item__c quItem = new Quote_Item__c();
                    quItem.Quote__c = QUId;
                    quItem.Item__c = pr.Item__c;
                    quItem.Quantity__c = pr.Quantity__c;
                    quItem.Item_Name__c = pr.Item_Name_Formula__c;
                    quItem.Purchase_Request_No__c = pr.Id;
                    quItemList.add(quItem);
                    
                    Purchase_Request__c prItem = new Purchase_Request__c();
                    prItem.Id = pr.Id;
                    prItem.Quoted_Created__c = QUId;
                    prList.add(prItem);
                }
            }
            
        }

        //Update Purchase Request
        if (prList.size() > 0){
            update prList;
        }

        if (quItemList.size() > 0){
            insert quItemList;
        }


        InvocableOutput output = new InvocableOutput();
        output.QuotesList = quList;
        outputList.add(output);
        return outputList;
    }
	
    public class InvocableInput {
		@InvocableVariable(label='List of Purchase Requests' required=true)
		public List<Purchase_Request__c> purchaseRequestList;
    }

    public class InvocableOutput {
		@InvocableVariable(label='List of Quotes')
		public List<Quote__c> QuotesList;
    }
}