force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Bundle_Item__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bundle Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipName>Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Services_Received__c/Services_Received__c.object-meta.xml
<CustomObject>
    <label>Services Received Items</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Received Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/ServicesReceived__c.object-meta.xml
<CustomObject>
    <label>Services Received</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Services Received</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Received</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/fields/Description_of_Operations__c.field-meta.xml
<CustomField>
    <fullName>Description_of_Operations__c</fullName>
    <label>Description of Operations</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DR#</label>
    <referenceTo>WD_Report__c</referenceTo>
    <relationshipLabel>Services Received</relationshipLabel>
    <relationshipName>Services_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Finish_Time__c.field-meta.xml
<CustomField>
    <fullName>Finish_Time__c</fullName>
    <label>Finish Time</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Services_Received__c</referenceTo>
    <relationshipName>Services_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Item_Rate__c.field-meta.xml
<CustomField>
    <fullName>Item_Rate__c</fullName>
    <label>Item Rate</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Item_total__c.field-meta.xml
<CustomField>
    <fullName>Item_total__c</fullName>
    <inlineHelpText>Total Hours, Number of Days, Lump Sum  (Number in unit will multiply by rate to get total cost of item.</inlineHelpText>
    <label>Item Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <inlineHelpText>Use 24hr time (round to nearest 15 min)</inlineHelpText>
    <label>Start time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <label>Total Cost</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/WD_Report__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <displayFormat>JO-{00000}</displayFormat>
        <label>JO #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/skedRelatedSRExtension.cls
public class skedRelatedSRExtension{

public List<ServicesReceived__c> SRList {get; set;}

  public skedRelatedSRExtension(ApexPages.StandardController controller) {
    
        WD_Report__c JO = (WD_Report__c)controller.getRecord(); 
        
        SRList = [Select Date__c, RecordTypeId, Item__c, Item__r.Name, Description_of_Operations__c, Start_time__c,
         Finish_Time__c, Item_total__c, Item_Rate__c, Total_Cost__c From ServicesReceived__c Where DR__c = :JO.Id
         ORDER BY Start_time__c ASC];   
        
       }
 }