force-app/main/default/objects/Driver_Assignment__c/Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Driver Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000000}</displayFormat>
        <label>Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Driver Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver_Assignment__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>20 JUN 2023: Previous name is Configuration</description>
    <label>Contract Job Item</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contract_Item__c.Item_Name__r.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contract_Item__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Configuration_Name__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Name__c</fullName>
    <description>20 JUN 2023: Previous name is Configuration Name</description>
    <formula>Configuration__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract Job Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Configuration_pklist__c.field-meta.xml
<CustomField>
    <fullName>Configuration_pklist__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primemover</fullName>
            </value>
            <value>
                <fullName>Primemover + Dolly</fullName>
            </value>
            <value>
                <fullName>Flat Top Single</fullName>
            </value>
            <value>
                <fullName>Flat Top B Double</fullName>
            </value>
            <value>
                <fullName>Flat Top Double</fullName>
            </value>
            <value>
                <fullName>Flat Top AB Triple</fullName>
            </value>
            <value>
                <fullName>Flat Top Triple</fullName>
            </value>
            <value>
                <fullName>Bed Truck</fullName>
            </value>
            <value>
                <fullName>Bed Truck + 1 Trailer</fullName>
            </value>
            <value>
                <fullName>Bed Truck + B Double</fullName>
            </value>
            <value>
                <fullName>Bed Truck + 2 Trailers</fullName>
            </value>
            <value>
                <fullName>Water Tanker Single</fullName>
            </value>
            <value>
                <fullName>Water Tanker B Double</fullName>
            </value>
            <value>
                <fullName>Water Tanker Double</fullName>
            </value>
            <value>
                <fullName>Water Tanker AB Triple</fullName>
            </value>
            <value>
                <fullName>Water Tanker Triple</fullName>
            </value>
            <value>
                <fullName>Fuel Tanker Single</fullName>
            </value>
            <value>
                <fullName>Fuel Tanker B Double</fullName>
            </value>
            <value>
                <fullName>Fuel Tanker Double</fullName>
            </value>
            <value>
                <fullName>Fuel Tanker AB Triple</fullName>
            </value>
            <value>
                <fullName>Fuel Tanker Triple</fullName>
            </value>
            <value>
                <fullName>Quad Float</fullName>
            </value>
            <value>
                <fullName>Quad Float + Dolly</fullName>
            </value>
            <value>
                <fullName>Vac Truck</fullName>
            </value>
            <value>
                <fullName>Cattle Crate Single</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment_Date__c</fullName>
    <label>Driver Assignment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver_Assignment_URL__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment_URL__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+ Id ,  Name , &apos;_blank&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Driver Assignment URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver_Status__c.field-meta.xml
<CustomField>
    <fullName>Driver_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Calculate difference between start and end date/time</description>
    <formula>(End_Date_Time__c - Start_Date_Time__c)*24</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duration (hours)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Is_Driver_Assignment_Accepted__c.field-meta.xml
<CustomField>
    <fullName>Is_Driver_Assignment_Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Tick the checkbox if you accept the driver assignment.</inlineHelpText>
    <label>Is Driver Assignment Accepted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Maintenance_Category__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Category__c</fullName>
    <label>Maintenance Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Heavy Vehicle Maintenance</fullName>
            </value>
            <value>
                <fullName>Non- Heavy Vehicle Maintenance</fullName>
            </value>
            <value>
                <fullName>Assist at Camp</fullName>
                <isActive>false</isActive>
                <label>Assist at Camp</label>
            </value>
            <value>
                <fullName>Assist at Rig</fullName>
                <isActive>false</isActive>
                <label>Assist at Rig</label>
            </value>
            <value>
                <fullName>Assist in Stores</fullName>
                <isActive>false</isActive>
                <label>Assist in Stores</label>
            </value>
            <value>
                <fullName>Clean LV</fullName>
                <isActive>false</isActive>
                <label>Clean LV</label>
            </value>
            <value>
                <fullName>Clean Workshop</fullName>
                <isActive>false</isActive>
                <label>Clean Workshop</label>
            </value>
            <value>
                <fullName>Drive LV</fullName>
                <isActive>false</isActive>
                <label>Drive LV</label>
            </value>
            <value>
                <fullName>Empty Bins</fullName>
                <isActive>false</isActive>
                <label>Empty Bins</label>
            </value>
            <value>
                <fullName>HV Passenger</fullName>
                <isActive>false</isActive>
                <label>HV Passenger</label>
            </value>
            <value>
                <fullName>LV Repairs</fullName>
                <isActive>false</isActive>
                <label>LV Repairs</label>
            </value>
            <value>
                <fullName>Loader/Forklift Driving (unrelated to a HV)</fullName>
                <isActive>false</isActive>
                <label>Loader/Forklift Driving (unrelated to a HV)</label>
            </value>
            <value>
                <fullName>Other Non-HV task</fullName>
                <isActive>false</isActive>
                <label>Other Non-HV task</label>
            </value>
            <value>
                <fullName>Pickup/Delivery Duties (LV only)</fullName>
                <isActive>false</isActive>
                <label>Pickup/Delivery Duties (LV only)</label>
            </value>
            <value>
                <fullName>Training</fullName>
                <isActive>false</isActive>
                <label>Training</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Quoted_Price_Job__c.field-meta.xml
<CustomField>
    <fullName>Quoted_Price_Job__c</fullName>
    <description>Ticked if the Contract Job Item Service Type is Fixed Price/Hour</description>
    <formula>ISPICKVAL(  Configuration__r.Service_Type__c  , &apos;Fixed Price/Hour&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hourly Job Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Transport_Job__c.field-meta.xml
<CustomField>
    <fullName>Transport_Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transport Job</label>
    <referenceTo>Transport_Job__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Assigned Truck (Prime Mover)</description>
    <inlineHelpText>Assigned Truck (Prime Mover)</inlineHelpText>
    <label>Truck</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Asset_Family__c</field>
            <operation>equals</operation>
            <value>Prime Movers</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DriverAssignmentController.cls
public with sharing class DriverAssignmentController {
    @AuraEnabled(cacheable=true)
    public static List<Driver_Assignment__c> getDriverAssignmentList(Id transportjob) {
        return [SELECT Id, Name, Driver__r.Name, Driver_Status__c, Is_Driver_Assignment_Accepted__c, Send_Notification__c, Start_Date_Time__c, End_Date_Time__c, Duration__c, Start_Time__c, End_Time__c, Configuration_Name__c, 
            Maintenance_Category__c, Configuration_pklist__c, Truck__c, Truck__r.Name, Quoted_Price_Job__c, Driver_Assignment_URL__c, Driver_Assignment_Date__c
            FROM Driver_Assignment__c
            WHERE Transport_Job__c = :transportjob  
            WITH SECURITY_ENFORCED
            ORDER BY Driver__r.Name
        ];
    }

    // 23 JUN 2023 [C+S] GET DRAFT DRIVER ASSIGNMENT WITH NO CONTACT JOB ITEMS 
    @AuraEnabled(cacheable=true)
    public static List<Driver_Assignment__c> getDriverAssignNoContactJobItem(Id transportjob) {
        return [SELECT Id
            FROM Driver_Assignment__c 
            WHERE Transport_Job__c = :transportjob  
            AND Configuration__c = ''
            //AND Driver_Status__c = 'Draft'
            WITH SECURITY_ENFORCED
        ];
    }

    // 23 JUN 2023 [C+S] GET DRAFT DRIVER ASSIGNMENT WITH NO CONTACT JOB ITEMS 
    @AuraEnabled(cacheable=true)
    public static List<Driver_Assignment__c> getDriverAssignNoConfiguration(Id transportjob) {
        return [SELECT Id
            FROM Driver_Assignment__c 
            WHERE Transport_Job__c = :transportjob  
            AND Configuration_pklist__c = ''
            //AND Driver_Status__c = 'Draft'
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List < sObject > fetchLookUpValues(String searchKey,String fieldName, String ObjectName,String keyField) {
     List < sObject > returnList = new List < sObject > ();
       String sQuery =  'SELECT '+fieldName+','+keyField+ ' FROM '
       +ObjectName+' LIMIT 100' ;
       List < sObject > lstOfRecords = Database.query(sQuery);
       for (sObject obj: lstOfRecords) {
           returnList.add(obj);
       }
       return returnList;
   }

   @AuraEnabled(cacheable=true)
   public static List <Contract_Item__c> ConfigurationLookUp(Id transportJobID) {
    String sQuery =  'SELECT Name, Id FROM Contract_Item__c WHERE Unit_Type__c = \'Transport\'';
    Transport_Job__c[] unitID =  [SELECT Unit__c, Unit__r.Contract_New__c, Unit__r.Unit_Type__c, Site__r.Contract__c FROM Transport_Job__c WHERE iD = :transportJobID];
    
    //If Unit ID record found
    if (!unitID.Isempty()) {
        /*Id strUnitID = unitID[0].Unit__c;
        Id strSiteId = unitID[0].Site__c;
        List<Unit__c> contractNo = new List<Unit__c>();
        List<Site__c> siteNo = new List<Site__c>();*/
        Id strcontractNo = null;
        if (unitID[0].Unit__r.Unit_Type__c == 'Transport'){
            sQuery =  'SELECT Name, Id FROM Contract_Item__c WHERE Active__c = TRUE AND Unit_Type__c = \'Transport\' AND Contract__c =\'' + unitID[0].Site__r.Contract__c + '\'';
        }
        else {
            sQuery =  'SELECT Name, Id FROM Contract_Item__c WHERE Active__c = TRUE AND Unit_Type__c = \'Transport\' AND Contract__c =\'' + unitID[0].Unit__r.Contract_New__c + '\'';
        }
        


        /*//If Contract No record found
        if(!contractNo.Isempty()){
            sQuery =  'SELECT Name, Id FROM Contract_Item__c WHERE Unit_Type__c = \'Transport\' AND Contract__c =\'' + strcontractNo + '\'';
       }*/
    } 
      
    List < Contract_Item__c > returnList = new List < Contract_Item__c > ();  
	List < Contract_Item__c > lstOfRecords = Database.query(sQuery);
	for (Contract_Item__c obj: lstOfRecords) {
               returnList.add(obj);
           }       
       
	return returnList; 
  }

    // 18 SEPT 2023: Added Truck lookup
    @AuraEnabled(cacheable=true)
    public static List <Asset__c> TruckLookUp(Id transportJobID) {
        String sQuery =  'SELECT Name, Id FROM Asset__c WHERE Type__c = \'Transport\' AND Asset_Family__c = \'Prime Movers\' ORDER BY Name ASC';
            
        List < Asset__c > returnList = new List < Asset__c > ();  
        List < Asset__c > lstOfRecords = Database.query(sQuery);
        for (Asset__c obj: lstOfRecords) {
                    returnList.add(obj);
                }       
            
        return returnList; 
    }

  @AuraEnabled(cacheable=true)
  public static List <Employees__c> DriverNameLookUp() {
   
    //List of Active Employees
   String sQuery =  'SELECT Id, Name FROM Employees__c WHERE RecordType.Name = \'Active Employee\' AND On_Shift__c = TRUE AND Driver_User__c != NULL ORDER BY Name';
   
   List < Employees__c > returnList = new List < Employees__c > ();  
   List < Employees__c > lstOfRecords = Database.query(sQuery);
   for (Employees__c obj: lstOfRecords) {
              returnList.add(obj);
          }       
      
   return returnList; 
 }
}