force-app/main/default/objects/Driver_Assignment__c/Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Driver Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000000}</displayFormat>
        <label>Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Driver Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver_Assignment__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <formula>Transport_Job__r.Site__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Transport_Job__c.field-meta.xml
<CustomField>
    <fullName>Transport_Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transport Job</label>
    <referenceTo>Transport_Job__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <formula>Transport_Job__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Assigned_to_Unit__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Employment</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Job__c/Transport_Job__c.object-meta.xml
<CustomObject>
    <label>Transport Job</label>
    <nameField>
        <displayFormat>TJ-{0000000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR 4 OR 5)</booleanFilter>
        <filterItems>
            <field>Site__c.Site_Status__c</field>
            <operation>equals</operation>
            <value>Open, Open - Inactive, Open, Open - Inactive, Closed</value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Camp__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Rig__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Camp__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Rig__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Transport Jobs</relationshipLabel>
    <relationshipName>Transport_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Types__c.field-meta.xml
<CustomField>
    <fullName>Types__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular</fullName>
                <default>true</default>
                <label>Regular</label>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Transport Jobs</relationshipLabel>
    <relationshipName>Transport_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>Field Camp/Rig - purpose built for contract
Base - Permanent building/Camp 
Department - section of business that may require identifying for expense purposes</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qld Depot</fullName>
                <label>Qld - Depot</label>
            </value>
            <value>
                <fullName>Camp - Qld</fullName>
                <label>Qld - Camp</label>
            </value>
            <value>
                <fullName>Rig - Qld</fullName>
                <label>Qld - Rig</label>
            </value>
            <value>
                <fullName>Depot - Roma</fullName>
                <label>SA - Depot</label>
            </value>
            <value>
                <fullName>Camp - SA</fullName>
                <label>SA - Camp</label>
            </value>
            <value>
                <fullName>Rig - SA</fullName>
                <label>SA - Rig</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Field - Rig</fullName>
            </value>
            <value>
                <fullName>Field - Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DriverAssignmentTriggerHandlerTest.cls
@IsTest 

public class DriverAssignmentTriggerHandlerTest {
    static testmethod void testUpdateStartTime(){
        Transport_Job__c tj = new Transport_Job__c(Types__c = 'Maintenance');
        insert tj;
        Account cust = new Account(Name = 'Test');
        insert cust;
        Site__c st = new Site__c(Name = 'Test', Account__c = cust.Id);
        insert st;
        Unit__c unit = new Unit__c(Name = 'Test', Unit_Type__c = 'Transport', Status__c = 'Active', Site__c = st.Id);
        insert unit;
        Position__c pos = new Position__c(Name = 'Test');
        insert pos;
        Employees__c emp = new Employees__c(Name = 'Test', Status__c = 'Active', First_Name__c ='Test', Last_Name__c = 'Test', 
        Assigned_to_Unit__c = unit.Id, PositionLookup__c = pos.Id);
        insert emp;
        Driver_Assignment__c da = new Driver_Assignment__c(Transport_Job__c = tj.Id, Driver__c = emp.Id, Maintenance_Category__c = 'Training');
        insert da;
        da.Start_Date_Time__c = system.now();
        da.End_Date_Time__c = system.now() + 1;
        update da;
        da = [select Id, Start_Date_Time__c, End_Date_Time__c, Start_Time__c, End_Time__c from Driver_Assignment__c where Id = :da.Id limit 1];
        system.assertEquals(da.Start_Date_Time__c.format('hh:mm a'), da.Start_Time__c);
        system.assertEquals(da.End_Date_Time__c.format('hh:mm a'), da.End_Time__c);
        
    }
}