force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Daily_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Summary_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Site Job Summary</label>
    <referenceTo>Daily_Summary_Report__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Manager - Approved</fullName>
            </value>
            <value>
                <fullName>Ops - Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/Daily_Summary_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Site Job Summary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Job Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Status__c</fullName>
    <formula>TEXT(Site__r.Site_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ops Mgr - Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <label>Invoiced - Draft</label>
            </value>
            <value>
                <fullName>Invoiced - Disputed</fullName>
                <label>Disputed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Summary_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Summary_Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Summary Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Status__c</fullName>
    <inlineHelpText>Open: Active;
Open - Inactive: Inactive,Winding up;
Closed: Inactive, Work Complete;</inlineHelpText>
    <label>Site Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Inv - Draft</fullName>
            </value>
            <value>
                <fullName>Inv - Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Inv - Approved</fullName>
            </value>
            <value>
                <fullName>Inv - Disputed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Inv - Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>LTI_Reset_Date__c</fullName>
    <description>When the LTI field is changed back to zero the LTI Date will automatically reset to the day this happened</description>
    <label>LTI Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteTrigger_Test.cls
@isTest
public class SiteTrigger_Test {
    static testMethod void testMethod1(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insert rigUnit;
            
            Site__c site1 = testData.createSite();
            site1.Account__c = acc.Id;
            site1.Contract__c = cont.Id;
            site1.Status__c = 'Open';
            insert site1;
            
            List<Daily_Summary_Report__c> relatedDailySummaryReport = [Select Id,Status__c from Daily_Summary_Report__c where Summary_Report_Date__c = today];
            if(relatedDailySummaryReport.isEmpty()){
                Daily_Summary_Report__c dsr = new Daily_Summary_Report__c();
                dsr.Summary_Report_Date__c = System.today();
                dsr.Status__c = 'Open';
                dsr.Contract__c = cont.Id;
                dsr.Site__c = site1.Id;
                insert dsr;
                relatedDailySummaryReport.add(dsr);
            }
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site1.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            dailyReportRig.Status__c = 'Open';
            insert dailyReportRig;
            
            Test.startTest();
            site1.Site_Status__c = 'Closed';
            update site1;
            Test.stopTest();
            
        }
        catch(Exception e){
            String errorMessage = 'Site Status cannot be set to Closed';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            System.assertEquals(exceptionThrown, true);
        }   
    }
    
    static testMethod void preventSiteDelete(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insert rigUnit;
            
            Site__c site1 = testData.createSite();
            site1.Account__c = acc.Id;
            site1.Contract__c = cont.Id;
            site1.Status__c = 'Open';
            insert site1;
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site1.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            dailyReportRig.Status__c = 'Open';
            insert dailyReportRig;
            
            delete site1;
            
        }
        catch(Exception e){
            String errorMessage = 'You cannot delete a Site when there are records associated with it.';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            System.assertEquals(exceptionThrown, true);
        }   
    }
}