force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Item__c/Contract_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Job Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contract__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Add_to_NDT__c.field-meta.xml
<CustomField>
    <fullName>Add_to_NDT__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, item&apos;s hours will be calculated for NDT Hours on Unit</inlineHelpText>
    <label>Add to NDT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Contract_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Item__c.BundledItem__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Contract Job Items</relationshipLabel>
    <relationshipName>Contract_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>If not selected then auto-populated from Item</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Daily_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Summary_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Site Job Summary</label>
    <referenceTo>Daily_Summary_Report__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/Daily_Summary_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Site Job Summary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Job Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Add_to_NDT__c.field-meta.xml
<CustomField>
    <fullName>Add_to_NDT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to NDT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>LTI_Reset_Date__c</fullName>
    <description>When the LTI field is changed back to zero the LTI Date will automatically reset to the day this happened</description>
    <label>LTI Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>Field Camp/Rig - purpose built for contract
Base - Permanent building/Camp 
Department - section of business that may require identifying for expense purposes</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qld Depot</fullName>
                <label>Qld - Depot</label>
            </value>
            <value>
                <fullName>Camp - Qld</fullName>
                <label>Qld - Camp</label>
            </value>
            <value>
                <fullName>Rig - Qld</fullName>
                <label>Qld - Rig</label>
            </value>
            <value>
                <fullName>Depot - Roma</fullName>
                <label>SA - Depot</label>
            </value>
            <value>
                <fullName>Camp - SA</fullName>
                <label>SA - Camp</label>
            </value>
            <value>
                <fullName>Rig - SA</fullName>
                <label>SA - Rig</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Field - Rig</fullName>
            </value>
            <value>
                <fullName>Field - Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailySummaryReportTrigger_Test.cls
@isTest
public class DailySummaryReportTrigger_Test {
    
    //Calls preventSubmittedStatus method
    static testMethod void testMeth1(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Item__c item2 = testData.createItemRigOperating();
            insert item2;
            
            Account acc = testData.createAccount();
            acc.Regions_LG_Area__c = 'Maranoa';
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            Site__c site1 = testData.createSite();
            site1.Account__c = acc.Id;
            site1.Contract__c = cont.Id;
            insert site1;
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insert rigUnit;
            
            Contract_Item__c contractItem2 = testData.createContractJobItem();
            contractItem2.Unit_Type__c = 'Rig';
            contractItem2.Contract__c = cont.Id;
            contractItem2.Item_Name__c = item2.Id;
            contractItem2.Add_to_NDT__c = true;
            insert contractItem2;
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site1.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            insert dailyReportRig;
            
            List<Daily_Summary_Report__c> relatedDailySummaryReport = [Select Id,Status__c from Daily_Summary_Report__c where Summary_Report_Date__c = today];
            if(relatedDailySummaryReport.isEmpty()){
                Daily_Summary_Report__c dsr = new Daily_Summary_Report__c();
                dsr.Summary_Report_Date__c = System.today();
                dsr.Status__c = 'Open';
                dsr.Contract__c = cont.Id;
                dsr.Site__c = site1.Id;
                insert dsr;
                relatedDailySummaryReport.add(dsr);
            }
            
           // List<Daily_Summary_Report__c> relatedDailySummaryReport = [Select Id,Status__c from Daily_Summary_Report__c where Summary_Report_Date__c = today];
            relatedDailySummaryReport[0].Status__c = 'Submitted';
            update relatedDailySummaryReport[0];

            delete relatedDailySummaryReport[0];
        }
        catch(Exception e){
            String errorMessage = 'A Daily Site Job Summary cannot be submitted till all the Daily Site Jobs have been Ops - Approved.';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            //System.assertEquals(exceptionThrown, true);
            system.debug('## exception: ' + e.getMessage());
        }
    }
    
    
    //Calls preventDuplicateSummaryReport method
    static testMethod void testMeth2(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Item__c item2 = testData.createItemRigOperating();
            insert item2;
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            Site__c site1 = testData.createSite();
            site1.Account__c = acc.Id;
            site1.Contract__c = cont.Id;
            insert site1;
            
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insert rigUnit;
            
            Contract_Item__c contractItem2 = testData.createContractJobItem();
            contractItem2.Unit_Type__c = 'Rig';
            contractItem2.Contract__c = cont.Id;
            contractItem2.Item_Name__c = item2.Id;
            contractItem2.Add_to_NDT__c = true;
            insert contractItem2;
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site1.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            insert dailyReportRig;
            
            Daily_Summary_Report__c dsr3 = new Daily_Summary_Report__c();
            dsr3.Contract__c = cont.Id;
            dsr3.Site__c = site1.Id;
            dsr3.Summary_Report_Date__c = System.today()-1;
            dsr3.Status__c = 'Open';
            insert dsr3;
            
            Daily_Summary_Report__c dsr = new Daily_Summary_Report__c();
            dsr.Contract__c = cont.Id;
            dsr.Site__c = site1.Id;
            dsr.Summary_Report_Date__c = System.today();
            dsr.Status__c = 'Open';
            insert dsr;
            
            Daily_Summary_Report__c dsr2 = new Daily_Summary_Report__c();
            dsr2.Contract__c = cont.Id;
            dsr2.Site__c = site1.Id;
            dsr2.Summary_Report_Date__c = System.today();
            dsr2.Status__c = 'Open';
            insert dsr2;
            
            
        }
        catch(Exception e){
            String errorMessage = 'A Daily Site Job Summary of this type has already been created';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            //System.assertEquals(exceptionThrown, true);
            system.debug('## exception: ' + e.getMessage());
        }
    }
    
    static testMethod void preventDailySiteJobSummaryDeletionTestMethod(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Item__c item2 = testData.createItemRigOperating();
            insert item2;
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            Site__c site1 = testData.createSite();
            site1.Account__c = acc.Id;
            site1.Contract__c = cont.Id;
            insert site1;
            
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insert rigUnit;
            
            Contract_Item__c contractItem2 = testData.createContractJobItem();
            contractItem2.Unit_Type__c = 'Rig';
            contractItem2.Contract__c = cont.Id;
            contractItem2.Item_Name__c = item2.Id;
            contractItem2.Add_to_NDT__c = true;
            insert contractItem2;
            
            Daily_Summary_Report__c dsr3 = new Daily_Summary_Report__c();
            dsr3.Contract__c = cont.Id;
            dsr3.Site__c = site1.Id;
            dsr3.Summary_Report_Date__c = System.today()-1;
            dsr3.Status__c = 'Open';
            insert dsr3;
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site1.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            dailyReportRig.Daily_Summary_Report__c = dsr3.Id;
            insert dailyReportRig;
            
            delete dsr3;           
            
            
        }
        catch(Exception e){
            String errorMessage = 'You cannot delete a Daily Site Job Summary if it has Daily Site Jobs Attached to it.';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            system.debug('## exception: ' + e.getMessage());
            //System.assertEquals(exceptionThrown, true);
        }
    }
    
    
    
    
    
}