force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Parent_WD_Unit__c.field-meta.xml
<CustomField>
    <fullName>Parent_WD_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent WD Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/UnitType__c.field-meta.xml
<CustomField>
    <fullName>UnitType__c</fullName>
    <formula>IF(CONTAINS(TEXT(Unit_Type__c),&apos;Rig&apos;),&apos;Rig&apos;,
IF(CONTAINS(TEXT(Unit_Type__c),&apos;Camp&apos;),&apos;Camp&apos;,
IF(CONTAINS(TEXT(Unit_Type__c),&apos;Transport&apos;),&apos;Transport&apos;,&apos;&apos;)))</formula>
    <label>UnitType</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DailySiteJobStandard_Controller.cls
/**********************************************************************************
* @author        Kunal Jain
* @date         
* @description   This is a controller for DailySiteJobStandard_VF visualforce page
* @TestClass     DailySiteJobStandard_Controller_Test
***********************************************************************************/
public class DailySiteJobStandard_Controller{
    
    String siteJobId;
    Id dailySiteJobId;
    
    public DailySiteJobStandard_Controller(ApexPages.StandardController controller){
        dailySiteJobId = controller.getId();
        siteJobId = dailySiteJobId;
    }
    
    public pageReference init(){
        Daily_Report__c dailyReport;
        String contractIdParam;
        String siteIdParam;
        String unitIdParam;
        String unitTypeParam;
        String retUrl;
        
        if(dailySiteJobId != null){
            dailyReport = [Select Id,Unit__c,Unit__r.UnitType__c,Type__c,Contract__c,Site__c from Daily_Report__c where Id = : dailySiteJobId];
            contractIdParam = dailyReport.Contract__c;
            siteIdParam = dailyReport.Site__c;
            unitIdParam = dailyReport.Unit__c;
            unitTypeParam = dailyReport.Unit__r.UnitType__c;
            retUrl = dailyReport.Id;
            
            
        }else{
            contractIdParam = ApexPages.currentPage().getParameters().get('contractId');
            siteIdParam = ApexPages.currentPage().getParameters().get('siteId');
            unitIdParam = ApexPages.currentPage().getParameters().get('unitId');
            unitTypeParam = ApexPages.currentPage().getParameters().get('unitType');
            retUrl = ApexPages.currentPage().getParameters().get('retURL');
            if(String.isNotBlank(retUrl)){
                Integer indexOfRetUrl = retUrl.indexOf('com/');
                retUrl = retUrl.substring(indexOfRetUrl + 4);
            }
        }
        
        system.debug('--DailySiteJobStandard_Controller Start--');
        system.debug('retUrl: ' + retUrl);
        system.debug('--DailySiteJobStandard_Controller End--');
        PageReference redirectToPage;
        if(siteJobId != null){
            redirectToPage = new PageReference('/apex/DailySiteJob_VF?siteJobId='+siteJobId+'&tabView=1'+'&retURL='+retUrl);
        }
        else{
            redirectToPage = new PageReference('/apex/DailySiteJob_VF?unitId='+unitIdParam+'&siteId='+siteIdParam+'&contractId='+contractIdParam+'&unitType='+unitTypeParam+'&retURL='+retUrl);
        }
        redirectToPage.setRedirect(true);
        return redirectToPage;
        
    }
}