force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Daily_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Summary_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Site Job Summary</label>
    <referenceTo>Daily_Summary_Report__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Report Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Manager - Approved</fullName>
            </value>
            <value>
                <fullName>Ops - Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/Daily_Summary_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Site Job Summary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Job Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ops Mgr - Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <label>Invoiced - Draft</label>
            </value>
            <value>
                <fullName>Invoiced - Disputed</fullName>
                <label>Disputed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Summary_Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Summary_Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Summary Report Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/WD_Camp__c.field-meta.xml
<CustomField>
    <fullName>WD_Camp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WD Camp</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Site (WD Camp)</relationshipLabel>
    <relationshipName>Site1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/WD_Rig__c.field-meta.xml
<CustomField>
    <fullName>WD_Rig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WD Rig</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI__c.field-meta.xml
<CustomField>
    <fullName>LTI__c</fullName>
    <label>LTI</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>LTI_Reset_Date__c</fullName>
    <description>When the LTI field is changed back to zero the LTI Date will automatically reset to the day this happened</description>
    <label>LTI Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailyReportTrigger_Test.cls
@isTest
public class DailyReportTrigger_Test {
    
    //This test method covers updateLTI and preventDuplicateReport methods
    static testMethod void testMethod1(){
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            List<Unit__c> insertUnitList = new List<Unit__c>();
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            insertUnitList.add(rigUnit);
            
            Unit__c campUnit = testData.createCampUnit();
            campUnit.Contract_New__c = cont.Id;
            campUnit.LTI_Reset_Date__c = System.today() - 5;
            insertUnitList.add(campUnit);
            
            insert insertUnitList;
            
            Site__c site = testData.createSite();
            site.Account__c = acc.Id;
            site.Contract__c = cont.Id;
            insert site;          
            
            List<Daily_Summary_Report__c> dailySummaryReportList = new List<Daily_Summary_Report__c>();  
            
            Daily_Summary_Report__c dsr = new Daily_Summary_Report__c();
            dsr.Contract__c = cont.Id;
            dsr.Site__c = site.Id;
            dsr.Summary_Report_Date__c = System.today();
            dsr.Status__c = 'Open';
            dailySummaryReportList.add(dsr);
            
            Daily_Summary_Report__c dsr2 = dsr.clone(false);
            dsr2.Summary_Report_Date__c = system.today() + 1;
            dailySummaryReportList.add(dsr2);
            
            Daily_Summary_Report__c dsr3 = dsr.clone(false);
            dsr3.Summary_Report_Date__c = system.today() + 2;
            dailySummaryReportList.add(dsr3);         
            insert dailySummaryReportList;
            
            List<Daily_Report__c> dailyReportList = new List<Daily_Report__c>();
            
            Daily_Report__c dailyReportRig = testData.createRigDailyReport();
            dailyReportRig.Contract__c = cont.Id;
            dailyReportRig.Site__c = site.Id;
            dailyReportRig.Unit__c = rigUnit.Id;
            dailyReportList.add(dailyReportRig);        
            
            Daily_Report__c dailyReportCamp = testData.createCampDailyReport();
            dailyReportCamp.Contract__c = cont.Id;
            dailyReportCamp.Site__c = site.Id;
            dailyReportCamp.Unit__c = campUnit.Id;
            dailyReportCamp.Status__c = 'Submitted';
            dailyReportList.add(dailyReportCamp);       
            
            Daily_Report__c dailyReportCamp2 = dailyReportCamp.clone(false);
            dailyReportCamp2.Report_Date__c = system.today() + 1;
            dailyReportList.add(dailyReportCamp2);          
            
            Daily_Report__c dailyReportCamp3 = dailyReportCamp.clone(false);
            dailyReportCamp3.Report_Date__c = system.today() + 2;
            dailyReportList.add(dailyReportCamp3);   
            
            Test.startTest();
            insert dailyReportList;
            
            delete [select Id from Daily_Report__c where Id= :dailyReportCamp3.Id];
            
            Daily_Report__c dailyReportCamp4 = dailyReportCamp.clone(false);
            dailyReportCamp4.Report_Date__c = system.today();
            insert dailyReportCamp4;
            Test.stopTest();
        }
        
        catch(Exception e){
            String errorMessage = 'Cannot create daily report. A Daily Report of the same type for this day has been already created for the Site';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            //System.assertEquals(exceptionThrown, true);
            
        }
    }
    
    //This method covers the preventOpenReport method
    static testMethod void testMethod2(){
        
        try{
            TestDataFactory testData = new TestDataFactory();
            
            Account acc = testData.createAccount();
            insert acc;
            
            Contract__c cont = testData.createContract();
            cont.Account__c = acc.Id;
            insert cont;
            
            List<Unit__c> unitList = new List<Unit__c>();
            
            Unit__c rigUnit = testData.createRigUnit();
            rigUnit.Contract_New__c = cont.Id;
            rigUnit.LTI_Reset_Date__c = System.today() - 5;
            unitList.add(rigUnit);
            
            Unit__c campUnit = testData.createCampUnit();
            campUnit.Contract_New__c = cont.Id;
            campUnit.LTI_Reset_Date__c = System.today() - 5;
            unitList.add(campUnit);
            
            insert unitList;
            
            Site__c site = testData.createSite();
            site.Account__c = acc.Id;
            site.Contract__c = cont.Id;
            insert site;
            
            Daily_Report__c dailyReportCamp = testData.createCampDailyReport();
            dailyReportCamp.Contract__c = cont.Id;
            dailyReportCamp.Site__c = site.Id;
            dailyReportCamp.Unit__c = campUnit.Id;
            dailyReportCamp.Status__c = 'Open';
            Test.startTest();
            insert dailyReportCamp;
            
            Daily_Report__c dailyReportCamp2 = dailyReportCamp.clone(false);
            dailyReportCamp2.Report_Date__c = system.today() + 1;
            insert dailyReportCamp2;
            Test.stopTest();
        }
        catch(Exception e){
            String errorMessage = 'Daily Report cannot be created since a Daily Report';
            Boolean exceptionThrown = e.getMessage().contains(errorMessage) ? true : false;
            System.assertEquals(exceptionThrown, true);
        }
        
    }   
    
    //This method covers the updateLTI method 
    static testMethod void testMethod3(){
        
        TestDataFactory testData = new TestDataFactory();
        
        Account acc = testData.createAccount();
        insert acc;
        
        Contract__c cont = testData.createContract();
        cont.Account__c = acc.Id;
        insert cont;
        
        List<Unit__c> unitList = new List<Unit__c>();
        
        Unit__c rigUnit = testData.createRigUnit();
        rigUnit.Contract_New__c = cont.Id;
        rigUnit.LTI_Reset_Date__c = System.today() - 5;
        unitList.add(rigUnit);        
        insert unitList;
        
        Site__c site = testData.createSite();
            site.Account__c = acc.Id;
            site.Contract__c = cont.Id;
            insert site;
        
        List<Daily_Report__c> dailyReportList = new List<Daily_Report__c>();
        Daily_Report__c dailyReportRig = testData.createRigDailyReport();
        dailyReportRig.Contract__c = cont.Id;
        dailyReportRig.Site__c = site.Id;
        dailyReportRig.Unit__c = rigUnit.Id;
        dailyReportList.add(dailyReportRig);
        insert dailyReportList;
        
        system.assertEquals(1, [Select Id,LTI__c from Unit__c where Id = :rigUnit.Id].LTI__c);
        
    
    }
    
    static testMethod void testDeletion(){
        TestDataFactory testData = new TestDataFactory();
            
        Account acc = testData.createAccount();
        insert acc;
        
        Contract__c cont = testData.createContract();
        cont.Account__c = acc.Id;
        insert cont;
        
        List<Unit__c> insertUnitList = new List<Unit__c>();
        
        Unit__c campUnit = testData.createCampUnit();
        campUnit.Contract_New__c = cont.Id;
        campUnit.LTI_Reset_Date__c = System.today() - 5;
        insertUnitList.add(campUnit);
        
        insert insertUnitList;
        
        Site__c site = testData.createSite();
        site.Account__c = acc.Id;
        site.Contract__c = cont.Id;
        site.WD_Camp__c = campUnit.Id;
        site.WD_Rig__c = campUnit.Id; // stand alone
        insert site;          
        
        List<Daily_Summary_Report__c> dailySummaryReportList = new List<Daily_Summary_Report__c>();  
        
        Daily_Summary_Report__c dsr = new Daily_Summary_Report__c();
        dsr.Contract__c = cont.Id;
        dsr.Site__c = site.Id;
        dsr.Summary_Report_Date__c = System.today();
        dsr.Status__c = 'Open';
        dailySummaryReportList.add(dsr);
        
        Daily_Report__c dailyReportCamp = testData.createCampDailyReport();
        dailyReportCamp.Contract__c = cont.Id;
        dailyReportCamp.Site__c = site.Id;
        dailyReportCamp.Unit__c = campUnit.Id;
        dailyReportCamp.Status__c = 'Open';
        insert dailyReportCamp;
        dailyReportCamp.Status__c = 'Submitted';
        update dailyReportCamp;
        try {
            delete dailyReportCamp;
        }
        catch (Exception e){
            system.assertNotEquals(null, e.getMessage());
        }
        dailyReportCamp.Status__c = 'Open';
        //update dailyReportCamp;
        //delete dailyReportCamp;
    }
    
}