force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/Contract_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Job Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Contract__r.Account_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Add_to_NDT__c.field-meta.xml
<CustomField>
    <fullName>Add_to_NDT__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, item&apos;s hours will be calculated for NDT Hours on Unit</inlineHelpText>
    <label>Add to NDT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Contract_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Item__c.BundledItem__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Contract Job Items</relationshipLabel>
    <relationshipName>Contract_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>If not selected then auto-populated from Item</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/Daily_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Job Item</label>
    <nameField>
        <displayFormat>DJI-{000000}</displayFormat>
        <label>Daily Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Daily_Report__r.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Contract_Job_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Job_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Job Item</label>
    <referenceTo>Contract_Item__c</referenceTo>
    <relationshipLabel>Daily Job Items</relationshipLabel>
    <relationshipName>Daily_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>Daily_Report__c</referenceTo>
    <relationshipName>Daily_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <formula>Contract_Job_Item__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Item Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Used only for Items where the Service Type is of type Quantity</description>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Add_to_NDT__c.field-meta.xml
<CustomField>
    <fullName>Add_to_NDT__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Add to NDT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Active__c.field-meta.xml
<CustomField>
    <fullName>Site_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Site Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>LTI_Reset_Date__c</fullName>
    <description>When the LTI field is changed back to zero the LTI Date will automatically reset to the day this happened</description>
    <label>LTI Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>Field Camp/Rig - purpose built for contract
Base - Permanent building/Camp 
Department - section of business that may require identifying for expense purposes</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qld Depot</fullName>
                <label>Qld - Depot</label>
            </value>
            <value>
                <fullName>Camp - Qld</fullName>
                <label>Qld - Camp</label>
            </value>
            <value>
                <fullName>Rig - Qld</fullName>
                <label>Qld - Rig</label>
            </value>
            <value>
                <fullName>Depot - Roma</fullName>
                <label>SA - Depot</label>
            </value>
            <value>
                <fullName>Camp - SA</fullName>
                <label>SA - Camp</label>
            </value>
            <value>
                <fullName>Rig - SA</fullName>
                <label>SA - Rig</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Field - Rig</fullName>
            </value>
            <value>
                <fullName>Field - Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailyReportItemTrigger_Test.cls
/******************************************************************************
* @author        Kunal Jain
* @date         
* @description   This is a test class for DailyReportItemTrigger_Handler
******************************************************************************/
@isTest
public class DailyReportItemTrigger_Test {
    
    static testMethod void testMethod1(){
        
        
        TestDataFactory testData = new TestDataFactory();
        
        List<Item__c> itemInsertList = new List<Item__c>();
        Item__c item = testData.createItemCampStandy();
        itemInsertList.add(item);
        
        Item__c item2 = testData.createItemRigOperating();
        itemInsertList.add(item2);
        
        Item__c item3 = item2.clone(false);
        itemInsertList.add(item3);
        
        insert itemInsertList;
        
        Account acc = testData.createAccount();
        acc.Regions_LG_Area__c = 'VIC';
        insert acc;
        
        Contract__c cont = testData.createContract();
        cont.Account__c = acc.Id;
        insert cont;
        
        List<Contract_Item__c> contractItemList = new List<Contract_Item__c>();
        Contract_Item__c contractItem = testData.createContractJobItem();
        contractItem.Contract__c = cont.Id;
        contractItem.Item_Name__c = item.Id;
        contractItem.Add_to_NDT__c = true;
        contractItemList.add(contractItem);
        
        Contract_Item__c contractItem2 = testData.createContractJobItem();
        contractItem2.Unit_Type__c = 'Rig';
        contractItem2.Contract__c = cont.Id;
        contractItem2.Item_Name__c = item2.Id;
        contractItem2.Add_to_NDT__c = true;
        contractItemList.add(contractItem2);
        
        Contract_Item__c contractItem3 = contractItem2.clone(false);
        contractItemList.add(contractItem3);
        
        insert contractItemList;
        
        List<Unit__c> unitInsertList = new List<Unit__c>();
        Unit__c rigUnit = testData.createRigUnit();
        rigUnit.Contract_New__c = cont.Id;
        rigUnit.LTI_Reset_Date__c = System.today() - 5;
        unitInsertList.add(rigUnit);
        
        Unit__c campUnit = testData.createCampUnit();
        campUnit.Contract_New__c = cont.Id;
        campUnit.LTI_Reset_Date__c = System.today() - 5;
        unitInsertList.add(campUnit);
        
        insert unitInsertList;
        
        List<Site__c> siteInsertList = new List<Site__c>();
        Site__c site1 = testData.createSite();
        site1.Account__c = acc.Id;
        site1.Contract__c = cont.Id;
        site1.Site_Active__c = true;
        siteInsertList.add(site1);
        
        Site__c site2 = testData.createSite();
        site2.Name = 'Test Site 2';
        site2.Account__c = acc.Id;
        site2.Contract__c = cont.Id;
        site2.Site_Active__c = true;
        siteInsertList.add(site2);
        
        insert siteInsertList;
        
        Daily_Report__c dailyReportRig = testData.createRigDailyReport();
        dailyReportRig.Contract__c = cont.Id;
        dailyReportRig.Site__c = site1.Id;
        dailyReportRig.Unit__c = rigUnit.Id;
        insert dailyReportRig;
        
        List<Daily_Report_Item__c> reportItemInsertList = new List<Daily_Report_Item__c>();
        Daily_Report_Item__c dailyReportItem = new Daily_Report_Item__c();
        dailyReportItem.Daily_Report__c = dailyReportRig.Id;
        dailyReportItem.Start_Time__c = System.now().addHours(-1);
        dailyReportItem.End_Time__c = System.now().addHours(1);
        dailyReportItem.Contract_Job_Item__c = contractItem2.Id;
        reportItemInsertList.add(dailyReportItem);
        
        Daily_Report_Item__c dailyReportItem3 = dailyReportItem.clone(false);
        dailyReportItem.Contract_Job_Item__c = contractItem3.Id;
        reportItemInsertList.add(dailyReportItem3);
        
        insert reportItemInsertList;
        
        delete dailyReportItem3;
        
        List<Daily_Report__c> reportInsertList = new List<Daily_Report__c>();
        Daily_Report__c dailyReportCamp = testData.createCampDailyReport();
        dailyReportCamp.Contract__c = cont.Id;
        dailyReportCamp.Site__c = site1.Id;
        dailyReportCamp.Unit__c = campUnit.Id;
        reportInsertList.add(dailyReportCamp);
        
        Daily_Report__c dailyReportCamp2 = testData.createCampDailyReport();
        dailyReportCamp2.Contract__c = cont.Id;
        dailyReportCamp2.Site__c = site2.Id;
        dailyReportCamp2.Unit__c = campUnit.Id;
        reportInsertList.add(dailyReportCamp2);
        
        insert reportInsertList;
        
        Daily_Report_Item__c dailyReportItem2 = new Daily_Report_Item__c();
        dailyReportItem2.Daily_Report__c = dailyReportCamp2.Id;
        dailyReportItem2.Quantity__c = 6.0;
        dailyReportItem2.Contract_Job_Item__c = contractItem.Id;
        insert dailyReportItem2;
        
    }
}