force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Manager - Approved</fullName>
            </value>
            <value>
                <fullName>Ops - Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/recordTypes/Transport.recordType-meta.xml
<RecordType>
    <fullName>Transport</fullName>
    <active>true</active>
    <label>Transport</label>
</RecordType>

force-app/main/default/objects/Daily_Summary_Report__c/Daily_Summary_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Site Job Summary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Job Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Status__c</fullName>
    <formula>TEXT(Site__r.Site_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Site Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ops Mgr - Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <label>Invoiced - Draft</label>
            </value>
            <value>
                <fullName>Invoiced - Disputed</fullName>
                <label>Disputed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Status__c</fullName>
    <inlineHelpText>Open: Active;
Open - Inactive: Inactive,Winding up;
Closed: Inactive, Work Complete;</inlineHelpText>
    <label>Site Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Inv - Draft</fullName>
            </value>
            <value>
                <fullName>Inv - Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Inv - Approved</fullName>
            </value>
            <value>
                <fullName>Inv - Disputed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Inv - Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Job__c/Transport_Job__c.object-meta.xml
<CustomObject>
    <label>Transport Job</label>
    <nameField>
        <displayFormat>TJ-{0000000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Job__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <description>Info from Site record</description>
    <formula>HYPERLINK(&apos;/&apos;+Site__r.Contract__c , Site__r.Contract__r.Name, &apos;_self&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND ((2 AND 3) OR 4 OR 5)</booleanFilter>
        <filterItems>
            <field>Site__c.Site_Status__c</field>
            <operation>equals</operation>
            <value>Open, Open - Inactive, Open, Open - Inactive, Closed</value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Camp__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Rig__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Camp__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <filterItems>
            <field>Site__c.WD_Rig__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Transport Jobs</relationshipLabel>
    <relationshipName>Transport_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteTrigger_Handler.cls
/**
 * @description       : 
 * @author            : Donnie Banez
 * @group             : 
 * @last modified on  : 06-09-2020
 * @last modified by  : Donnie Banez
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   06-09-2020   Donnie Banez   Initial Version
**/
public class SiteTrigger_Handler {
    
    public static Boolean SiteTriggerHandlerRecursion = false;
    
    //This method prevents Site Status Close if all Daily Reports are not submitted
    public static void preventSiteStatusClose(List<Site__c> triggernew, Map<Id, Site__c> triggerOldMap) {
        try {
            Set<Id> siteIdSet = new Set<Id>();
            
            for (Site__c sitedata : triggernew) {
                system.debug('sitedata: ' + sitedata);
                system.debug('sitedata.Site_Status__c: ' + sitedata.Site_Status__c);
                system.debug('sitedata.Site_Status__c previous: ' + triggerOldMap.get(sitedata.Id).Site_Status__c);
                if (sitedata.Contract__c != null && sitedata.Site_Status__c == 'Closed' && triggerOldMap.get(sitedata.Id).Site_Status__c != 'Closed') {
                    siteIdSet.add(sitedata.Id);
                }
            }
            system.debug('siteIdSet: ' + siteIdSet);
            /*List <Site__c> sitelist = [SELECT Id,(SELECT Id,Site__c,Status__c FROM Daily_Reports__r WHERE (Status__c = null OR Status__c = 'Open')) FROM Site__c WHERE Id IN: siteIdSet ]; */
            List <Site__c> sitelist = [SELECT Id, 
                            (SELECT Id FROM Daily_Summary_Reports__r WHERE Status__c != 'Approved'),
                            (select Id, Name, OwnerId, Owner.Name, Status__c, Job_Date__c, Site__c, Unit__c, Billable__c,
                                    Category__c from Transport_Jobs__r where Billable__c = true and
                                (Status__c = 'Assigned' or Status__c = 'In Progress' or Status__c = 'Completed'))
                            FROM Site__c WHERE Id IN:siteIdSet AND Contract__c != null];
           
            system.debug('sitelist: ' + sitelist);
            if (sitelist != null && !sitelist.isEmpty()) {
                for (Site__c sitedata : triggernew) {
                    for (Site__c site : sitelist) {
                        if (sitedata.Id == site.Id && site.Daily_Summary_Reports__r.size() > 0) {
                            sitedata.addError(' Site Status cannot be set to Closed since the all the Daily Summary Reports have not been Approved yet.');
                        }
                        if (sitedata.Id == site.Id && site.Transport_Jobs__r.size() > 0) {
                            sitedata.addError(' Site Status cannot be set to Closed since there are still open Transport Jobs.');
                        }
                    }
                }
            }
        } catch (Exception e) {
            System.debug('At ' + e.getLineNumber() + '. Cause: ' + e.getCause() + '. ErrorMessage: ' + e.getMessage());
        }
    }
    
    public static void preventActiveSite(List<Site__c> triggernew) {
        
        list<RollUpSummaryUtility.fieldDefinition> fieldDefinitions =
            new list<RollUpSummaryUtility.fieldDefinition>{
                new RollUpSummaryUtility.fieldDefinition('COUNT', 'Id', 'Total_Active_Site__c')
                    };
                        RollUpSummaryUtility.rollUpTrigger(fieldDefinitions, triggernew, 'Site__c', 'Contract__c', 'Contract__c', 'AND Site_Active__c = true');
        SiteTrigger_Handler.SiteTriggerHandlerRecursion = true;
        
    }
    
    public static void preventSiteDelete(Map<Id, Site__c> triggerOldMap) {
        
        try {
            Map<Id, Integer> siteIdRelatedRecordCount = new Map<Id, Integer>();
            for (Site__c site : triggerOldMap.values()) {
                if(site.Contract__c != null){
                    siteIdRelatedRecordCount.put(site.Id, 0);
                }
                
            }
            
            if(!siteIdRelatedRecordCount.keyset().isEmpty()){
                List<Daily_Report__c> dailyReportList = [Select Id,Site__c from Daily_Report__c where Site__c IN :triggerOldMap.keySet()];
                List<Daily_Summary_Report__c> dailySummaryReportList = [Select Id,Site__c from Daily_Summary_Report__c where Site__c IN :triggerOldMap.keySet()];
                //List<Invoice__c> invoiceList = [Select Id,Site__c from Invoice__c where Site__c IN :triggerOldMap.keySet()];
                
                if (!dailyReportList.isEmpty()) {
                    for (Daily_Report__c dailyReport : dailyReportList) {
                        Integer count = siteIdRelatedRecordCount.get(dailyReport.Site__c) + 1;
                        siteIdRelatedRecordCount.put(dailyReport.Site__c, count);
                    }
                }
                
                if (!dailySummaryReportList.isEmpty()) {
                    for (Daily_Summary_Report__c dailySummaryReport : dailySummaryReportList) {
                        Integer count = siteIdRelatedRecordCount.get(dailySummaryReport.Site__c) + 1;
                        siteIdRelatedRecordCount.put(dailySummaryReport.Site__c, count);
                    }
                }
                
                /*if (!invoiceList.isEmpty()) {
                    for (Invoice__c invoice : invoiceList) {
                    Integer count = siteIdRelatedRecordCount.get(invoice.Site__c) + 1;
                    siteIdRelatedRecordCount.put(invoice.Site__c, count);
                    }
                    }*/
                
                for (Site__c site : triggerOldMap.values()) {
                    if (siteIdRelatedRecordCount.get(site.Id) > 0) {
                        site.addError('You cannot delete a Site when there are records associated with it.');
                    }
                }
            }
            
            
        } catch (Exception e) {
            System.debug('In apex class: SiteTrigger_Handler . At line ' + e.getLineNumber() + '. Cause: ' + e.getCause() + '. ErrorMessage: ' + e.getMessage());
        }
        
        
    }
    
}