force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Site_Status__c.field-meta.xml
<CustomField>
    <fullName>Site_Status__c</fullName>
    <inlineHelpText>Open: Active;
Open - Inactive: Inactive,Winding up;
Closed: Inactive, Work Complete;</inlineHelpText>
    <label>Site Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Open - Inactive</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ready to Invoice</fullName>
            </value>
            <value>
                <fullName>Inv - Draft</fullName>
            </value>
            <value>
                <fullName>Inv - Sent for Approval</fullName>
            </value>
            <value>
                <fullName>Inv - Approved</fullName>
            </value>
            <value>
                <fullName>Inv - Disputed</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
                <label>Inv - Paid</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateQuoteController.cls
public class GenerateQuoteController {
    //Apex properties or variables
    public Id contractId {get; set;}
    public Id siteId { get; set; }
    public site__c site{get;set;}
    //constructor to get the Case record
    public GenerateQuoteController(ApexPages.StandardController controller) {
    site__c sites =  (site__c) controller.getRecord();
    Id siteId = sites.Id;
    site=[select id,Contract__c,Site_Status__c  from site__c where id=:siteId limit 1];
    contractId=site.Contract__c; 
    }
public PageReference quoteExecution() {
     
    if(this.site.Site_Status__c!='Closed'){
         ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Cannot Generate an Invoice for a Site that is not Closed.'));
      
    }
    else{
        try{
        GenerateInvoice.generateInvoiceRecord(contractId, siteId);
        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'You have successfully generated an Invoice.'));
        } catch(exception ex){
             ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,ex.getMessage()));
      
        }
    }
    return null; 
    }    

   
}