force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Item__c/Contract_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Job Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Item__c/fields/Add_to_NDT__c.field-meta.xml
<CustomField>
    <fullName>Add_to_NDT__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, item&apos;s hours will be calculated for NDT Hours on Unit</inlineHelpText>
    <label>Add to NDT</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Contract_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/Item_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Item_Frequency__c</fullName>
    <label>Item Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Per Day</fullName>
            </value>
            <value>
                <fullName>Per Site</fullName>
            </value>
            <value>
                <fullName>Multi Per Day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Auto_Create_Daily_Report_Items__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Daily_Report_Items__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Create Daily Report Items</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Report Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/Daily_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Job Item</label>
    <nameField>
        <displayFormat>DJI-{000000}</displayFormat>
        <label>Daily Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Item__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <formula>Daily_Report__r.Contract__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contract</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Contract_Job_Item__c.field-meta.xml
<CustomField>
    <fullName>Contract_Job_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract Job Item</label>
    <referenceTo>Contract_Item__c</referenceTo>
    <relationshipLabel>Daily Job Items</relationshipLabel>
    <relationshipName>Daily_Report_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>Daily_Report__c</referenceTo>
    <relationshipName>Daily_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Item_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Item_Frequency__c</fullName>
    <formula>TEXT( Contract_Job_Item__r.Item_Frequency__c )</formula>
    <label>Item Frequency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Report_Item__c/fields/Number_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Hours__c</fullName>
    <description>Used only for Items where the Service Type is of type Hourly</description>
    <formula>((End_Time__c - Start_Time__c) * 1440)/60</formula>
    <label>Number of Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Date_Last_ndt__c.field-meta.xml
<CustomField>
    <fullName>Date_Last_ndt__c</fullName>
    <inlineHelpText>When specified, NDT hours are computed from this date onwards. If blank, it counts all NDT hours for this Unit</inlineHelpText>
    <label>NDT Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/NDT_Hours__c.field-meta.xml
<CustomField>
    <fullName>NDT_Hours__c</fullName>
    <description>Auto-populated by the Daily Job Item Trigger</description>
    <inlineHelpText>Auto-populated by the Daily Job Item Trigger</inlineHelpText>
    <label>NDT Hours</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DailyReportItem_Handler.cls
/******************************************************************************
* @author        Kunal Jain
* @date         
* @description   This is a handler class for DailyReportItemTrigger
* @TestClass     DailyReportItemTrigger_Test
******************************************************************************/

public class DailyReportItem_Handler {
    
    public static Boolean DailyReportItemTriggerRecursion = false;
    
    /***********************************************************************************************
* @description: This method prevents a Daily Report Item from being added if a
* Daily Report for the day has already been created and item's Frequency is per day or per site
************************************************************************************************/
    /*****************************************************************************************
* Code commented by: Kunal Jain
* Reason: The handling of Per Day/Per Site Item is now being handled implicitly by visual
* workflow "Auto Create DR Items & Active Personnels PB Flow".
* It's also handled when the a Daily Site Job Item is being added.
******************************************************************************************/
    /*public static void preventDailyReportItem(List<Daily_Report_Item__c> triggernew){

try{
Set<Id> dailyReportIdSet = new Set<Id>();
Set<Id> contractIdSet = new Set<Id>();
Map<Id,List<Daily_Report__c>> dailyReportsMap = new Map<Id,List<Daily_Report__c>>();

for(Daily_Report_Item__c dri: triggernew){
if(dri.Daily_Report__c != null && dri.Contract_Job_Item__c != null && (dri.Item_Frequency__c == 'Per Day' || dri.Item_Frequency__c == 'Per Site')){
dailyReportIdSet.add(dri.Daily_Report__c);
}
}

List<Daily_Report__c> dailyReportsList = [Select Id,Site__c,Type__c,Contract__c,Unit__c,Auto_Create_Daily_Report_Items__c,Report_Date__c from Daily_Report__c where Id IN: dailyReportIdSet AND
Contract__c != null];

if(dailyReportsList != null && !dailyReportsList.isEmpty()){
for(Daily_Report__c dr: dailyReportsList){
contractIdSet.add(dr.Contract__c);
}

if(contractIdSet != null && !contractIdSet.isEmpty()){
List<Daily_Report__c> dailyReportsListOther = [Select Id,Site__c,Type__c,Contract__c,Unit__c,Auto_Create_Daily_Report_Items__c,Report_Date__c from Daily_Report__c where Contract__c IN: contractIdSet AND
Contract__c != null];

if(dailyReportsListOther != null && !dailyReportsListOther.isEmpty()){
for(Daily_Report__c dr: dailyReportsListOther){
if(dailyReportsMap.containsKey(dr.Contract__c) && dailyReportsMap.get(dr.Contract__c) != null){
dailyReportsMap.get(dr.Contract__c).add(dr);
}
else{
dailyReportsMap.put(dr.Contract__c, new List<Daily_Report__c>{dr});
}
}
}
}

for(Daily_Report_Item__c dri: triggernew){
for(Daily_Report__c dr: dailyReportsList){
if(dri.Daily_Report__c == dr.Id){
if(dailyReportsMap.containsKey(dr.Contract__c) && dailyReportsMap.get(dr.Contract__c) != null){

for(Daily_Report__c drc: dailyReportsMap.get(dr.Contract__c)){

//To check for Per Day
if(dri.Item_Frequency__c == 'Per Day' && dr.Id != drc.Id && dr.Report_Date__c == drc.Report_Date__c && dr.Unit__c == drc.Unit__c && dr.Type__c == drc.Type__c){
dri.addError('This item whose frequency is per day has already been added for the day. You cannot add it again for the same day.');
}

//To check for Per Site
if(dri.Item_Frequency__c == 'Per Site' && dr.Id != drc.Id && dr.Type__c == drc.Type__c && dr.Site__c == drc.Site__c){
dri.addError('This item whose frequency is per site has already been added for the site. You cannot add it again for another site.');
}
}
}
}
}
}
}
}
catch(Exception e){
System.debug('At '+e.getLineNumber()+'. Cause: '+e.getCause()+'. ErrorMessage: '+e.getMessage());
}
}*/
    
    
    
    
    /***********************************************************************************
* @description: This method Totals up the Hours from the Daily Report Item and
* add it to the report's related Unit
************************************************************************************/
    public static void addToNdt(List<Daily_Report_Item__c> triggernew){
        DailyReportItem_Handler.DailyReportItemTriggerRecursion = true;
        Set<Id> dailyReportIdSet = new Set<Id>();
        Set<Id> unitIdSet = new set<Id>();
        
        for(Daily_Report_Item__c dailyReportItem: triggernew){
            dailyReportIdSet.add(dailyReportItem.Daily_Report__c);
        }
        
        List<Daily_Report__c> dailyReportList = [Select Id,Name,Unit__c,Report_Date__c from Daily_Report__c where Id IN :dailyReportIdSet LIMIT 50000];
        for(Daily_Report__c dailyReport: dailyReportList){
            if(dailyReport.Unit__c != null){
                unitIdSet.add(dailyReport.Unit__c);
            }
        }
        
        if(!unitIdSet.isEmpty()){
            
            Map<Id,Decimal> unitNdtHoursMap = new Map<Id,Decimal>();
            
            List<Daily_Report__c> dailyReportMainList = [Select Id,Name,Unit__c,Report_Date__c,(Select Id,Name,Number_of_Hours__c,Contract_Job_Item__r.Add_to_NDT__c,Daily_Report__r.Unit__c
                                                                                                from Daily_Report_Items__r where Number_of_Hours__c != null AND
                                                                                                Contract_Job_Item__r.Add_to_NDT__c = true LIMIT 50000)
                                                         from Daily_Report__c where Unit__c IN: unitIdSet LIMIT 50000];
            
            Map<Id,Unit__c> unitMap = new Map<Id,Unit__c>([Select Id,Name,NDT_Hours__c,Date_Last_ndt__c from Unit__c where Id in :unitIdSet LIMIT 50000]);
            
            for(Daily_Report__c dailyReport: dailyReportMainList){
                if(!dailyReport.Daily_Report_Items__r.isEmpty()){
                    for(Daily_Report_Item__c dailyReportItem: dailyReport.Daily_Report_Items__r){
                        Unit__c unit = unitMap.get(dailyReport.Unit__c);
                        Decimal oldNdtHours = 0;
                        
                        if(unitNdtHoursMap.containsKey(unit.Id)){
                            oldNdtHours = unitNdtHoursMap.get(unit.Id);
                        }
                        
                        if(unit.Date_Last_ndt__c != null){
                            if(dailyReport.Report_Date__c >= unit.Date_Last_ndt__c){
                                oldNdtHours += dailyReportItem.Number_of_Hours__c;    
                            }                            
                        } else {
                            oldNdtHours += dailyReportItem.Number_of_Hours__c;
                        }
                        
                        unitNdtHoursMap.put(unit.Id,oldNdtHours);
                    }
                }
            }
            
            if(!unitNdtHoursMap.isEmpty()){
                DailyReportItem_Handler.DailyReportItemTriggerRecursion = true;
                List<Unit__c> unitUpdateList = new List<Unit__c>();
                for(Id unitId: unitNdtHoursMap.keyset()){
                    Unit__c unit = new Unit__c();
                    unit.Id = unitId;
                    unit.NDT_Hours__c = unitNdtHoursMap.get(unitId);
                    unitUpdateList.add(unit);
                }
                
                
                update unitUpdateList;
            }
            
            
        }
        
        
    }
    
}