force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Daily_Summary_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Summary_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Daily Site Job Summary</label>
    <referenceTo>Daily_Summary_Report__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Report_Date__c.field-meta.xml
<CustomField>
    <fullName>Report_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Report Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Manager - Approved</fullName>
            </value>
            <value>
                <fullName>Ops - Approved</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rig</fullName>
            </value>
            <value>
                <fullName>Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 3) OR (4 AND 5)</booleanFilter>
        <errorMessage>The Unit Details assigned to this DSJ is invalid. Check Contract, Unit type, Job type. Make sure that the Contract in the DSJ matches the contract in Unit Contract # and the Rig/Camp Daily Site Job Type matches the type of the Unit)</errorMessage>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Unit__c.Contract_New__c</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <valueField>$Source.Type__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Rig, Camp</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.UnitType__c</field>
            <operation>equals</operation>
            <value>Transport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Daily Site Jobs</relationshipLabel>
    <relationshipName>Daily_Reports</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/fields/UnitIsStandAlone__c.field-meta.xml
<CustomField>
    <fullName>UnitIsStandAlone__c</fullName>
    <description>8 May: changed definitions to also return true if only one unit is populated</description>
    <formula>(Site__r.WD_Camp__c =  Site__r.WD_Rig__c)
||
ISBLANK(Site__r.WD_Rig__c)
||
ISBLANK(Site__r.WD_Camp__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>If the WD Camp and WD Rig in Site is the same</inlineHelpText>
    <label>Unit is Stand Alone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Report__c/recordTypes/Transport.recordType-meta.xml
<RecordType>
    <fullName>Transport</fullName>
    <active>true</active>
    <label>Transport</label>
</RecordType>

force-app/main/default/objects/Daily_Summary_Report__c/Daily_Summary_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job Summary</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Daily Site Job Summary No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Job Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Daily_Summary_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Summary_Report__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ops Mgr - Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <label>Invoiced - Draft</label>
            </value>
            <value>
                <fullName>Invoiced - Disputed</fullName>
                <label>Disputed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Previous_Site_Look_up__c.field-meta.xml
<CustomField>
    <fullName>Previous_Site_Look_up__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Site</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Site__c.Contract__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.Id</field>
            <operation>notEqual</operation>
            <valueField>Site__c.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/fields/WD_Rig__c.field-meta.xml
<CustomField>
    <fullName>WD_Rig__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WD Rig</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Site</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TriggerAutomations__c/TriggerAutomations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Automations</label>
</CustomObject>

force-app/main/default/objects/TriggerAutomations__c/fields/DailySiteJob__c.field-meta.xml
<CustomField>
    <fullName>DailySiteJob__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Daily Site Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI__c.field-meta.xml
<CustomField>
    <fullName>LTI__c</fullName>
    <label>LTI</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DailySiteJobTriggerHandler.cls
/****
 * Apex Class for Daily Site Job Trigger Handler; 
 * Author: Whiteshed, D Banez
 * Date: Jan 2019 
 * Test Class: DailySiteJobTriggerHandlerTest
*/
public with sharing class DailySiteJobTriggerHandler {
	public static TriggerAutomations__c automationEnabled  = TriggerAutomations__c.getInstance(); 
	public static Boolean dsjEnabled = automationEnabled.DailySiteJob__c;
	public static Boolean DailyReportTriggerRecursion = false;
    
	public static void mainEntry(Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate,Boolean isDelete, Boolean isUnDelete, 
                    List<SObject> newList, List<SObject> oldList, Map<ID, SObject> newmap, Map<ID, SObject> oldmap)
    {
    	// In a test context always set this to true        
        if (Test.isrunningTest())  {
            dsjEnabled = true;
        }
        // Perform business logic
        if(dsjEnabled){
        	try{
            	// INSERT TRIGGER
                if(isInsert){
                    // Before
                    if(isBefore){
                    	preventDuplicateReport(newList);
            			preventOpenReport(newList);
                    }            
                    // After
                    if(isAfter){
                        if(!DailyReportTriggerRecursion){
                            updateLTI(newList);
                        }
                    }
                }
                // Update TRIGGER
                if(isUpdate){
                    // Before
                    if(isBefore){
                    	
                    }            
                    // After
                    if(isAfter){
                   		
                    }
                }
                // Delete TRIGGER
                if(isDelete){
                    // Before
                    if(isBefore){
                        preventDeletionOfSubmittedReport (oldList);
                    }            
                    // After
                    if(isAfter){
                    	deleteParentDSJSIfStandAlone(oldList);
                    }
                }
                // UNDELETE Trigger
                if(isUnDelete){}  
            } catch (Exception ex){
            	//String errorString = ex.getStackTraceString()+'--'+ ex.getTypeName()+'--'+ ex.getMessage();
                newList[0].addError(ex.getStackTraceString()+'--'+ ex.getTypeName()+'--'+ ex.getMessage());
            }
        }
    }
    
    public static void updateLTI(List<Daily_Report__c> triggernew){
        
        Set<Id> unitIdSet = new Set<Id>();
        List<Unit__c> unitUpdateList = new List<Unit__c>();
        
        for(Daily_Report__c dr: triggernew){
            if(dr.Unit__c != null){
                unitIdSet.add(dr.Unit__c);
            }
        }
        
        if(!unitIdSet.isEmpty()){
            List<Unit__c> unitList = [Select Id,LTI__c,(Select Id,Report_Date__c from Daily_Reports__r where CreatedDate = Today LIMIT 2) from Unit__c where Id IN :unitIdSet];
            
            for(Unit__c unit: unitList){
                if(!unit.Daily_Reports__r.isEmpty() && unit.Daily_Reports__r.size() == 1){
                    unit.LTI__c = unit.LTI__c != null ? unit.LTI__c + 1 : 1;
                    unitUpdateList.add(unit);
                }
            }
            
            if(!unitUpdateList.isEmpty()){
                update unitUpdateList;
                DailyReportTriggerRecursion = true;
            }
            
        }
    }
    
    public static void preventDeletionOfSubmittedReport (List<Daily_Report__c> oldList){
        // 25 May - check if user has ability to delete DSJ and DSJS 
        User u = [select Id, AbilityToDeleteDSJAndDSJS__c, Profile.Name from User where Id = :UserInfo.getUserId() limit 1];
        
        for (Daily_Report__c rep : oldList){
            // 26 March: Revised rules on deletion
            if (u.Profile.Name != 'System Administrator'){
                if (rep.Status__c == 'Approved' || rep.Status__c == 'Invoiced'){
                    rep.addError('Daily Site Jobs that are approved or invoiced can no longer be deleted');
                }
                else if (!u.AbilityToDeleteDSJAndDSJS__c && rep.Status__c != 'Open' && rep.Status__c != 'Rejected'){
                    rep.addError('You can only delete Open or Rejected Daily Site Jobs.');
                }
            }
        }
    }
    
    public static void deleteParentDSJSIfStandAlone(List<Daily_Report__c> oldList){
        Set<Id> parentDSJSIdSet = new Set<Id>();
        
        for (Daily_Report__c rep : oldList){
            if (rep.UnitIsStandAlone__c && rep.Type__c == 'Camp'){
                parentDSJSIdSet.add(rep.Daily_Summary_Report__c);
            }
        }
        
        if (parentDSJSIdSet.size() > 0){
            List<Daily_Summary_Report__c> parentDSJSToDelete = [select Id from Daily_Summary_Report__c where Id in :parentDSJSIdSet];
            Database.delete(parentDSJSToDelete, false);
        }
    }
    
    public static void preventDuplicateReport(List<Daily_Report__c> triggernew){
        
        try{
            Set<Id> siteIdSet = new Set<Id>();
            Map<Id,List<Daily_Report__c>> mapSiteDailyReport = new Map<Id,List<Daily_Report__c>>();//Map<Site,List<DailyReport>>
            
            for(Daily_Report__c dr: triggernew){
                if(dr.Site__c != null && dr.Type__c != null && dr.Unit__c != null && dr.Report_Date__c != null){
                    siteIdSet.add(dr.Site__c);
                }
            }
            system.debug('siteIdSet: ' + siteIdSet);
            if(siteIdSet != null && !siteIdSet.isEmpty()){
                //06 Sept 2020: DB - Allow to create Transport Daily Site Job
                List<Daily_Report__c> dailyReportList = [Select Id,Name,Site__c,Type__c,Unit__c,Report_Date__c,Site__r.Name from Daily_Report__c
                                                         where (Type__c != null AND Type__c != 'Transport' AND Unit__c != null AND Report_Date__c != null) AND Site__c IN: siteIdSet];
                system.debug('dailyReportList: ' + dailyReportList);
                if(dailyReportList != null && !dailyReportList.isEmpty()){
                    for(Daily_Report__c dr: dailyReportList){
                        if(mapSiteDailyReport.containsKey(dr.Site__c) && mapSiteDailyReport.get(dr.Site__c) != null){
                            mapSiteDailyReport.get(dr.Site__c).add(dr);
                        }
                        else{
                            mapSiteDailyReport.put(dr.Site__c, new List<Daily_Report__c> {dr});
                        }
                    }
                }
                system.debug('mapSiteDailyReport: ' + mapSiteDailyReport);
                for(Daily_Report__c dr: triggernew){
                    if(mapSiteDailyReport.containsKey(dr.Site__c) && mapSiteDailyReport.get(dr.Site__c) != null){
                        for(Daily_Report__c dr2: mapSiteDailyReport.get(dr.Site__c)){
                            if((dr.Report_Date__c == dr2.Report_Date__c) && (dr.Type__c == dr2.Type__c) && (dr.Unit__c == dr2.Unit__c)){
                                dr.addError('Cannot create daily report. A Daily Report of the same type for this day has been already created for the Site: ' + dr2.Site__r.Name);
                            }
                        }
                    }
                }
            }
        }
        catch(Exception e){System.debug('At '+e.getLineNumber()+'. Cause: '+e.getCause()+'. ErrorMessage: '+e.getMessage());}
    }
    
    public static void preventOpenReport(List<Daily_Report__c> triggernew){
        try{
            
            Set<Id> siteIdSet = new Set<Id>();
            Map<Id,List<Daily_Report__c>> mapSiteDailyReport = new Map<Id,List<Daily_Report__c>>();//Map<Site,List<DailyReport>>
            
            for(Daily_Report__c dr: triggernew){
                siteIdSet.add(dr.Site__c);
            }
            
            if(siteIdSet != null && !siteIdSet.isEmpty()){
                List<Daily_Report__c> dailyReportList = [Select Id,Name,Site__c,Type__c,Unit__c,Report_Date__c,Site__r.Name,Contract__c from Daily_Report__c
                                                         where Status__c = 'Open' AND Site__c IN: siteIdSet];
                
                if(dailyReportList != null && !dailyReportList.isEmpty()){
                    for(Daily_Report__c dr: dailyReportList){
                        if(mapSiteDailyReport.containsKey(dr.Site__c) && mapSiteDailyReport.get(dr.Site__c) != null){
                            mapSiteDailyReport.get(dr.Site__c).add(dr);
                        }
                        else{
                            mapSiteDailyReport.put(dr.Site__c, new List<Daily_Report__c> {dr});
                        }
                    }
                }
                
                for(Daily_Report__c dr: triggernew){
                
                    if(mapSiteDailyReport.containsKey(dr.Site__c) && mapSiteDailyReport.get(dr.Site__c) != null){
                        for(Daily_Report__c dr2: mapSiteDailyReport.get(dr.Site__c)){
                            if((dr.Contract__c == dr2.Contract__c) && (dr.Type__c == dr2.Type__c) && (dr.Unit__c == dr2.Unit__c) && ( (dr2.Report_Date__c < dr.Report_Date__c) || (dr2.Report_Date__c > dr.Report_Date__c))){
                                dr.addError('Daily Report cannot be created since a Daily Report '+dr2.Name+' of this type is open. Kindly, submit that report before creating a new one.');
                            }
                        }   
                    }
                }
            }
        }
        catch(Exception e){System.debug('At '+e.getLineNumber()+'. Cause: '+e.getCause()+'. ErrorMessage: '+e.getMessage());}
    }
}