force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contract</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Contract Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>In Approval Process</fullName>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory_Item__c/Inventory_Item__c.object-meta.xml
<CustomObject>
    <description>Label changed to Item Master from Inventory Item</description>
    <label>Item Master</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Item Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/Purchase_Request__c.object-meta.xml
<CustomObject>
    <label>Purchase Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>PR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/fields/Approval_Comments__c.field-meta.xml
<CustomField>
    <fullName>Approval_Comments__c</fullName>
    <label>Approval Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/New_Item_Name__c.field-meta.xml
<CustomField>
    <fullName>New_Item_Name__c</fullName>
    <label>New Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Purchase_Request_Approver__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Request_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Request Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Source_Store__c.field-meta.xml
<CustomField>
    <fullName>Source_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Source Store</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Purchase Requests - Source</relationshipLabel>
    <relationshipName>Purchase_Requests_Source</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Source_Store_Item__c.field-meta.xml
<CustomField>
    <fullName>Source_Store_Item__c</fullName>
    <label>Source Store Item</label>
    <referenceTo>Store_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests (Source Store Item)</relationshipLabel>
    <relationshipName>Purchase_Requests2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Staff_Name__c.field-meta.xml
<CustomField>
    <fullName>Staff_Name__c</fullName>
    <label>Staff Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Purchasing Review</fullName>
            </value>
            <value>
                <fullName>Approver Review</fullName>
            </value>
            <value>
                <fullName>For Approval - Review Complete</fullName>
            </value>
            <value>
                <fullName>For Item Review</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>For Ordering</fullName>
            </value>
            <value>
                <fullName>Pick List</fullName>
            </value>
            <value>
                <fullName>Packing List</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Approved - For Ordering</fullName>
                <isActive>false</isActive>
                <label>Approved - For Ordering</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Defective</fullName>
                <isActive>false</isActive>
                <label>Defective</label>
            </value>
            <value>
                <fullName>For Item Approval</fullName>
                <isActive>false</isActive>
                <label>For Item Approval</label>
            </value>
            <value>
                <fullName>For Pricing Approval</fullName>
                <isActive>false</isActive>
                <label>For Pricing Approval</label>
            </value>
            <value>
                <fullName>For Quoting</fullName>
                <isActive>false</isActive>
                <label>For Quoting</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Ready for Collection</fullName>
                <isActive>false</isActive>
                <label>Ready for Collection</label>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
                <isActive>false</isActive>
                <label>Sent to Supplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Item__c/Store_Item__c.object-meta.xml
<CustomObject>
    <description>Conjunction object for Item Master and Unit
Label changed to Inventory Item from Store Item</description>
    <label>Inventory Item</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Inventory Items are allowed</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Store_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Item__c/fields/Store_Unit__c.field-meta.xml
<CustomField>
    <fullName>Store_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store (Unit)</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Store_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract # (Old)</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Contract_New__c.field-meta.xml
<CustomField>
    <fullName>Contract_New__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract #</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/LTI_Reset_Date__c.field-meta.xml
<CustomField>
    <fullName>LTI_Reset_Date__c</fullName>
    <description>When the LTI field is changed back to zero the LTI Date will automatically reset to the day this happened</description>
    <label>LTI Reset Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Purchase_Request_Approver__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Request_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Request Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Purchase_Request_Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Source_Store__c.field-meta.xml
<CustomField>
    <fullName>Source_Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>If by pass ordering, specify the source store to pick list stocks.</inlineHelpText>
    <label>Source Store</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit (Source Store)</relationshipLabel>
    <relationshipName>Unit1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalApproveTest.cls
@isTest
public class ApprovalApproveTest {
    
    @isTest
    public static void testApproveRecord(){
        
        TestDataFactory testData = new TestDataFactory();
        
        Account acc = testData.createAccount();
        insert acc;
        
        Contract__c cont = testData.createContract();
        cont.Account__c = acc.Id;
        insert cont;
        
        Inventory_Item__c invobj = new Inventory_Item__c(Name ='Test Item',Active__c = True);
        insert invobj;
        
        Unit__c unitObj = testData.createRigUnit();
        unitObj.Contract_New__c = cont.Id;
        unitObj.LTI_Reset_Date__c = System.today() - 5;
        insert unitObj;        
        
        Store_Item__c storeItemobj = new Store_Item__c();
        storeItemobj.Inventory_Item__c = invobj.id;
        storeItemobj.Store_Unit__c=unitObj.id;
        insert storeItemobj;
        
        List<Purchase_Request__c> prList = new List<Purchase_Request__c>();
        for(Integer i =1;i<=5;i++){
            Purchase_Request__c pr = new Purchase_Request__c();
            pr.Approval_Comments__c = 'Test Approve' +i;
            pr.Status__c = 'For Approval';
            pr.New_Item_Name__c = 'Test Name' +i;
            pr.Item__c = invobj.Id;
            pr.Source_Store__c = unitObj.Id;
            pr.Source_Store_Item__c = storeItemobj.Id;
            pr.Staff_Name__c = 'Test Staff';
            pr.Quantity__c = 2;
            pr.Purchase_Request_Approver__c = UserInfo.getUserId();
            prList.add(pr);
        }
        
        insert prList;
        List<String> prRecordIdList = new List<String>(); 
        List<String> prRecordIdList2 = new List<String>();         
        prRecordIdList.add(prList[2].id);
        prRecordIdList2.add(prList[3].id);
        
        system.assert(prList[0].Id != Null);
        
        /*ProcessInstance objProcessInstance = new ProcessInstance();
objProcessInstance= [SELECT Id,TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :pr.Id];
System.assertEquals(pr.CreatedDate,objProcessInstance.CreatedDate);*/
        
        /* Approval.ProcessSubmitRequest Approvalreq = new Approval.ProcessSubmitRequest();
Approvalreq.setComments('Submitting request for approval for Purchase Request.');
Approvalreq.setNextApproverIds(new Id[] {UserInfo.getUserId()});
Approvalreq.setObjectId(pr.Id);
Approval.ProcessResult approvalResult = Approval.process(Approvalreq);
*/
        
        List<ApprovalApprove.InvocableInput> InvInputobjListApprove = new List<ApprovalApprove.InvocableInput>();
        
        ApprovalApprove.InvocableInput InvInputObj = new ApprovalApprove.InvocableInput();
        InvInputObj.recordId = prList[0].Id;
        InvInputObj.approvalComments = 'Please Approve Test 1';
        
        InvInputobjListApprove.add(InvInputObj);
        List<ApprovalApprove.InvocableOutput> InvAcceptOutput = ApprovalApprove.ApproveRecord(InvInputobjListApprove);
        if(! InvAcceptOutput.isEmpty()){
            System.assertEquals(True, InvAcceptOutput[0].success , 'Approval Approve process returned False, expected True') ;
        }
        
        List<ApprovalReject.InvocableInput> InvInputobjListReject = new List<ApprovalReject.InvocableInput>();
        
        ApprovalReject.InvocableInput InvInputObj1 = new ApprovalReject.InvocableInput();
        InvInputObj1.recordId = prList[1].Id;
        InvInputObj1.approvalComments = 'Please Approve Test 2';
        
        List<ApprovalReject.InvocableOutput> InvRejectOutput = ApprovalReject.RejectRecord(InvInputobjListReject);
        if(! InvRejectOutput.isEmpty()){
            System.assertEquals(True, InvRejectOutput[0].success , 'Approval Reject process returned False, expected True') ;
        }
        
        InvInputobjListReject.add(InvInputObj1);
        ApprovalReject.RejectRecord(InvInputobjListReject);
        
        ApprovalLock.LockRecord(prRecordIdList);
        List<Purchase_Request__c> lockResult = [SELECT Id, Status__c FROM Purchase_Request__c WHERE Id =: prRecordIdList];
        for(Purchase_Request__c eachLockResult : lockResult){
            System.assertEquals('For Approval', eachLockResult.Status__c, 'Approval Lock Failed');
        }
        
        prRecordIdList2.add(prList[3].id);
                             
        ApprovalUnlock.UnLockRecord(prRecordIdList2);
        List<Purchase_Request__c> unlockResult = [SELECT Id, Status__c FROM Purchase_Request__c WHERE Id =: prRecordIdList2];
        for(Purchase_Request__c eachLockResult : unlockResult){
            System.assertEquals('For Approval', eachLockResult.Status__c, 'Approval unlock Failed');
        }

        ApprovalApprove.coverageHack();
        ApprovalReject.coverageHack();
        ApprovalLock.coverageHack();
        ApprovalUnlock.coverageHack();
    }
}