force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Assigned_to_Unit__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/Mandatory_Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Mandatory Professional Development</label>
    <nameField>
        <label>Mandatory Professional Development Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mandatory Professional Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Mandatory Professional Developments</relationshipLabel>
    <relationshipName>Position</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Professional_Development__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professional Development</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Mandatory Professional Development (By Client/Position)</relationshipLabel>
    <relationshipName>Mandatory_Professional_Developments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/fields/Required_By__c.field-meta.xml
<CustomField>
    <fullName>Required_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who requires that this be completed</inlineHelpText>
    <label>Required By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Courses_Qualifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/fields/Requirement_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Type__c</fullName>
    <label>Requirement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>As per Matrix</fullName>
            </value>
            <value>
                <fullName>Mandatory By Position</fullName>
            </value>
            <value>
                <fullName>WSQ - Core</fullName>
            </value>
            <value>
                <fullName>WSQ - Elective</fullName>
            </value>
            <value>
                <fullName>Manager to Request</fullName>
            </value>
            <value>
                <fullName>Mandatory Client Induction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LinkPDToPositionAndAccountTest.cls
@isTest(seeAllData=true)
public class LinkPDToPositionAndAccountTest{
    public static List<Professional_Development__c> profDevList;
    public static List<Professional_Development__c> profDevListUpdated;
    public static account acc;
    public static account acc1;
    public database.saveresult lsr;
    public static database.saveresult[] lsrArray;
    public static List<Id> recordsIds;
    public static Id accountId;
    public static List<Position__c> listPosition;
    private static List<Professional_Development__c>  pdtList = new List<Professional_Development__c>();
    private static List<Position__c> positionList = new List<Position__c>();
    private static List<Mandatory_Professional_Development__c > devRecList = new List<Mandatory_Professional_Development__c>();
    
    
    private static List<Account> accountList = new List<Account>();
    private static List<Mandatory_Professional_Development__c> accDevRecList = new List<Mandatory_Professional_Development__c>();
    private static List<Site__c> siteList = new List<Site__c>();
    private static List<Unit__c> unitList = new List<Unit__c>();
    
    private static List<Employees__c> employeeList = new List<Employees__c>();
    public static database.saveResult[] employeeSaveResult;
    public static database.saveResult[] positionDevRecSaveResult;
    public static database.saveResult[] unitSaveResult;
    public static database.saveResult[] positionSaveResultList; 
    public static database.saveResult[] siteSaveResultList;
    public static void init(){
    pdtList.add(InilitizeTestData.createPersonalDevType('Test PrfessionalDevelopment1',10));
        pdtList.add(InilitizeTestData.createPersonalDevType('Test PrfessionalDevelopment2',20));
        
        database.saveResult[] profDevTypeSaveResultList = database.insert(pdtList);
        
        positionList.add(InilitizeTestData.createPosition('Test Position 1'));
        positionList.add(InilitizeTestData.createPosition('Test Position 2')); 
        
        positionSaveResultList = database.insert(positionList);
        System.debug('positionSaveResultList-----------:'+positionSaveResultList);
        
        devRecList.add(InilitizeTestData.createMandDevRecord(profDevTypeSaveResultList[0].getId(),'Test Mand Pos1',null,positionSaveResultList[0].getId()));
        devRecList.add(InilitizeTestData.createMandDevRecord(profDevTypeSaveResultList[1].getId(),'Test Mand Pos2',null,positionSaveResultList[1].getId()));
        
        positionDevRecSaveResult = database.insert(devRecList);
       
        accountList.add(InilitizeTestData.createAccount('Test Account1'));
        accountList.add(InilitizeTestData.createAccount('Test Account2'));
        
        database.saveResult[] accountSaveResultList = database.insert(accountList);
        

        
        siteList.add(InilitizeTestData.createSite('Test Site1',accountSaveResultList[0].getId()));
        siteList.add(InilitizeTestData.createSite('Test Site2',accountSaveResultList[1].getId()));
        
        //database.saveResult[] 
        siteSaveResultList = database.insert(siteList);
        
        unitList.add(InilitizeTestData.createUnit('Test Unit1',siteSaveResultList[0].getId()));
        unitList.add(InilitizeTestData.createUnit('Test Unit2',siteSaveResultList[1].getId()));
        
         unitSaveResult = database.insert(unitList);
        
 
        for(Integer i=0;i<=5;i++){
            employeeList.add(InilitizeTestData.createEmployee(positionSaveResultList[1].getId(),unitSaveResult[1].getId(),'Employee'+i));
        }
        
        
       employeeSaveResult = database.insert(employeeList); 
       
        profDevList = new List<Professional_Development__c>();
        listPosition = new List<Position__c>();
        for(Integer i=0;i<10;i++){
            listPosition.add(InilitizeTestData.createPosition('Test Position'+i));  
        }
        database.insert(listPosition);
        //acc = InilitizeTestData.createAccount('Test Account');
        //database.saveresult lsr =database.insert(acc);
        accountId =accountSaveResultList[0].getId(); 
        for(Integer i=0;i<10;i++){
            profDevList.add(InilitizeTestData.createProfDevRecord('Test Prof Dev'+i,null));    
        }  
        lsrArray =database.insert(profDevList);
       
    }
    
    public static testmethod void myUnitTest1(){
        init(); 
        acc1 = InilitizeTestData.createAccount('Test Account1');
        database.saveresult la = database.insert(acc1);
        //system.assertEquals(lsrArray,null);
        recordsIds = new List<Id>();
        for(database.saveresult d:lsrArray){
            recordsIds.add(d.getId());
        }
        profDevListUpdated = new List<Professional_Development__c>();
        for(Professional_Development__c pd:[select id,Required_By__c from Professional_Development__c where id in:recordsIds]){
            pd.Required_By__c =null;
            pd.Requirement_Type__c = null;
            profDevListUpdated.add(pd);
        }
        database.update(profDevListUpdated);
        profDevListUpdated.clear();
        for(Professional_Development__c pd:[select id,Required_By__c from Professional_Development__c where id in:recordsIds]){
            pd.Requirement_Type__c ='Compulsory - All';
            profDevListUpdated.add(pd); 
        }
        database.update(profDevListUpdated);
      
       
    }
    public static testmethod void myUnitTest2(){
        List<Employees__c> empList = new List<Employees__c>();
       // Position__c position = InilitizeTestData.createPosition('Test Position 2');
        //database.insert(position);
        positionList.add(InilitizeTestData.createPosition('Test Position 1'));
        positionList.add(InilitizeTestData.createPosition('Test Position 2')); 
        
        positionSaveResultList = database.insert(positionList);
        System.debug('positionSaveResultList-----------:'+positionSaveResultList);
                accountList.add(InilitizeTestData.createAccount('Test Account1'));
        accountList.add(InilitizeTestData.createAccount('Test Account2'));
        
        database.saveResult[] accountSaveResultList = database.insert(accountList);
        
        /*accDevRecList.add(InilitizeTestData.createMandDevRecord(profDevTypeSaveResultList[0].getId(),'Test Mand Acc1',accountSaveResultList[0].getId(),null));
        accDevRecList.add(InilitizeTestData.createMandDevRecord(profDevTypeSaveResultList[1].getId(),'Test Mand Acc 2',accountSaveResultList[1].getId(),null));
        
        database.saveResult[] acctDevResultList = database.insert(accDevRecList); */
        
        siteList.add(InilitizeTestData.createSite('Test Site1',accountSaveResultList[0].getId()));
        siteList.add(InilitizeTestData.createSite('Test Site2',accountSaveResultList[1].getId()));
        
        //database.saveResult[] 
        siteSaveResultList = database.insert(siteList);
        
        unitList.add(InilitizeTestData.createUnit('Test Unit1',siteSaveResultList[0].getId()));
        unitList.add(InilitizeTestData.createUnit('Test Unit2',siteSaveResultList[1].getId()));
        
         unitSaveResult = database.insert(unitList);
        for(Integer i=0;i<5;i++){
           // empList.add(InilitizeTestData.createEmployeeForNewTest(position.id,'testEmp'+i));    
       // }
            Employees__c emp= new Employees__c();
            emp.PositionLookup__c = positionSaveResultList[0].getId();
            emp.Assigned_to_Unit__c  = unitSaveResult[0].getId(); 
            emp.First_Name__c='first name';
            emp.Last_Name__c='last name';    
            System.debug('---------------------list to check'+emp);
            empList.add(emp);
          }  
        System.debug('---------------------list to before check'+empList);
        database.insert(empList);
        System.debug('---------------------list to after check'+empList );
        
        PageReference pageRef = Page.deleteWarningPage;
        pageRef.getParameters().put('id',positionSaveResultList[0].id);
        Test.setCurrentPage(pageRef);    
         
        posController pos = new posController();
        system.assertNotEquals(pos.deletePosition(),null);
        system.assertNotEquals(pos.cancelPosition(),null);
        //system.assertEquals(pos.autoDelete(),null);
        
    }
    

}