force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/positionExtension.cls
public class positionExtension {

    public positionExtension() {

    }


    public positionExtension(ApexPages.StandardController controller) {

    }
    @remoteaction
    public static string getEmployees(Id positionId){
    
        List<Employees__c> employeesUnderPosition     ;
        employeesUnderPosition = new List<Employees__c>([select id ,name from Employees__c where PositionLookup__c=:positionId]); 
        if(employeesUnderPosition.size()>0){
            return 'success';
        }else{
            return null;
        }
    
    }

}