force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Orders__c/Job_Orders__c.object-meta.xml
<CustomObject>
    <label>WD Sales Orders</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>WD S0 #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WD Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Orders__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Transport_Job_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Provide a brief description of the type of job, hire items, additional services, agreed contract items, etc....</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/Fuel_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Fuel_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel On Hand</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/Fuel_Used__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Used</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/Job_Date__c.field-meta.xml
<CustomField>
    <fullName>Job_Date__c</fullName>
    <description>Date Job was started</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/Job_Status__c.field-meta.xml
<CustomField>
    <fullName>Job_Status__c</fullName>
    <inlineHelpText>Open - Record has been created as job is booked/started
Job Complete - TD received and uploaded to record.
Invoiced - Invoice has been created and sent to client</inlineHelpText>
    <label>Job Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Job Complete</fullName>
                <color>#33CC00</color>
                <label>Job Complete</label>
            </value>
            <value>
                <fullName>Approval Required</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>WD Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/To_Be_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>To_Be_Invoiced__c</fullName>
    <label>To Be Invoiced</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End of Month</fullName>
            </value>
            <value>
                <fullName>Invoice with WD Unit</fullName>
            </value>
            <value>
                <fullName>No Charge</fullName>
            </value>
            <value>
                <fullName>On Job Completion</fullName>
            </value>
            <value>
                <fullName>Fortnightly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Orders__c/fields/WD_Unit__c.field-meta.xml
<CustomField>
    <fullName>WD_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>only applies to movement of WD UNITS</inlineHelpText>
    <label>WD Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Transport_Job_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Services_Received__c/Services_Received__c.object-meta.xml
<CustomObject>
    <label>Services Received Items</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services Received Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Services_Received__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Hire_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/ServicesReceived__c.object-meta.xml
<CustomObject>
    <label>Services Received</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Services Received</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Received</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Services Received</relationshipLabel>
    <relationshipName>Services_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>/*Site__r.Account__r.Name*/
 Contract_New__r.Account__r.Name</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fuel_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Delivered__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Delivered</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fuel_On_Hand__c.field-meta.xml
<CustomField>
    <fullName>Fuel_On_Hand__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel On Hand</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Fuel_Used__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Used</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/WD_Personnel__c.object-meta.xml
<CustomObject>
    <label>WD Personnel</label>
    <nameField>
        <displayFormat>WDP-{00000}</displayFormat>
        <label>WDP#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WD Personnel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Personnel__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipName>WD_Personnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/recordTypes/Personnel.recordType-meta.xml
<RecordType>
    <fullName>Personnel</fullName>
    <active>true</active>
    <label>Personnel</label>
</RecordType>

force-app/main/default/objects/WD_Report__c/WD_Report__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <displayFormat>JO-{00000}</displayFormat>
        <label>JO #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Report__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Job Orders</relationshipLabel>
    <relationshipName>Rig_Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Any relevant information can be entered to make tracking of invoicing more simple eg.. quote or lump sum, subcontractor name and cost??</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Fuel_Delivered__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Delivered__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Fuel Delivered</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Rig_Daily_Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/sked_WDR_Test2.cls
@isTest(SeeAllData=true)
    public class sked_WDR_Test2 {
         
         static Account Client;
         static Job_Orders__c Job;
         static WD_Report__c WDR;
         static WD_Personnel__c Personnel;
         static ServicesReceived__c ServiceReceived1;
         static ServicesReceived__c ServiceReceived2;
         static ServicesReceived__c ServiceReceived3;
         static ServicesReceived__c ServiceReceived4;
         static ServicesReceived__c ServiceReceived5;
         static ServicesReceived__c ServiceReceived6;
         static ServicesReceived__c ServiceReceived7;
         static ServicesReceived__c ServiceReceived8;
         static Unit__c WDUNit;
         static Site__c Site;
         static Services_Received__c Item;
         static Position__c Position;
         static Employees__c Employee;
         
         static testMethod void TestWDTriggers() {  

            Schema.DescribeSObjectResult accSchema = Schema.SObjectType.Account; 
            Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = accSchema.getRecordTypeInfosByName(); 
            Id acc_rtId = AccountRecordTypeInfo.get('Client').getRecordTypeId();
    
            Client = new Account();
            Client.Name = 'John Doe';
            Client.RecordTypeId = acc_rtId;
            
            //Client
            insert Client;
            
            Site = new Site__c();
            Site.Name = 'Site Test';
            Site.Account__c = Client.Id;
            
            //Site
            insert Site;
            
            WDUNit = new Unit__c();
            WDUNit.Name = 'WD Unit Test';
            WDUNit.Site__c = Site.Id;
            WDUNit.Fuel_On_Hand__c = 50;
            WDUNit.Fuel_Delivered__c = 100;
            WDUNit.Fuel_Used__c = 10;
            
            //WD Unit
            insert WDUNit;
   
            Job = new Job_Orders__c();
            Job.Client__c = Client.Id;
            Job.Description__c = 'Job Test';
            Job.Job_Date__c = System.Today();
            Job.To_Be_Invoiced__c = 'On Job Completion';
            Job.Job_Status__c = 'Open';
            Job.WD_Unit__c = WDUNit.Id;
            Job.Site_ID__c = Site.Id;
            
            
            //Job
            insert Job;
            
            Schema.DescribeSObjectResult wdrSchema = Schema.SObjectType.WD_Report__c; 
            Map<String,Schema.RecordTypeInfo> WDRRecordTypeInfo = wdrSchema.getRecordTypeInfosByName(); 
            Id wdr_rtId = WDRRecordTypeInfo.get('12 Hour Rig').getRecordTypeId();
            
            WDR = new WD_Report__c();
            WDR.RecordTypeId = wdr_rtId;
                WDR.Sales_Order__c = Job.Id;
            WDR.Approved_By__c = UserInfo.getUserId();
            WDR.WD_Unit__c = WDUNit.Id;
            
            //WDR
            insert WDR;
         
            Test.startTest();  

            WD_Report__c report = [Select Fuel_Delivered__c, Fuel_Used__c From WD_Report__c Where Id = :WDR.Id];
            
            report.Fuel_Delivered__c = 200;
            report.Fuel_Used__c = 70;
            
            update report;          
                
            Test.stopTest();    
        }
        
        static testMethod void TestPageBaseClass() {
            
            Schema.DescribeSObjectResult accSchema = Schema.SObjectType.Account; 
            Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = accSchema.getRecordTypeInfosByName(); 
            Id acc_rtId = AccountRecordTypeInfo.get('Client').getRecordTypeId();
    
            Client = new Account();
            Client.Name = 'John Doe';
            Client.RecordTypeId = acc_rtId;
            
            //Client
            insert Client;
            
            Site = new Site__c();
            Site.Name = 'Site Test';
            Site.Account__c = Client.Id;
            
            //Site
            insert Site;
            
            WDUNit = new Unit__c();
            WDUNit.Name = 'WD Unit Test';
            WDUNit.Site__c = Site.Id;
            WDUNit.Fuel_On_Hand__c = 50;
            WDUNit.Fuel_Delivered__c = 100;
            WDUNit.Fuel_Used__c = 10;
            
            //WD Unit
            insert WDUNit;
   
            Job = new Job_Orders__c();
            Job.Client__c = Client.Id;
            Job.Description__c = 'Job Test';
            Job.Job_Date__c = System.Today();
            Job.To_Be_Invoiced__c = 'On Job Completion';
            Job.Job_Status__c = 'Open';
            Job.WD_Unit__c = WDUNit.Id;
            Job.Site_ID__c = Site.Id;
            
            
            //Job
            insert Job;
            
            Schema.DescribeSObjectResult wdrSchema = Schema.SObjectType.WD_Report__c; 
            Map<String,Schema.RecordTypeInfo> WDRRecordTypeInfo = wdrSchema.getRecordTypeInfosByName(); 
            Id wdr_rtId = WDRRecordTypeInfo.get('12 Hour Rig').getRecordTypeId();
            
            WDR = new WD_Report__c();
            WDR.RecordTypeId = wdr_rtId;
              WDR.Sales_Order__c = Job.Id;
            WDR.Approved_By__c = UserInfo.getUserId();
            
            //WDR.Name = 'WDR Test';
            
            //WDR
            insert WDR;
            
            Test.startTest();
            
            Test.setCurrentPage(new PageReference('apex/WDRpage?WDReportId='+WDR.Id));
            skedWDPageController pageCtrl2 = new skedWDPageController();            
            
            skedWDPersonnel componentPersonnel = new skedWDPersonnel ();
            skedWDServicesReceive componentServiceReceived = new skedWDServicesReceive ();
                    
            
            pageCtrl2.myComponent1Controller = componentPersonnel;
            pageCtrl2.myComponent3Controller = componentServiceReceived;
            
            pageCtrl2.myComponent1Controller.key = 'component1';
            pageCtrl2.myComponent1Controller.pageController = pageCtrl2;
            
            pageCtrl2.myComponent3Controller.key = 'component3';
            pageCtrl2.myComponent3Controller.pageController = pageCtrl2;
            
            skedComponentControllerBase skcBase = pageCtrl2.getMyComponentController();
            
            Test.stopTest(); 
            
            
        }
        
        static testMethod void TestWDExtension() {  
        
                    Schema.DescribeSObjectResult accSchema = Schema.SObjectType.Account; 
            Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = accSchema.getRecordTypeInfosByName(); 
            Id acc_rtId = AccountRecordTypeInfo.get('Client').getRecordTypeId();
    
            Client = new Account();
            Client.Name = 'John Doe';
            Client.RecordTypeId = acc_rtId;
            
            //Client
            insert Client;
            
            Site = new Site__c();
            Site.Name = 'Site Test';
            Site.Account__c = Client.Id;
            
            //Site
            insert Site;
            
            WDUNit = new Unit__c();
            WDUNit.Name = 'WD Unit Test';
            WDUNit.Site__c = Site.Id;
            WDUNit.Fuel_On_Hand__c = 50;
            WDUNit.Fuel_Delivered__c = 100;
            WDUNit.Fuel_Used__c = 10;
            
            //WD Unit
            insert WDUNit;
   
            Job = new Job_Orders__c();
            Job.Client__c = Client.Id;
            Job.Description__c = 'Job Test';
            Job.Job_Date__c = System.Today();
            Job.To_Be_Invoiced__c = 'On Job Completion';
            Job.Job_Status__c = 'Open';
            Job.WD_Unit__c = WDUNit.Id;
            Job.Site_ID__c = Site.Id;
            
            
            //Job
            insert Job;
            
            Schema.DescribeSObjectResult wdrSchema = Schema.SObjectType.WD_Report__c; 
            Map<String,Schema.RecordTypeInfo> WDRRecordTypeInfo = wdrSchema.getRecordTypeInfosByName(); 
            Id wdr_rtId = WDRRecordTypeInfo.get('12 Hour Rig').getRecordTypeId();
            
            WDR = new WD_Report__c();
            WDR.RecordTypeId = wdr_rtId;
          WDR.Sales_Order__c = Job.Id;
            WDR.Approved_By__c = UserInfo.getUserId();
            
            //WDR
            insert WDR;
        
        Test.startTest(); 
                
        Test.setCurrentPageReference(new PageReference('/'+Job.Id));
                
        ApexPages.StandardController sc = new ApexPages.standardController(Job);
        skedWDRextension skedExt = new skedWDRextension(sc);
        skedExt.selectedRecordType = '12 Hour Rig';
        skedExt.showWDRPage();

        
        Test.stopTest(); 
        
        }
        
        static testMethod void TestRExtension() {  
        
            Schema.DescribeSObjectResult accSchema = Schema.SObjectType.Account; 
            Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = accSchema.getRecordTypeInfosByName(); 
            Id acc_rtId = AccountRecordTypeInfo.get('Client').getRecordTypeId();
    
            Client = new Account();
            Client.Name = 'John Doe';
            Client.RecordTypeId = acc_rtId;
            
            //Client
            insert Client;
            
            Site = new Site__c();
            Site.Name = 'Site Test';
            Site.Account__c = Client.Id;
            
            //Site
            insert Site;
            
            WDUNit = new Unit__c();
            WDUNit.Name = 'WD Unit Test';
            WDUNit.Site__c = Site.Id;
            WDUNit.Fuel_On_Hand__c = 50;
            WDUNit.Fuel_Delivered__c = 100;
            WDUNit.Fuel_Used__c = 10;
            
            //WD Unit
            insert WDUNit;
   
            Job = new Job_Orders__c();
            Job.Client__c = Client.Id;
            Job.Description__c = 'Job Test';
            Job.Job_Date__c = System.Today();
            Job.To_Be_Invoiced__c = 'On Job Completion';
            Job.Job_Status__c = 'Open';
            Job.WD_Unit__c = WDUNit.Id;
            Job.Site_ID__c = Site.Id;
            
            
            //Job
            insert Job;
            
            Schema.DescribeSObjectResult wdrSchema = Schema.SObjectType.WD_Report__c; 
            Map<String,Schema.RecordTypeInfo> WDRRecordTypeInfo = wdrSchema.getRecordTypeInfosByName(); 
            Id wdr_rtId = WDRRecordTypeInfo.get('12 Hour Rig').getRecordTypeId();
            
            WDR = new WD_Report__c();
            WDR.RecordTypeId = wdr_rtId;
          WDR.Sales_Order__c = Job.Id;
            WDR.Approved_By__c = UserInfo.getUserId();
            
            //WDR
            insert WDR;
        
        ApexPages.StandardController sc = new ApexPages.StandardController(WDR);
        skedRelatedSRExtension skeExt = new skedRelatedSRExtension(sc);
        
        }
        
        
         
         
}