force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/posController.cls
//THIS CLASS IS WRITTEN TO HANDLE THE POSITION POSITION DELETION WARNING EVENTS
public class posController {
    //PROPERTIES USED IN THECONTROLLER
    public List<Employees__c> employeesUnderPosition{get;set;}
    public boolean showEmployees{get;set;}
    public pagereference refreshPage{get;set;}
    public posController (){}
    //PUBLIC METHOD TO DELETE THE POSITION ONCE CONFIRMED
    public pagereference deletePosition(){
        position__c pos =[select id from position__c  where id=:ApexPages.currentPage().getParameters().get('id')];
        delete pos;
        pagereference  page = new  pagereference('/');
        return page ;
    }
    //PUBLIC METHOD TO REDIRECT USER TO DETAIL PAGE ON CANCAL ACTION
    public pagereference cancelPosition(){
        pagereference  page = new  pagereference('/'+ApexPages.currentPage().getParameters().get('id'));
        
        return page;
    }
    //AUTO-DELETE THE POSITION if NO EMPLOYEES ARE ASSOCIATED WITH POSITION
    public pagereference autoDelete(){
        employeesUnderPosition = new List<Employees__c>([select id ,name from Employees__c where PositionLookup__c = :ApexPages.currentPage().getParameters().get('id')]);
        if(employeesUnderPosition.size()>0){
            showEmployees = true;
            return null;
        }
        else{
            position__c pos =[select id from position__c  where id=:ApexPages.currentPage().getParameters().get('id')];
            delete pos;
            pagereference  page = new  pagereference('/');
            return page ;
        }
    }
    
    
    
}