force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Personnel__c/WD_Personnel__c.object-meta.xml
<CustomObject>
    <label>WD Personnel</label>
    <nameField>
        <displayFormat>WDP-{00000}</displayFormat>
        <label>WDP#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WD Personnel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Personnel__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/DR__c.field-meta.xml
<CustomField>
    <fullName>DR__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>DR #</label>
    <referenceTo>WD_Report__c</referenceTo>
    <relationshipLabel>WD Personnel</relationshipLabel>
    <relationshipName>WD_Personnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Name</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipName>WD_Personnel4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/Pay_Ending__c.field-meta.xml
<CustomField>
    <fullName>Pay_Ending__c</fullName>
    <label>Pay Ending</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>03/03/2015</fullName>
            </value>
            <value>
                <fullName>17/03/2015</fullName>
            </value>
            <value>
                <fullName>31/03/2015</fullName>
            </value>
            <value>
                <fullName>14/04/2015</fullName>
            </value>
            <value>
                <fullName>28/04/2015</fullName>
            </value>
            <value>
                <fullName>12/05/2015</fullName>
            </value>
            <value>
                <fullName>26/05/2015</fullName>
            </value>
            <value>
                <fullName>09/06/15</fullName>
            </value>
            <value>
                <fullName>23/06/2015</fullName>
            </value>
            <value>
                <fullName>7/07/2015</fullName>
            </value>
            <value>
                <fullName>21/07/2015</fullName>
            </value>
            <value>
                <fullName>4/08/2015</fullName>
            </value>
            <value>
                <fullName>18/08/2015</fullName>
            </value>
            <value>
                <fullName>1/09/2015</fullName>
            </value>
            <value>
                <fullName>15/09/2015</fullName>
            </value>
            <value>
                <fullName>29/09/2015</fullName>
            </value>
            <value>
                <fullName>13/10/2015</fullName>
            </value>
            <value>
                <fullName>27/10/2015</fullName>
            </value>
            <value>
                <fullName>10/11/2015</fullName>
            </value>
            <value>
                <fullName>24/11/2015</fullName>
            </value>
            <value>
                <fullName>8/12/2015</fullName>
            </value>
            <value>
                <fullName>22/12/2015</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipName>WD_Personnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <inlineHelpText>This is the total Work Hrs over a 24hr DAY Period as per Work Diary (not a 24hr WORK Period.)  This does not effect payroll or man hour stats.</inlineHelpText>
    <label>Total Work Hrs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/fields/WD_Unit__c.field-meta.xml
<CustomField>
    <fullName>WD_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WD Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>WD_Personnel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WD_Personnel__c/recordTypes/Personnel.recordType-meta.xml
<RecordType>
    <fullName>Personnel</fullName>
    <active>true</active>
    <label>Personnel</label>
</RecordType>

force-app/main/default/classes/skedWDPersonnel.cls
public with sharing class skedWDPersonnel extends skedComponentControllerBase {

    //Use in table rows. 
    public Integer rowNumber{ get; set; }
    public Integer numberOfRowToRemove { get; set; }
    public Integer numberOfRowToEdit { get; set; }
    
    //Required fields error 
    public boolean showError {get; set;}   
    
    //Use in modal pop-up
    public boolean displayPopup {get; set;}   
    
    public boolean isEdit {get{ if (isEdit == null) isEdit = false; return isEdit;} set;}    
    
    public void closePopup() {        
        displayPopup = false;    
    }     
    public void showPopup() {      
        if (isEdit == null) {isEdit = false;}
        System.debug('**before '+displayPopup);
        showError = false;
        displayPopup = true;    
        System.debug('**after '+displayPopup);
    }

    //WD Report Id from the page
    public ID WDReportId {
          get;
          set {
              if (value != null) {
                WDReportId  = value;}
              }
     }
     
   //Pay Ending from the WDR page
    public string PayEndingDate {
          get;
          set {
              if (value != null) {
                PayEndingDate = value;}
              }
     }
   
    //WD Unit from the page
    public ID WDUnit {
          get;
          set {
              if (value != null) {
                WDUnit = value;}
              }
    }
   
   //Place holder of the inputs from the pop-up
   public WD_Personnel__c NewPersonnel {
    get{ 
       if (NewPersonnel == null){
              NewPersonnel = new WD_Personnel__c();      
              NewPersonnel.Date_Created__c = System.Today();
                isEdit = false;
          }      
                return NewPersonnel ;
    }  
    set;}
  
    //Table Data
    public List<WD_Personnel__c> WDPList {get; set;}
    
   //Method for saving the list of WD Personnel
    public void SaveWDPersonnel() {
                
  
      if (WDPList == null){
          WDPList = new List<WD_Personnel__c>();         
      }
  
      for(WD_Personnel__c p : WDPList){
            p.DR__c = WDReportId;
            p.WD_Unit__c = WDUnit;
            p.Pay_Ending__c = PayEndingDate;
      }
            
      if (WDPList.size() > 0)
          upsert WDPList;
      
      if (deleteList.size() > 0)
          delete deleteList;
    }
  
   // The method to remove an item from the list
    public PageReference removeNewObject(){
        WDPList.remove(numberOfRowToRemove);  
        return null;
    }
    
     // The method to edit an item from the list
    public PageReference editNewObject(){
        if (WDPList.size() > 0){
            isEdit = true;
            System.debug('***WDPList '+WDPList);
            this.NewPersonnel = WDPList.get(numberOfRowToEdit);  
            showPopup();
        }
        
        return null;
    }
    
    private List<WD_Personnel__c> deleteList = new List<WD_Personnel__c>();
    
// The method to peremanently delete an item from the database
    public PageReference deleteNewObject(){
        if (WDPList.size() > 0){
            WD_Personnel__c personDelete = WDPList.get(numberOfRowToRemove);
            deleteList.add(personDelete);
            WDPList.remove(numberOfRowToRemove);  
        }
        return null;
    }
  
  
  
  public void AddWDP(){
  
      if (WDPList == null){
          WDPList = new List<WD_Personnel__c>();         
      }
      try{
      System.debug('**this.NewPersonnel.Position__c '+retrievePositionId(this.NewPersonnel.Name__c));
          if (this.NewPersonnel.Name__c != null && this.NewPersonnel.Total_Hours__c != null){
              this.NewPersonnel.Position__c = retrievePositionId(this.NewPersonnel.Name__c);
              
              if (isEdit){
                  if (WDPList != null)
                    WDPList.remove(numberOfRowToEdit); 
                  }
              
              WDPList.add(this.NewPersonnel);
              this.NewPersonnel = new WD_Personnel__c();
              displayPopup = false;    
              isEdit = false;
          }
            else      {
                throw new skedCustomException ('WD Personnel fields required.');
                
            }
      }catch(Exception e){showError = true;}
      
      System.debug('**showError '+ showError);
  }
  
    public Id retrievePositionId(Id EmployeeId){
     System.debug('component class eid '+EmployeeId);
    Employees__c emp = [Select PositionLookup__c From Employees__c Where Id = :EmployeeId];
    System.debug('component class return '+emp.PositionLookup__c);
    return emp.PositionLookup__c;
    
    }
    
    
    
}