force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DisplayWarningMessage.cls
//CLASS CREATED TO BE EXECUTE DELETE FROM BUTTON JAVASCRIPT
global class DisplayWarningMessage{
    //METHOD TO GET ALL EMPLOYEES NAME UNDER THIS POSITION
    webservice static string getEmployees(Id positionId){
        
        List<Employees__c> employeesUnderPosition     ;
        employeesUnderPosition = new List<Employees__c>([select id ,name from Employees__c where PositionLookup__c=:positionId]); 
        if(employeesUnderPosition.size()>0){
        	return 'success';
        }
        else{
        	return null;
        }
    }
    //METHOD TO DELETE POSITION
    webservice static void deletePosition(Id positionId){
        Position__c toBeDeletePosition =[select id from Position__c where id=:positionId];
        delete toBeDeletePosition;
    }
    
}