force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Assigned_to_Unit__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/On_Shift__c.field-meta.xml
<CustomField>
    <fullName>On_Shift__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Shift</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Employment</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Manager__c.field-meta.xml
<CustomField>
    <fullName>Unit_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Unit Manager also controls Transport Jobs Mgmt.</inlineHelpText>
    <label>Unit Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UnitShortcutController.cls
public with sharing class UnitShortcutController {
	@AuraEnabled
    public static Id getUnitId(){
        List<Unit__c> unitManagedList = [select Id from Unit__c where Unit_Manager__c = :UserInfo.getUserId() limit 1];
        return (unitManagedList.size() > 0) ? unitManagedList[0].Id : null;
    }
    
    @AuraEnabled
    public static String getUnitName(){
        List<Unit__c> unitManagedList = [select Id, Name from Unit__c where Unit_Manager__c = :UserInfo.getUserId() limit 1];
        return (unitManagedList.size() > 0) ? unitManagedList[0].Name : null;
    }
    
    @AuraEnabled
    public static String getActiveOnshiftEmployees(){
        List<Unit__c> unitManagedList = [select Id, Name, (select Id from Employees__r where Status__c ='Active' and On_Shift__c = true) 
                                         from Unit__c where Unit_Manager__c = :UserInfo.getUserId() limit 1];
        return (unitManagedList.size() > 0) ? String.valueOf(unitManagedList[0].Employees__r.size()) : '0';
        
    }
}