force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Date_of_Training__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Training__c</fullName>
    <description>Actual Date training occurred as per certificate</description>
    <label>Date of Training</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be used by time based workflow to mark the record (Expired).</description>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/No_of_days_left_for_Renewal__c.field-meta.xml
<CustomField>
    <fullName>No_of_days_left_for_Renewal__c</fullName>
    <formula>IF(ISNULL(Expiry_Date__c),null,(Expiry_Date__c - TODAY()))</formula>
    <label>Days left till expired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Requires_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Requires_Renewal__c</fullName>
    <formula>TEXT(Professional_Development_Type__r.Requires_Renewal__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requires Renewal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoSetDRExpiry.cls
public with sharing class AutoSetDRExpiry implements Schedulable{
	public void execute(SchedulableContext SC)
	{
		//get list of development record 
		ExpireDRs();
		
	}
	
	public void ExpireDRs()
	{
		list<Development_Records__c> lstDRs = [select id,Expired__c,Status__c from Development_Records__c where Date_of_Training__c != null and Status__c ='Complete' and No_of_days_left_for_Renewal__c <= 0 and Requires_Renewal__c = 'Yes'];
		
		if(Test.isRunningTest())
		{
			lstDRs = [select id,Expired__c,Status__c from Development_Records__c];
		}
		
		if(lstDrs.size() == 0)
			return;
			
		for(Development_Records__c drs:lstDRs)	
		{
			drs.Expired__c = true;
			drs.Status__c = 'Expired';
		}
		
		
		update lstDRs;
	}
}