force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Professional_Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Development Type</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Development_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Requirement_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Type__c</fullName>
    <formula>TEXT( Professional_Development_Type__r.Requirement_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requirement Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/fields/Requirement_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Type__c</fullName>
    <label>Requirement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>As per Matrix</fullName>
            </value>
            <value>
                <fullName>Mandatory By Position</fullName>
            </value>
            <value>
                <fullName>WSQ - Core</fullName>
            </value>
            <value>
                <fullName>WSQ - Elective</fullName>
            </value>
            <value>
                <fullName>Manager to Request</fullName>
            </value>
            <value>
                <fullName>Mandatory Client Induction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoSetDRExpiryTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class AutoSetDRExpiryTest {

    static testMethod void myUnitTest() {
        Professional_Development__c  pdt = new Professional_Development__c ();
        pdt.Name ='Test';

        pdt.Requirement_Type__c ='Compulsory - All';
        
		insert pdt;
    	
        Development_Records__c  newDev = new Development_Records__c();
        newDev.Professional_Development_Type__c = pdt.id;
        newDev.Status__c ='Incomplete';
        insert newDev;
        
        AutoSetDRExpiry asd = new AutoSetDRExpiry();
        asd.ExpireDRs();
    }
}