force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Training_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <formula>IF( Requires_Renewal__c = &quot;No&quot;, null, 
IF( Expiry_Date_Override__c &lt;&gt; Date_of_Training__c, Expiry_Date_Override__c,
IF( AND(Renewal_Period_Days__c  &gt; -1, ISBLANK(Expiry_Date_Override__c)), (Date_of_Training__c  +  Renewal_Period_Days__c),
null )))</formula>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Expiry_Reminder_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Reminder_Date__c</fullName>
    <formula>Expiry_Date__c  -  Number_of_days_for_Reminder_Alert__c</formula>
    <label>Expiry Reminder Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Professional_Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Development Type</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Development_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Employment</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/recordTypes/Training.recordType-meta.xml
<RecordType>
    <fullName>Training</fullName>
    <active>true</active>
    <label>Training</label>
</RecordType>

force-app/main/default/classes/DevRecordReminder.cls
global class DevRecordReminder implements Schedulable {
    global void execute(SchedulableContext sc) {
    	sendMail();
    }
    
    private void sendMail(){
    	Messaging.SingleEmailMessage[] mails = new Messaging.SingleEmailMessage[]{};
        User touser = [ SELECT Id, Name, Email FROM User WHERE UserRole.Name = 'HR Manager' LIMIT 1 ];
        EmailTemplate template = [ SELECT Id, HtmlValue, Body, Subject
                                   FROM EmailTemplate WHERE DeveloperName = 'New_PD_Reminder' LIMIT 1 ];
        Pattern p = Pattern.compile('\\{![A-Za-z_.]+\\}');

        for ( Development_Records__c dev :
                [ SELECT Id, Expiry_Reminder_Date__c, Owner.Email, Professional_Development_Type__r.Name,
                         Employee__r.Name, Expiry_Date__c
                  FROM Development_Records__c where employee__r.Status__c = 'Active'] ) {

            if ( dev.Expiry_Reminder_Date__c == Date.today() || Test.isRunningTest() ){
            	Map<String, String> newTemplate = merge_template( buildMap(dev), template, p );
	            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
	            mail.setPlainTextBody( newTemplate.get('Body') );
	            mail.setSubject( newTemplate.get('Subject') );
	            mail.setToAddresses( new String[]{'training@wilddesert.com.au', 'dhamon@skedulo.com'} );
	            mail.setReplyTo( touser.Email );
	            mail.setSenderDisplayName( touser.Name );  
	            mails.add(mail);
            }
            if ( Test.isRunningTest() ) break;
        }
            
        Messaging.sendEmail(mails);
    }
    
    private Map<String, String> buildMap( Development_Records__c dev ){
    	Map<String, String> strMap = new Map<String, String>();
    	strMap.put('{!Development_Records__c.Professional_Development_Type__c}', dev.Professional_Development_Type__r.Name);
    	strMap.put('{!Development_Records__c.Employee__c}', dev.Employee__r.Name);
    	strMap.put('{!Development_Records__c.Expiry_Date__c}',
    	       dev.Expiry_Date__c == null ? '' : dev.Expiry_Date__c.format());
    	String link = 'https://login.salesforce.com/' + dev.Id;
    	strMap.put('{!Development_Records__c.Link}', link);
    	return strMap;
    }
    
    public static Map<String,String> merge_template(Map<String,String> obj, EmailTemplate email, Pattern p){
	    Map<String,String> data = new Map<String,String>();
	    String html = email.Body;
	    if(html!=null){
	        html = m(html,obj,p.matcher(html));
	        data.put('Body',html);
	    }
	    else{
	        data.put('Body','');
	    }
	    String subject = email.Subject;
	    subject = m(subject,obj,p.matcher(subject));
	
	    data.put('Subject',subject);
	
	    return data;
	}
	
	private static String m(String body,Map<String,String> obj,Matcher m){
	    while(m.find()){
	      String merge_field = m.group();
	      String value;
	      try{
	        value = (String) obj.get(merge_field);
	      }
	     catch(Exception e){
	        value='';
	     }
	     if(value!=null){
	        body = body.replace(merge_field,value);
	     }
	     else{
	        body = body.replace(merge_field,'');
	     }
	    }
	    return body;
	}
    
    public void testSendMail(){
    	sendMail();
    }
}