force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Training_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>TEXT(Employee__r.Position__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Professional_Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Development Type</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Development_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Employment</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/Mandatory_Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Mandatory Professional Development</label>
    <nameField>
        <label>Mandatory Professional Development Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mandatory Professional Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Mandatory Professional Developments</relationshipLabel>
    <relationshipName>Position</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Professional_Development__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professional Development</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Mandatory Professional Development (By Client/Position)</relationshipLabel>
    <relationshipName>Mandatory_Professional_Developments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CleanDRBatch.cls
global class CleanDRBatch implements Database.Batchable<SObject>, database.stateful {
	string query = 'Select id,Status__c, Professional_Development_Type__c, Employee__c, Employee__r.PositionLookup__c From Development_Records__c where status__c = \'Incomplete\' and employee__r.Status__c = \'Active\'';
	list<id> delIds;
	Map<id,Position__c> map_id_Position;
	global CleanDRBatch()
	{
	 	delIds = new list<id>();
	 	map_id_Position = new map<id,Position__c>([Select Name, Id, (Select Id, Name, Professional_Development__c From Position__r) From Position__c]);
	}
	
	global Database.Querylocator start(database.batchableContext BC)
	{
		return database.getQueryLocator(query);
	}
	
	global void execute(database.batchableContext BC, list<Development_Records__c> scope)
	{
		set<id> posIDs = new set<id>();
		
		for(Development_Records__c Drs: scope)
		{
			if(Drs.employee__r.PositionLookup__c == null)
				delIds.add(Drs.id);
			
			Position__c p = map_id_Position.get(Drs.employee__r.PositionLookup__c );
			
			if(p == null)
			{
				delIds.add(Drs.id);
				continue;
			}
			boolean found = false;
			for(Mandatory_Professional_Development__c mpd: p.Position__r)
			{
				if(mpd.Professional_Development__c == drs.Professional_Development_Type__c)	
				{
					found = true;
					break;
				}
			}
			
			if(!found)
			{
				delIds.add(Drs.id);
			}
		}
		
		
		
		//Query Posiion
		 
		
	}
	
	global void finish(database.batchableContext BC)
	{
		if(delIds.size() == 0)
			return;
		
		list<Development_Records__c> lstDevRecs = [Select id From Development_Records__c where id in:delIds];
		
		delete lstDevRecs;
	}

}