force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Assigned_To_Unit__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To_Unit__c</fullName>
    <formula>Employee__r.Assigned_to_Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned To Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Date_of_Training__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Training__c</fullName>
    <description>Actual Date training occurred as per certificate</description>
    <label>Date of Training</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Date_Renewal_Required__c.field-meta.xml
<CustomField>
    <fullName>Date_Renewal_Required__c</fullName>
    <label>Date Renewal Required</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Days_for_renewal_required__c.field-meta.xml
<CustomField>
    <fullName>Days_for_renewal_required__c</fullName>
    <label>Days for renewal required</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employees__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Training_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Expiry_Status__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Status__c</fullName>
    <label>Expiry Status</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/PD_Type_Text__c.field-meta.xml
<CustomField>
    <fullName>PD_Type_Text__c</fullName>
    <label>PD Type Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Position_Id__c.field-meta.xml
<CustomField>
    <fullName>Position_Id__c</fullName>
    <description>This field is created to store the related current position id for employee record.</description>
    <label>Position Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Professional_Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Development Type</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Development_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Incomplete</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Unit_Id__c.field-meta.xml
<CustomField>
    <fullName>Unit_Id__c</fullName>
    <description>This field is created to store the current unit id related to employee record.</description>
    <label>Unit Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Assigned_to_Unit__c.field-meta.xml
<CustomField>
    <fullName>Assigned_to_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/PositionLookup__c.field-meta.xml
<CustomField>
    <fullName>PositionLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employees__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre Employment</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/Mandatory_Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Mandatory Professional Development</label>
    <nameField>
        <label>Mandatory Professional Development Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mandatory Professional Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Professional_Development__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professional Development</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Mandatory Professional Development (By Client/Position)</relationshipLabel>
    <relationshipName>Mandatory_Professional_Developments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/fields/Days_until_renewal_is_required__c.field-meta.xml
<CustomField>
    <fullName>Days_until_renewal_is_required__c</fullName>
    <inlineHelpText>Number of days until it needs to be renewed. 
EG: 1 year = 365 Days</inlineHelpText>
    <label>Days until renewal is required</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/fields/Expiry_Status__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Status__c</fullName>
    <label>Expiry Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Does not expire</fullName>
            </value>
            <value>
                <fullName>Expire and clone</fullName>
            </value>
            <value>
                <fullName>Expire and set for refresh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutoPopulateDevelopmentRecordsUtility.cls
//This class is written to handle all the complexity of AutoPopulateDevelopmentRecord  trigger.
public class AutoPopulateDevelopmentRecordsUtility{
    //This method handle all the newely employee insert requests.
    public static void createDevRecordOnEmployeeInsert(List<Employees__c > emloyeeNewList,Map<Id,Id> unitIdAndAccountIdMap,
    Map<Id,List<Mandatory_Professional_Development__c>> accountIdAndMandDevelopmentRecordId ,Map<Id,List<Mandatory_Professional_Development__c>> positionMandDevRecords ){
        
        Map<Id,Map<string,Development_Records__c>> uniqueDevRecUnderEmployee = new Map<Id,Map<string,Development_Records__c >>(); 
        Map<string,Development_Records__c> dumpMap; 
        
        List<Development_Records__c> devRecUnderEmployee = new List<Development_Records__c>();
        
        for(Employees__c emp:emloyeeNewList){
            if(emp.PositionLookup__c!=null||emp.Assigned_to_Unit__c!=null){
               dumpMap = new Map<string,Development_Records__c>();
               if(emp.Assigned_to_Unit__c!=null){
               for(Mandatory_Professional_Development__c d:accountIdAndMandDevelopmentRecordId.get(unitIdAndAccountIdMap.get(emp.Id))) {
                   Development_Records__c devClone = new Development_Records__c();
                    devClone.Professional_Development_Type__c= d.Professional_Development__c;
                    devClone.Employee__c= emp.Id;
                 /*  
                   devClone.Date_of_Training__c=d.Date_of_Training__c;
                   devClone.Date_Renewal_Required__c=d.Date_Renewal_Required__c;
                  
                   devClone.PD_Type_Text__c= d.PD_Type_Text__c;
                  
                   devClone.Status__c = d.Status__c;
                   devClone.Days_for_renewal_required__c = d.Professional_Development_Type__r.Days_until_renewal_is_required__c;
                   devClone.Unit_Id__c = emp.Assigned_to_Unit__c;
                  */
                   //devClone.Expiry_Status__c=d.Professional_Development_Type__r.Expiry_Status__c;
                   dumpMap.put(devClone.Professional_Development_Type__c,devClone);
                   system.debug('------------------Inside LOOP 1-------------------------------'+dumpMap);
               }
               }
               for(Mandatory_Professional_Development__c d1:positionMandDevRecords.get(emp.PositionLookup__c)){
                   Development_Records__c devClone1 = new Development_Records__c();
                   devClone1.Professional_Development_Type__c= d1.Professional_Development__c;
                   devClone1.Employee__c= emp.Id;
                   /*
                   devClone1.Date_of_Training__c=d1.Date_of_Training__c;
                   devClone1.Date_Renewal_Required__c=d1.Date_Renewal_Required__c;
                   
                   
                   devClone1.Status__c = d1.Status__c;
                   devClone1.Days_for_renewal_required__c = d1.Professional_Development_Type__r.Days_until_renewal_is_required__c;
                   devClone1.Position_Id__c = emp.PositionLookup__c;
                   */
                   //devClone1.Expiry_Status__c=d1.Professional_Development_Type__r.Expiry_Status__c;
                   dumpMap.put(devClone1.Professional_Development_Type__c,devClone1);
                    system.debug('------------------Inside LOOP 2-------------------------------'+dumpMap);
               }
               system.debug('------------------start-------------------------------'+dumpMap);
             uniqueDevRecUnderEmployee.put(emp.Id,dumpMap);
                          
            }
       }
     
       
           for(Map<string,Development_Records__c> mp:uniqueDevRecUnderEmployee.Values()){
               for(Development_Records__c d:mp.values()){
                   devRecUnderEmployee.add(d);
               }       
           }
       
       
           database.insert(devRecUnderEmployee);
     
           
       
    }
    //This method handles all the employee update requests.
    public static void updateDevRecordsUnderEmployee(Map<Id,Employees__c> oldEmpMap,List<Employees__c > emloyeeNewList,List<Employees__c > emloyeeOldList,
    Map<Id,Id> unitIdAndAccountIdMap,Map<Id,List<Mandatory_Professional_Development__c>> accountIdAndDevelopmentRecordId,
    Map<Id,List<Mandatory_Professional_Development__c>> positionMandDevRecords,Map<Id,List<Development_Records__c>> oldEmpDevRecords){
    Map<Id,Set<Id>> setprofessionalDevMap = new Map<Id,Set<Id>>();
        Map<Id,List<Mandatory_Professional_Development__c>> newPositionMandDevelopmentRec = new Map<Id,List<Mandatory_Professional_Development__c>>();
        Map<Id,List<Mandatory_Professional_Development__c>> newUnitMandDevelopmentRec = new Map<Id,List<Mandatory_Professional_Development__c>>();
        
        Map<Id,Map<string,Mandatory_Professional_Development__c>> mapNewUniqueMandDevRecords = new Map<Id,Map<string,Mandatory_Professional_Development__c>>();
        Map<string,Mandatory_Professional_Development__c> dumpMaptoUniq;
        
        for(Employees__c emp:emloyeeNewList){
            //if((emp.PositionLookup__c!=oldEmpMap.get(emp.Id).PositionLookup__c)||(emp.Assigned_to_Unit__c!=oldEmpMap.get(emp.Id).Assigned_to_Unit__c)){
                newPositionMandDevelopmentRec.put(emp.Id,positionMandDevRecords.get(emp.PositionLookup__c)); 
                newUnitMandDevelopmentRec.put(emp.Id,accountIdAndDevelopmentRecordId.get(unitIdAndAccountIdMap.get(emp.Id)));          
            //}
        } 
        system.debug('----------------------New Position Dev Records------------'+newPositionMandDevelopmentRec);  
        system.debug('----------------------New Unit Dev Records------------'+newUnitMandDevelopmentRec); 
        system.debug('----------------------Already existing devRecords------------'+oldEmpDevRecords);
       
        for(Employees__c emp:emloyeeNewList){
            dumpMaptoUniq = new Map<string,Mandatory_Professional_Development__c>();
            if(emp.PositionLookup__c!=null){
                for(Mandatory_Professional_Development__c dev:newPositionMandDevelopmentRec.get(emp.Id)){
                    dumpMaptoUniq.put(dev.Professional_Development__c,dev);
                }
            }
            if(emp.Assigned_to_Unit__c!=null){
                for(Mandatory_Professional_Development__c dev:newUnitMandDevelopmentRec.get(emp.Id)){
                    dumpMaptoUniq.put(dev.Professional_Development__c,dev);
                }
            }
            mapNewUniqueMandDevRecords.put(emp.Id,dumpMaptoUniq);    
        
        }
        
        system.debug('---111111111111111111-------Unique New------------'+mapNewUniqueMandDevRecords); 
        //To avoid duplicates and from new records 
        for(Employees__c emp:emloyeeNewList){
           for(string s :mapNewUniqueMandDevRecords.get(emp.Id).keySet()){
               Integer flag =0;
               for(Development_Records__c dev:oldEmpDevRecords.get(emp.Id)){
                   if(dev.Professional_Development_Type__c == s){
                       flag++;
                   }
               } 
               if(flag>0){
                   mapNewUniqueMandDevRecords.get(emp.Id).remove(s);
               }   
           }
        }
   
       system.debug('----2222222222222222222-------Unique New------------'+mapNewUniqueMandDevRecords); 
     
     //Copy new records from unique development records
     List<Development_Records__c> newDevRecords = new List<Development_Records__c>(); 
     for(Employees__c emp:emloyeeNewList){
         if((emp.PositionLookup__c!=oldEmpMap.get(emp.Id).PositionLookup__c)&&(emp.Assigned_to_Unit__c!=oldEmpMap.get(emp.Id).Assigned_to_Unit__c)){
              for(Mandatory_Professional_Development__c d:mapNewUniqueMandDevRecords.get(emp.Id).values()){
                  Development_Records__c dNew = new Development_Records__c();
                  dNew.Professional_Development_Type__c= d.Professional_Development__c;
                  dNew.Employee__c= emp.Id;
                 /* 
                  dNew.Date_of_Training__c=d.Date_of_Training__c;
                  dNew.Date_Renewal_Required__c=d.Date_Renewal_Required__c;
                  
                  
                  dNew.Status__c = d.Status__c;
                  dNew.Unit_Id__c = emp.Assigned_to_Unit__c;
                  dNew.Position_Id__c = emp.PositionLookup__c;
                  dNew.Days_for_renewal_required__c = d.Professional_Development_Type__r.Days_until_renewal_is_required__c;
                 */
                  //dNew.Expiry_Status__c=d.Professional_Development_Type__r.Expiry_Status__c;
                  newDevRecords.add(dNew);
             }
         }
        else if(emp.PositionLookup__c!=oldEmpMap.get(emp.Id).PositionLookup__c){
             for(Mandatory_Professional_Development__c d:mapNewUniqueMandDevRecords.get(emp.Id).values()){
                  Development_Records__c dNew = new Development_Records__c();
                  dNew.Professional_Development_Type__c= d.Professional_Development__c;
                  dNew.Employee__c= emp.Id;
                 /*
                  dNew.Date_of_Training__c=d.Date_of_Training__c;
                  dNew.Date_Renewal_Required__c=d.Date_Renewal_Required__c;
                  
                  dNew.Professional_Development_Type__c= d.Professional_Development_Type__c;
                  dNew.Status__c = d.Status__c;
                  dNew.Position_Id__c = emp.PositionLookup__c;
                  dNew.Days_for_renewal_required__c = d.Professional_Development_Type__r.Days_until_renewal_is_required__c;
                  */
                  //dNew.Expiry_Status__c=d.Professional_Development_Type__r.Expiry_Status__c;
                  newDevRecords.add(dNew);
             }
         }
         else if(emp.Assigned_to_Unit__c!=oldEmpMap.get(emp.Id).Assigned_to_Unit__c){
             for(Mandatory_Professional_Development__c d:mapNewUniqueMandDevRecords.get(emp.Id).values()){
                  Development_Records__c dNew = new Development_Records__c();
                  dNew.Professional_Development_Type__c= d.Professional_Development__c;
                  dNew.Employee__c= emp.Id;
                  /*
                  dNew.Date_of_Training__c=d.Date_of_Training__c;
                  dNew.Date_Renewal_Required__c=d.Date_Renewal_Required__c;
                  
                 
                  dNew.Status__c = d.Status__c;
                  dNew.Unit_Id__c = emp.Assigned_to_Unit__c;
                  dNew.Days_for_renewal_required__c = d.Professional_Development_Type__r.Days_until_renewal_is_required__c;
                  */
                  //dNew.Expiry_Status__c=d.Professional_Development_Type__r.Expiry_Status__c;
                  newDevRecords.add(dNew);
             }
         }
        
        
     }
    
         database.insert(newDevRecords);
    
 }   
    
    
    
    
    
    
}