force-app/main/default/objects/Daily_Report__c/Daily_Report__c.object-meta.xml
<CustomObject>
    <label>Daily Site Job</label>
    <nameField>
        <displayFormat>DSJ-{00000}</displayFormat>
        <label>Daily Site Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Site Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Item__c/Daily_Report_Item__c.object-meta.xml
<CustomObject>
    <label>Daily Job Item</label>
    <nameField>
        <displayFormat>DJI-{000000}</displayFormat>
        <label>Daily Report Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Report_Item__c/fields/Daily_Report__c.field-meta.xml
<CustomField>
    <fullName>Daily_Report__c</fullName>
    <label>Daily Report</label>
    <referenceTo>Daily_Report__c</referenceTo>
    <relationshipName>Daily_Report_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SiteJobItemSpecific_Controller.cls
public class SiteJobItemSpecific_Controller {
    
    private final Daily_Report_Item__c dri;
    public Daily_Report_Item__c dritm;
    public SiteJobItemSpecific_Controller(ApexPages.StandardController stdController){
        this.dri = (Daily_Report_Item__c) stdController.getRecord();
    }
    
    public PageReference siteJobItemSpecific(){
        dritm = [select Id,Daily_Report__c from Daily_Report_Item__c where Id =: dri.Id];
        PageReference pgRef = new PageReference('/apex/SiteJobItem_VF?id='+dritm.Daily_Report__c+'&driItem='+dritm.Id);
        pgRef.setRedirect(true);
        return pgRef;
    }

}