force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>QU-{000000}</displayFormat>
        <label>Quote No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Details_for_Supplier__c.field-meta.xml
<CustomField>
    <fullName>Details_for_Supplier__c</fullName>
    <label>Details for Supplier</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_Item_Table__c.field-meta.xml
<CustomField>
    <fullName>Quote_Item_Table__c</fullName>
    <label>Quote Item Table</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier [From Quote]</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Supplier_Address_formula__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Address_formula__c</fullName>
    <formula>IF(NOT(ISBLANK(Supplier__r.BillingStreet)), Supplier__r.BillingStreet, NULL) +
IF(NOT(ISBLANK(Supplier__r.BillingCity)), &quot; &quot; + Supplier__r.BillingCity, NULL) +
IF(NOT(ISBLANK(Supplier__r.BillingState)), &quot;, &quot; + Supplier__r.BillingState, NULL) +
IF(NOT(ISBLANK(Supplier__r.BillingPostalCode)), &quot;, &quot; + Supplier__r.BillingPostalCode, NULL) +
IF(NOT(ISBLANK(Supplier__r.BillingCountry)), &quot; &quot; + Supplier__r.BillingCountry, NULL)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Supplier_Phone_formula__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Phone_formula__c</fullName>
    <formula>Supplier__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Supplier Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GenerateQuote_Controller.cls
/** This class is used for 'GenerateQuote_Pdf' to get the Quote details
 * CreatedBy: Cinch + Strike
 * Created Date: 25th NOV 2022
 * 
 * History
 * 25-NOV-2022    Vic Petilla    Initial Creation
**/

public with sharing class GenerateQuote_Controller {

    private final Quote__c quo;
    public String quoteName { get; set; }
    public String supplierName { get; set; }
    public String supplierAddress { get; set; }
    public String supplierPhone { get; set; }
    public String quoteItems { get; set; }
    public String detailsForSupplier { get; set; }


    public GenerateQuote_Controller(ApexPages.StandardController stdController) {

        try {

            quo = (Quote__c) stdController.getRecord();
            List<Quote__c> tempquote = [SELECT Id, Name, Supplier__r.Name, Supplier_Address_formula__c, Supplier_Phone_formula__c, Quote_Item_Table__c, Details_for_Supplier__c
                FROM Quote__c WHERE Id = :quo.Id LIMIT 1];

            for (Quote__c quote : tempquote) {
                quoteName = quote.Name;
                supplierName = quote.Supplier__r.Name;
                supplierAddress = quote.Supplier_Address_formula__c;
                supplierPhone = quote.Supplier_Phone_formula__c;
                quoteItems = quote.Quote_Item_Table__c;
                detailsForSupplier = quote.Details_for_Supplier__c;
            }
            
        } catch (Exception e){
            System.debug('At '+e.getLineNumber()+'. Cause: '+e.getCause()+'. ErrorMessage: '+e.getMessage());
        }
    }
}