force-app/main/default/objects/WD_Personnel__c/WD_Personnel__c.object-meta.xml
<CustomObject>
    <label>WD Personnel</label>
    <nameField>
        <displayFormat>WDP-{00000}</displayFormat>
        <label>WDP#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WD Personnel</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Personnel__c/fields/Total_Hours__c.field-meta.xml
<CustomField>
    <fullName>Total_Hours__c</fullName>
    <inlineHelpText>This is the total Work Hrs over a 24hr DAY Period as per Work Diary (not a 24hr WORK Period.)  This does not effect payroll or man hour stats.</inlineHelpText>
    <label>Total Work Hrs</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/WD_Report__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <displayFormat>JO-{00000}</displayFormat>
        <label>JO #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Report__c/fields/Personnel_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Personnel_Hrs__c</fullName>
    <label>Personnel Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/skedComputePersonnelHrs.cls
//Use by sked_WDR_PersonnelHrs_trigger   
public with sharing class skedComputePersonnelHrs{

    public WD_Report__c ReturnWDPersonnelHrs(List<WD_Personnel__c> listPersonnel, WD_Report__c WDR){

        try{    
            decimal PersonnelHrs = 0;
                
                for (WD_Personnel__c p : listPersonnel){
                          PersonnelHrs += p.Total_Hours__c;
                }
                
                WDR.Personnel_Hrs__c = PersonnelHrs;
                    
        }catch(Exception e){}
        
        return WDR;
                                
    }
}