force-app/main/default/objects/Contract_Item__c/Contract_Item__c.object-meta.xml
<CustomObject>
    <label>Contract Job Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contract Job Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Item__c/fields/Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Service_Type__c</fullName>
    <inlineHelpText>If not selected then auto-populated from Item</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Price/Hour</fullName>
            </value>
            <value>
                <fullName>Fixed Price/Quantity</fullName>
            </value>
            <value>
                <fullName>Flexi Price/Quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>WD Asset</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Asset__c.Parent_Asset__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Asset__c.Inventory_Item__c</field>
            <operation>equals</operation>
            <value>Stacked</value>
        </filterItems>
        <filterItems>
            <field>$Source.Contract__c</field>
            <operation>equals</operation>
            <valueField>Asset__c.Unit__r.Contract_New__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Contract Job Items</relationshipLabel>
    <relationshipName>Contract_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract_Item__c/fields/WD_Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset_Name__c</fullName>
    <formula>WD_Asset__r.Name</formula>
    <label>WD Asset Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Typeahead.cls
// Controller class for the Force.com Typeahead component
public with sharing class Typeahead {

  @RemoteAction
  public static list<sObject> searchRecords( String queryString, String objectName, 
    list<String> fieldNames, String fieldsToSearch, String filterClause, String orderBy, Integer recordLimit ) {

    if (queryString == null) return null;

    String sQuery = String.escapeSingleQuotes( queryString );
    if (sQuery.length() == 0) return null;

    String sObjectName = (objectName == null) ? 'Contact' : String.escapeSingleQuotes( objectName );

    String sInFields = 
      (fieldsToSearch == null || fieldsToSearch == '' || fieldsToSearch.toUpperCase() == 'ALL') ? '' : ( ' IN ' + String.escapeSingleQuotes(fieldsToSearch) + ' FIELDS' );
    
    if(sObjectName == 'Contract_Item__c'){
        fieldNames.add('Service_Type__c');fieldNames.add('WD_Asset_Name__c');fieldNames.add('WD_Asset__c');}            
    
    
    String sFields = (fieldNames == null || fieldNames.isEmpty()) ? 'Id, Name' : String.escapeSingleQuotes( String.join( fieldNames, ', ' ) );  
    
    String sOrder = ' ORDER BY ' + ( (orderBy == null || orderBy == '') ? 'Name' : String.escapeSingleQuotes(orderBy) ); 
    
    String sLimit = (recordLimit == null || recordLimit == 0 || recordLimit >= 2000) ? '' : ( ' LIMIT ' + String.valueOf(recordLimit));
    
    // can't escape the filter clause
    String sWhere = (filterClause == null || filterClause == '') ? '' : ( ' WHERE ' + filterClause );
    string query = 'FIND \'' + sQuery + '*\'' + sInFields + ' RETURNING ' + sObjectName + '( ' + sFields + sWhere + sOrder + sLimit + ' )';   
        system.debug('query: ' + query);
    list<list<sObject>> results = Search.query(
      'FIND \'' + sQuery + '*\'' + sInFields + 
        ' RETURNING ' + sObjectName + '( ' + sFields + sWhere + sOrder + sLimit + ' )'
    );
    
    return results[0];
  }  

}