force-app/main/default/objects/Daily_Pre_Start__c/Daily_Pre_Start__c.object-meta.xml
<CustomObject>
    <label>Daily Pre-Start</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Daily Pre-Start #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Pre-Starts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Pre_Start__c/fields/Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver Assignment</label>
    <referenceTo>Driver_Assignment__c</referenceTo>
    <relationshipLabel>Daily Pre-Starts</relationshipLabel>
    <relationshipName>Daily_Pre_Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Pre_Start__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Driver Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000000}</displayFormat>
        <label>Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Driver Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver_Status__c.field-meta.xml
<CustomField>
    <fullName>Driver_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Transport_Job__c.field-meta.xml
<CustomField>
    <fullName>Transport_Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transport Job</label>
    <referenceTo>Transport_Job__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/Transport_Job__c.object-meta.xml
<CustomObject>
    <label>Transport Job</label>
    <nameField>
        <displayFormat>TJ-{0000000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerAutomations__c/TriggerAutomations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Trigger Automations</label>
</CustomObject>

force-app/main/default/objects/TriggerAutomations__c/fields/Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Driver Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DriverAssignmentTriggerHandler.cls
/****
 * Apex Class for Driver Assignment Tigger Handler; 
 * Author: D Banez
 * Date: Sept 2020 
 * Test Class: DriverAssignmentTriggerHandlerTest
*/
public with sharing class DriverAssignmentTriggerHandler {
	public static TriggerAutomations__c automationEnabled  = TriggerAutomations__c.getInstance(); 
	public static Boolean daEnabled = automationEnabled.Driver_Assignment__c;
    
	public static void mainEntry(Boolean isBefore, Boolean isAfter, Boolean isInsert, Boolean isUpdate,Boolean isDelete, Boolean isUnDelete, 
                    List<SObject> newList, List<SObject> oldList, Map<ID, SObject> newmap, Map<ID, SObject> oldmap)
    {
    	// In a test context always set this to true        
        if (Test.isrunningTest())  {
            daEnabled = true;
        }
        // Perform business logic
        if(daEnabled){
        	try{
            	// INSERT TRIGGER
                if(isInsert){
                    // Before
                    if(isBefore){

                    }            
                    // After
                    if(isAfter){

                    }
                }
                // Update TRIGGER
                if(isUpdate){
                    // Before
                    if(isBefore){
                    	updateStartEndTime(newList);
                    }            
                    // After
                    if(isAfter){
                   		
                    }
                }
                // Delete TRIGGER
                if(isDelete){
                    // Before
                    if(isBefore){

                    }            
                    // After
                    if(isAfter){
						//processTransportJobsAndPreStarts((Map<Id, Driver_Assignment__c>) oldMap);
                    }
                }
                // UNDELETE Trigger
                if(isUnDelete){}  
            } catch (Exception ex){
                newList[0].addError(ex.getStackTraceString()+'--'+ ex.getTypeName()+'--'+ ex.getMessage());
            }
        }
    }
    
    //Using this method to format time on text
    public static void updateStartEndTime(List<Driver_Assignment__c> newList){
        for(Driver_Assignment__c da: newList) {
            if(da.Start_Date_Time__c != null){
                da.Start_Time__c = da.Start_Date_Time__c.format('hh:mm a');
            } else {
                da.Start_Time__c = '';
            }

            if(da.End_Date_Time__c != null){
            	da.End_Time__c = da.End_Date_Time__c.format('hh:mm a');
            } else {
                da.End_Time__c = '';
            }
                
        }
        
    }
    
    //deletion of related daily pre-starts
    /*public static void processTransportJobsAndPreStarts(Map<Id, Driver_Assignment__c> oldMap){
        List<Daily_Pre_Start__c> preStartsToDelete = new List<Daily_Pre_Start__c>();
        List<Driver_Assignment__c> daList = [select Id, Transport_Job__c,
                                             (select Id from Daily_Pre_Starts__r) from Driver_Assignment__c where Id in :oldMap.keySet()];
        Set<Id> transportJobIdSet = new Set<Id>();
        for (Driver_Assignment__c da : daList){
            if (da.Daily_Pre_Starts__r.size() > 0){
                preStartsToDelete.addAll(da.Daily_Pre_Starts__r);
            }
            transportJobIdSet.add(da.Transport_Job__c);
        }

        List<Transport_Job__c> parentJobList = [select Id, Status__c, (select Id, Driver_Status__c from Driver_Assignments__r)
            from Transport_Job__c where Id in : transportJobIdSet];
        List<Transport_Job__c> jobsToUpdateList = new List<Transport_Job__c>();
        for (Transport_Job__c job : parentJobList){
            Integer draftCount = 0;
            Integer assignedCount = 0;
            Integer inProgressCount = 0;
            Integer completedCount = 0;
            Integer totalCount = job.Driver_Assignments__r.size();
            for (Driver_Assignment__c da : job.Driver_Assignments__r){
                draftCount += (da.Driver_Status__c == 'Draft') ? 1 : 0;
                assignedCount += (da.Driver_Status__c == 'Assigned') ? 1 : 0;
                inProgressCount += (da.Driver_Status__c == 'In Progress') ? 1 : 0;
                completedCount += (da.Driver_Status__c == 'Completed') ? 1 : 0;
            }
            if (draftCount == totalCount){ // all  Remaining is Draft
                job.Status__c = 'Draft'; // reset to Draft
            } 
            else if (assignedCount == totalCount){
                job.Status__c = 'Assigned';  // set to assigned
            }
            else if (inProgressCount == totalCount){
                job.Status__c = 'In Progress';  // set to In progress
            }
            else if (completedCount == totalCount){
                job.Status__c = 'Completed';  // set to Completed
            }
            jobsToUpdateList.add(job); 
        }

        if (preStartsToDelete.size() > 0){
            try {
                delete preStartsToDelete;
            }
            catch (DmlException e){
                System.debug('There is an error deleting Driver Assignments: ' + e.getMessage());
            }
        }

        if (jobsToUpdateList.size() > 0){
            try {
                //delete jobsToUpdateList;
                update jobsToUpdateList;
            }
            catch (DmlException e){
                //System.debug('There is an error deleting Driver Assignments: ' + e.getMessage());
                System.debug('There is an error updating Transport job: ' + e.getMessage());
            }
        }
    }*/
}