force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO{00000}</displayFormat>
        <label>PO No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>PO Approved</fullName>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
            </value>
            <value>
                <fullName>Partially Fulfilled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Supplier</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Supplier_Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/Purchase_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Item</label>
    <nameField>
        <label>PO Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item Master</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Item__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Items</relationshipLabel>
    <relationshipName>Purchase_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/Purchase_Request__c.object-meta.xml
<CustomObject>
    <label>Purchase Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>PR No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Request__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventory</fullName>
            </value>
            <value>
                <fullName>Non-Inventory</fullName>
            </value>
            <value>
                <fullName>Assorted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item</label>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Source_Store_Item__c.field-meta.xml
<CustomField>
    <fullName>Source_Store_Item__c</fullName>
    <label>Source Store Item</label>
    <referenceTo>Store_Item__c</referenceTo>
    <relationshipLabel>Purchase Requests (Source Store Item)</relationshipLabel>
    <relationshipName>Purchase_Requests2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Purchasing Review</fullName>
            </value>
            <value>
                <fullName>Approver Review</fullName>
            </value>
            <value>
                <fullName>For Approval - Review Complete</fullName>
            </value>
            <value>
                <fullName>For Item Review</fullName>
            </value>
            <value>
                <fullName>For Approval</fullName>
            </value>
            <value>
                <fullName>For Ordering</fullName>
            </value>
            <value>
                <fullName>Pick List</fullName>
            </value>
            <value>
                <fullName>Packing List</fullName>
            </value>
            <value>
                <fullName>In Transit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Dispute</fullName>
            </value>
            <value>
                <fullName>Approved - For Ordering</fullName>
                <isActive>false</isActive>
                <label>Approved - For Ordering</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Defective</fullName>
                <isActive>false</isActive>
                <label>Defective</label>
            </value>
            <value>
                <fullName>For Item Approval</fullName>
                <isActive>false</isActive>
                <label>For Item Approval</label>
            </value>
            <value>
                <fullName>For Pricing Approval</fullName>
                <isActive>false</isActive>
                <label>For Pricing Approval</label>
            </value>
            <value>
                <fullName>For Quoting</fullName>
                <isActive>false</isActive>
                <label>For Quoting</label>
            </value>
            <value>
                <fullName>Missing</fullName>
                <isActive>false</isActive>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Ready for Collection</fullName>
                <isActive>false</isActive>
                <label>Ready for Collection</label>
            </value>
            <value>
                <fullName>Sent to Supplier</fullName>
                <isActive>false</isActive>
                <label>Sent to Supplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Request__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PR Supplier - This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</description>
    <inlineHelpText>This Supplier is linked to the Item Master [Prefered Supplier (1st)] or Quote Supplier unless otherwise updated.</inlineHelpText>
    <label>Supplier</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Only Supplier accounts are allowed. Please check the Supplier selected.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Supplier</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Requests</relationshipLabel>
    <relationshipName>Purchase_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Item__c/Store_Item__c.object-meta.xml
<CustomObject>
    <description>Conjunction object for Item Master and Unit
Label changed to Inventory Item from Store Item</description>
    <label>Inventory Item</label>
    <nameField>
        <displayFormat>INT-{00000}</displayFormat>
        <label>Inventory Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Item__c/fields/Default_ReOder_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Default_ReOder_Quantity__c</fullName>
    <label>Maximum ReOrder Quantity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Item__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only Active Inventory Items are allowed</errorMessage>
        <filterItems>
            <field>Inventory_Item__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Inventory_Item__c</referenceTo>
    <relationshipLabel>Inventory Items</relationshipLabel>
    <relationshipName>Store_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Item__c/fields/Minimum_Quantity_for_Restocking__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Quantity_for_Restocking__c</fullName>
    <label>Minimum Quantity for Restocking</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Item__c/fields/Store_Unit__c.field-meta.xml
<CustomField>
    <fullName>Store_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store (Unit)</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipName>Store_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreatePOsFromPRsTest.cls
@isTest
public class CreatePOsFromPRsTest {

    @isTest
    public static void POsFromPRsTest(){
        TestDataFactory testData = new TestDataFactory();
        Id supplierRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
        
        Account Supplier1 = new Account(Name = 'Test Supplier 1', Email__c = 'Test1@suplier.com', RecordTypeId = supplierRecordTypeId, Regions_LG_Area__c = 'Asia');
        Account Supplier2 = new Account(Name = 'Test Supplier 2', Email__c = 'Test2@suplier.com', RecordTypeId = supplierRecordTypeId, Regions_LG_Area__c = 'Asia');
        insert Supplier1;
        insert Supplier2;
        System.debug('Suppliers Created : 1st - '+Supplier1.Id +' , 2nd - '+ Supplier2.Id);
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(LastName = 'Dhoni',
                           FirstName='MS',
                           Alias = 'msd',
                           Email = 'ms@dhoni.com.prod',
                           Username = 'ms@dhoni.com.prod',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US'
                           );
        insert testUser;
        System.debug('User Created : '+testUser.Id);
        
        Inventory_Item__c invItem1 = new Inventory_Item__c(Name = 'Test Inv Item 1', OwnerId = testUser.Id, Active__c = true);
        Inventory_Item__c invItem2 = new Inventory_Item__c(Name = 'Test Inv Item 2', OwnerId = testUser.Id, Active__c = true);
        insert invItem1;
        insert invItem2;
        System.debug('Inventory Items Created : 1st - '+invItem1.Id +' , 2nd - '+ invItem2.Id);
        
        Unit__c unit = new Unit__c(Name = 'Test Unit');
        insert unit;
        Unit__c unit2 = new Unit__c(Name = 'Test Unit2');
        insert unit2;
        System.debug('Unit Created : '+unit2.Id);
        
        Store_Item__c storeItem1 = new Store_Item__c(Inventory_Item__c = invItem1.Id, Store_Unit__c = unit.Id, Minimum_Quantity_for_Restocking__c = 15, Default_ReOder_Quantity__c = 15);
        Store_Item__c storeItem2 = new Store_Item__c(Inventory_Item__c = invItem2.Id, Store_Unit__c = unit2.Id, Minimum_Quantity_for_Restocking__c = 15, Default_ReOder_Quantity__c = 15);
        insert storeItem1;
        insert storeItem2;
        System.debug('Store Items Created : 1st - '+storeItem1.Id +' , 2nd - '+ storeItem2.Id);
        
        Inventory_Item__c invobj = new Inventory_Item__c(Name ='Test Item');
		insert invobj;
        
        Purchase_Request__c pr1 = new Purchase_Request__c(Status__c = 'Pick List',Item__c = invobj.id, Category__c = 'Inventory', Source_Store_Item__c = storeItem1.Id, Quantity__c = 30, Supplier__c = Supplier1.Id);
        Purchase_Request__c pr2 = new Purchase_Request__c(Status__c = 'Pick List',Item__c = invobj.id, Category__c = 'Inventory', Source_Store_Item__c = storeItem2.Id, Quantity__c = 20, Supplier__c = Supplier2.Id);
        insert pr1;
        insert pr2;
        List<Purchase_Request__c> purchaseReqList = new List<Purchase_Request__c>();
        purchaseReqList.add(pr1);
        purchaseReqList.add(pr2);
        System.debug('Purchase requisitions Created : 1st - ' + pr1 + ' , 2nd - '+ pr2);
        
        List<CreatePOsFromPRs.InvocableInput> InvInputobjList = new List<CreatePOsFromPRs.InvocableInput>();
        
        CreatePOsFromPRs.InvocableInput obj = new CreatePOsFromPRs.InvocableInput();
        system.debug('!!'+purchaseReqList);
        obj.purchaseRequestList = new List<Purchase_Request__c>();
        obj.purchaseRequestList.addAll(purchaseReqList);
        System.debug('Invocable Object : '+ obj);
        System.debug('PR List Invocable : '+ obj.purchaseRequestList);
        
        InvInputobjList.add(obj);
        System.debug('Invocable Input List : '+ InvInputobjList);
        CreatePOsFromPRs.createPOs(InvInputobjList); 
        

        List<CreatePOsFromPRs.InvocableOutput> InvOutput = CreatePOsFromPRs.createPOs(InvInputobjList);
        System.debug('!!!!' + InvOutput);
        List<Purchase_Order__c> poList = new List<Purchase_Order__c>();
        for(CreatePOsFromPRs.InvocableOutput obj1 : InvOutput){
            System.debug('in loop : ' +obj1);
            poList = obj1.purchaseOrderList;
        }
        System.debug('PO Lists : ' + poList);
		List<Purchase_Order_Item__c> poListTest = [SELECT Purchase_Order__r.Supplier__c ,Inventory_Item__c , No_of_PR_Items__c, No_of_Items_Still_Pending__c, Quantity__c,Name from Purchase_Order_Item__c WHERE Purchase_Order__c in :poList];
        for(Purchase_Order_Item__c poItems : poListTest){
            if(poItems.Purchase_Order__r.Supplier__c == Supplier1.Id){
                System.assertEquals(pr1.Quantity__c, poItems.Quantity__c, 'Quantity Mismatch for PO of Supplier 1');
                System.assertEquals(1, poItems.No_of_PR_Items__c, 'No of PRs mismatch for PO of Supplier 1');
                System.assertEquals(pr1.Quantity__c, poItems.No_of_Items_Still_Pending__c,'No of pending items mismatch for PO of Supplier 1');
            }
            else if(poItems.Purchase_Order__r.Supplier__c == Supplier2.Id){
                System.assertEquals(pr2.Quantity__c, poItems.Quantity__c, 'Quantity Mismatch for PO of Supplier 2');
                System.assertEquals(1, poItems.No_of_PR_Items__c, 'No of PRs mismatch for PO of Supplier 2');
                System.assertEquals(pr2.Quantity__c, poItems.No_of_Items_Still_Pending__c,'No of pending items mismatch for PO of Supplier 2');
            }
        }
    }

    @IsTest
    public static void noSNumberItem(){
        TestDataFactory testData = new TestDataFactory();
        Id supplierRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Supplier').getRecordTypeId();
        
        Account Supplier1 = new Account(Name = 'Test Supplier 1', Email__c = 'Test1@suplier.com', RecordTypeId = supplierRecordTypeId, Regions_LG_Area__c = 'Asia');
        Account Supplier2 = new Account(Name = 'Test Supplier 2', Email__c = 'Test2@suplier.com', RecordTypeId = supplierRecordTypeId, Regions_LG_Area__c = 'Asia');
        insert Supplier1;
        insert Supplier2;
        System.debug('Suppliers Created : 1st - '+Supplier1.Id +' , 2nd - '+ Supplier2.Id);
        
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(LastName = 'Dhoni',
                           FirstName='MS',
                           Alias = 'msd',
                           Email = 'ms@dhoni.com.prod',
                           Username = 'ms@dhoni.com.prod',
                           ProfileId = profileId.id,
                           TimeZoneSidKey = 'GMT',
                           LanguageLocaleKey = 'en_US',
                           EmailEncodingKey = 'UTF-8',
                           LocaleSidKey = 'en_US'
                           );
        insert testUser;
        System.debug('User Created : '+testUser.Id);
        
        Unit__c unit = new Unit__c(Name = 'Test Unit');
        insert unit;
        Unit__c unit2 = new Unit__c(Name = 'Test Unit2');
        insert unit2;
        System.debug('Unit Created : '+unit2.Id);

        Inventory_Item__c invItem1 = new Inventory_Item__c(Name = 'Test Inv Item 1', OwnerId = testUser.Id, Active__c = true);
        Inventory_Item__c invItem2 = new Inventory_Item__c(Name = 'Test Inv Item 2', OwnerId = testUser.Id, Active__c = true);
        insert invItem1;
        insert invItem2;

        Store_Item__c storeItem1 = new Store_Item__c(Inventory_Item__c = invItem1.Id, Store_Unit__c = unit.Id, Minimum_Quantity_for_Restocking__c = 15, Default_ReOder_Quantity__c = 15);
        Store_Item__c storeItem2 = new Store_Item__c(Inventory_Item__c = invItem2.Id, Store_Unit__c = unit2.Id, Minimum_Quantity_for_Restocking__c = 15, Default_ReOder_Quantity__c = 15);
        insert storeItem1;
        insert storeItem2;
        System.debug('Store Items Created : 1st - '+storeItem1.Id +' , 2nd - '+ storeItem2.Id);

        
        Purchase_Request__c pr1 = new Purchase_Request__c(Status__c = 'Pick List', New_Item_Name__c = 'same item', Source_Store_Item__c = storeItem1.Id, Category__c = 'Inventory', Quantity__c = 30, Supplier__c = Supplier1.Id);
        Purchase_Request__c pr2 = new Purchase_Request__c(Status__c = 'Pick List', New_Item_Name__c = 'same item', Source_Store_Item__c = storeItem2.Id, Category__c = 'Inventory', Quantity__c = 20, Supplier__c = Supplier2.Id);
        insert pr1;
        insert pr2;
        List<Purchase_Request__c> purchaseReqList = new List<Purchase_Request__c>();
        purchaseReqList.add(pr1);
        purchaseReqList.add(pr2);
        System.debug('Purchase requisitions Created : 1st - ' + pr1 + ' , 2nd - '+ pr2);
        
        List<CreatePOsFromPRs.InvocableInput> InvInputobjList = new List<CreatePOsFromPRs.InvocableInput>();
        
        CreatePOsFromPRs.InvocableInput obj = new CreatePOsFromPRs.InvocableInput();
        system.debug('!!'+purchaseReqList);
        obj.purchaseRequestList = new List<Purchase_Request__c>();
        obj.purchaseRequestList.addAll(purchaseReqList);
        System.debug('Invocable Object : '+ obj);
        System.debug('PR List Invocable : '+ obj.purchaseRequestList);
        
        InvInputobjList.add(obj);
        System.debug('Invocable Input List : '+ InvInputobjList);
        CreatePOsFromPRs.createPOs(InvInputobjList); 
        

        List<CreatePOsFromPRs.InvocableOutput> InvOutput = CreatePOsFromPRs.createPOs(InvInputobjList);
        System.debug('!!!!' + InvOutput);
        List<Purchase_Order__c> poList = new List<Purchase_Order__c>();
        for(CreatePOsFromPRs.InvocableOutput obj1 : InvOutput){
            System.debug('in loop : ' +obj1);
            poList = obj1.purchaseOrderList;
        }
        System.debug('PO Lists : ' + poList);
		List<Purchase_Order_Item__c> poListTest = [SELECT Purchase_Order__r.Supplier__c ,Inventory_Item__c , No_of_PR_Items__c, No_of_Items_Still_Pending__c, Quantity__c,Name from Purchase_Order_Item__c WHERE Purchase_Order__c in :poList];
        for(Purchase_Order_Item__c poItems : poListTest){
            if(poItems.Purchase_Order__r.Supplier__c == Supplier1.Id){
                System.assertEquals(pr1.Quantity__c, poItems.Quantity__c, 'Quantity Mismatch for PO of Supplier 1');
                System.assertEquals(1, poItems.No_of_PR_Items__c, 'No of PRs mismatch for PO of Supplier 1');
                System.assertEquals(pr1.Quantity__c, poItems.No_of_Items_Still_Pending__c,'No of pending items mismatch for PO of Supplier 1');
            }
            else if(poItems.Purchase_Order__r.Supplier__c == Supplier2.Id){
                System.assertEquals(pr2.Quantity__c, poItems.Quantity__c, 'Quantity Mismatch for PO of Supplier 2');
                System.assertEquals(1, poItems.No_of_PR_Items__c, 'No of PRs mismatch for PO of Supplier 2');
                System.assertEquals(pr2.Quantity__c, poItems.No_of_Items_Still_Pending__c,'No of pending items mismatch for PO of Supplier 2');
            }
        }
    }
}