force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Current_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer_Reading__c</fullName>
    <label>Current Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Driver_Assignment__c/Asset_Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Asset Driver Assignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Asset Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Driver Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Driver_Assignment__c/fields/Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment__c</fullName>
    <label>Driver Assignment</label>
    <referenceTo>Driver_Assignment__c</referenceTo>
    <relationshipLabel>Asset Driver Assignments</relationshipLabel>
    <relationshipName>Asset_Driver_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Driver_Assignment__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Driver_Assignment__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <label>WD Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Inventory_Item__c</field>
            <operation>notEqual</operation>
            <value>Obselete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Driver Assignments</relationshipLabel>
    <relationshipName>Asset_Driver_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Odometer_Reading__c/Asset_Odometer_Reading__c.object-meta.xml
<CustomObject>
    <label>Asset Odometer Reading</label>
    <nameField>
        <displayFormat>AOR-{000000}</displayFormat>
        <label>Asset Odometer Reading Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Odometer Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Odometer_Reading__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Odometer Readings</relationshipLabel>
    <relationshipName>Asset_Odometer_Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Odometer_Reading__c/fields/Blank_Odometer_Today_formula__c.field-meta.xml
<CustomField>
    <fullName>Blank_Odometer_Today_formula__c</fullName>
    <formula>IF(Odometer_Today__c &gt; 0, FALSE, TRUE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Blank Odometer Today</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset_Odometer_Reading__c/fields/Current_Odometer__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer__c</fullName>
    <label>Current Odometer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Odometer_Reading__c/fields/Odometer_Today__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Today__c</fullName>
    <label>Odometer Today</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Driver Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000000}</displayFormat>
        <label>Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Driver Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver_Assignment__c/fields/Driver_Status__c.field-meta.xml
<CustomField>
    <fullName>Driver_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Ready to Submit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Transport_Job__c.field-meta.xml
<CustomField>
    <fullName>Transport_Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transport Job</label>
    <referenceTo>Transport_Job__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/Transport_Job__c.object-meta.xml
<CustomObject>
    <label>Transport Job</label>
    <nameField>
        <displayFormat>TJ-{0000000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssetAssignmentControllerTest.cls
@IsTest(SeeAllData=true)
public without sharing class AssetAssignmentControllerTest {
    
    static testmethod void testMethodLookup() {
        
        Transport_Job__c transjob = [SELECT Id FROM Transport_Job__c limit 1];
            
        Test.startTest();
        AssetAssignmentController.getAssetAssignmentList('a0M3H0000002GOZUA2');
        AssetAssignmentController.AssetLookUp('a0M3H0000002GOZUA2');
        AssetAssignmentController.getOdometerReading('a0M3H0000002GOZUA2');
        AssetAssignmentController.getDailyPrestart('a0M3H0000002GOZUA2');
        AssetAssignmentController.getOwnerUnit(transjob.Id);
        AssetAssignmentController.UnitLookUp();
        AssetAssignmentController.AssetOdometerLookUp();
        Test.stopTest();  
        
    }
    
    static testmethod void queryAsCommunityUser(){
        List<Asset_Odometer_Reading__c> assetList = AssetAssignmentController.getOdometerReading(UserInfo.getUserId());
        system.debug(LoggingLevel.DEBUG, '## size ran by admin user: ' + assetList.size());
        List<Asset_Odometer_Reading__c> rawQueryList = [SELECT Id, Asset__c, Asset__r.Name, Current_Odometer__c, Odometer_Today__c, Blank_Odometer_Today_formula__c 
                FROM Asset_Odometer_Reading__c WHERE OwnerId = :UserInfo.getUserId()];
        system.debug(LoggingLevel.DEBUG, '## admin user info get user id: ' + UserInfo.getUserId() );
        system.debug(LoggingLevel.DEBUG, '## size ran by admin user raw query: ' + rawQueryList.size());
        /*User commUser = [select Id from User where IsActive = true and UserType = 'PowerCustomerSuccess' limit 1];
        system.runAs(commUser){
            assetList = AssetAssignmentController.getOdometerReading(commUser.Id);
            system.debug(LoggingLevel.DEBUG, '## size ran by comm user: ' + assetList.size());
            system.debug(LoggingLevel.DEBUG, '## comm user info get user id: ' + UserInfo.getUserId() );
            rawQueryList = [SELECT Id, WD_Asset__c, WD_Asset__r.Name, WD_Asset__r.Current_Odometer_Reading__c, Odometer_Reading__c 
                FROM Asset_Driver_Assignment__c WHERE Driver_Assignment__r.OwnerId = :UserInfo.getUserId()
                AND  Driver_Assignment__r.Driver_Status__c IN ('Assigned','In Progress')];
            
            system.debug(LoggingLevel.DEBUG, '## size ran by comm  user raw query: ' + rawQueryList.size());
        }*/
    }
}