force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID_Number__c</fullName>
    <label>Asset ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Current_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer_Reading__c</fullName>
    <label>Current Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <label>Engine Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Hrs__c</fullName>
    <label>Last Service Hrs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Km__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Km__c</fullName>
    <label>Last Service Km</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Parent_Asset__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent Asset that this asset is currently associated with</description>
    <label>Parent Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Child Assets</relationshipLabel>
    <relationshipName>WD_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Where is the asset located?</inlineHelpText>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>WD Assets</relationshipLabel>
    <relationshipName>WD_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/Cranes.recordType-meta.xml
<RecordType>
    <fullName>Cranes</fullName>
    <active>false</active>
    <label>Cranes</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Dollies.recordType-meta.xml
<RecordType>
    <fullName>Dollies</fullName>
    <active>true</active>
    <label>Dollies</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Forklifts.recordType-meta.xml
<RecordType>
    <fullName>Forklifts</fullName>
    <active>true</active>
    <label>Forklifts</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Loaders.recordType-meta.xml
<RecordType>
    <fullName>Loaders</fullName>
    <active>true</active>
    <label>Loaders</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Rigs.recordType-meta.xml
<RecordType>
    <fullName>Rigs</fullName>
    <active>true</active>
    <label>Rigs</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <label>Trailer</label>
</RecordType>

force-app/main/default/objects/Development_Records__c/Development_Records__c.object-meta.xml
<CustomObject>
    <label>Development Record</label>
    <nameField>
        <displayFormat>DR-{0000}</displayFormat>
        <label>DR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Development Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Development_Records__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <formula>TEXT(Employee__r.Position__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Position 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Professional_Development_Type__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professional Development Type</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Development Records</relationshipLabel>
    <relationshipName>Development_Record</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Required_By__c.field-meta.xml
<CustomField>
    <fullName>Required_By__c</fullName>
    <formula>Professional_Development_Type__r.Required_By__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Required By</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Development_Records__c/fields/Requirement_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Type__c</fullName>
    <formula>TEXT( Professional_Development_Type__r.Requirement_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Requirement Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employees__c/Employees__c.object-meta.xml
<CustomObject>
    <label>Employees</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employees__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <inlineHelpText>INACTIVE - DO NOT USE</inlineHelpText>
    <label>Position 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accountant</fullName>
            </value>
            <value>
                <fullName>Accounts &amp; Payroll Officer</fullName>
            </value>
            <value>
                <fullName>Administration Officer</fullName>
            </value>
            <value>
                <fullName>Assistant Driller</fullName>
            </value>
            <value>
                <fullName>Auto Electrician</fullName>
            </value>
            <value>
                <fullName>Camp Attendant</fullName>
            </value>
            <value>
                <fullName>Camp Cook</fullName>
            </value>
            <value>
                <fullName>Camp Manager</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Derrickman</fullName>
            </value>
            <value>
                <fullName>Diesel Fitter</fullName>
            </value>
            <value>
                <fullName>Driller</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>Fabrications Leading Hand</fullName>
            </value>
            <value>
                <fullName>Field Safety Officer</fullName>
            </value>
            <value>
                <fullName>Field Supervisor</fullName>
            </value>
            <value>
                <fullName>Finance Manager</fullName>
            </value>
            <value>
                <fullName>Floorhand</fullName>
            </value>
            <value>
                <fullName>Groundskeeper</fullName>
            </value>
            <value>
                <fullName>HR Manager</fullName>
            </value>
            <value>
                <fullName>Junior Administration Officer</fullName>
            </value>
            <value>
                <fullName>Labourer</fullName>
            </value>
            <value>
                <fullName>Lead Floorhand</fullName>
            </value>
            <value>
                <fullName>Lead Station Hand</fullName>
            </value>
            <value>
                <fullName>Leasehand</fullName>
            </value>
            <value>
                <fullName>Maintenance Manager</fullName>
            </value>
            <value>
                <fullName>Managing Director</fullName>
            </value>
            <value>
                <fullName>Mechanic</fullName>
            </value>
            <value>
                <fullName>Mechanical Supervisor</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/Mandatory_Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Mandatory Professional Development</label>
    <nameField>
        <label>Mandatory Professional Development Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mandatory Professional Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mandatory Professional Developments</relationshipLabel>
    <relationshipName>Mandatory_Professional_Developments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Mandatory Professional Developments</relationshipLabel>
    <relationshipName>Position</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mandatory_Professional_Development__c/fields/Professional_Development__c.field-meta.xml
<CustomField>
    <fullName>Professional_Development__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Professional Development</label>
    <referenceTo>Professional_Development__c</referenceTo>
    <relationshipLabel>Mandatory Professional Development (By Client/Position)</relationshipLabel>
    <relationshipName>Mandatory_Professional_Developments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/Professional_Development__c.object-meta.xml
<CustomObject>
    <label>Professional Development</label>
    <nameField>
        <label>Course/Qualification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Professional Development</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Professional_Development__c/fields/Days_until_renewal_is_required__c.field-meta.xml
<CustomField>
    <fullName>Days_until_renewal_is_required__c</fullName>
    <inlineHelpText>Number of days until it needs to be renewed. 
EG: 1 year = 365 Days</inlineHelpText>
    <label>Days until renewal is required</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/fields/Required_By__c.field-meta.xml
<CustomField>
    <fullName>Required_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Who requires that this be completed</inlineHelpText>
    <label>Required By</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Courses_Qualifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Professional_Development__c/fields/Requirement_Type__c.field-meta.xml
<CustomField>
    <fullName>Requirement_Type__c</fullName>
    <label>Requirement Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>As per Matrix</fullName>
            </value>
            <value>
                <fullName>Mandatory By Position</fullName>
            </value>
            <value>
                <fullName>WSQ - Core</fullName>
            </value>
            <value>
                <fullName>WSQ - Elective</fullName>
            </value>
            <value>
                <fullName>Manager to Request</fullName>
            </value>
            <value>
                <fullName>Mandatory Client Induction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Client</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Client</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site</relationshipLabel>
    <relationshipName>Well_Sites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <formula>/*Site__r.Account__r.Name*/
 Contract_New__r.Account__r.Name</formula>
    <label>Client</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InilitizeTestData.cls
//Utility class to Create sample records for various test classes.
public class InilitizeTestData{
    //Method to find record type id of "Asset" records by passing record type name.
    public static Id findRecordTypeId(string recordTypeName){
        Schema.DescribeSObjectResult assetSchema = Schema.SObjectType.Asset__c; 
        Map<String,Schema.RecordTypeInfo> AssetRecordTypeInfo = assetSchema.getRecordTypeInfosByName();
        return AssetRecordTypeInfo.get(recordTypeName).getRecordTypeId();
    }
    //Method to create asset record of record type "Light Vehicles","Cranes","Non-Vehicle Engine","Rigs".
    public static Asset__c createAsset(string assetName,string Id,string recordtypename,Integer odometerReading,Integer lastServiceKm ){
        Asset__c asset = new Asset__c();
        asset.Name=assetName;
        asset.Asset_ID_Number__c=Id;
        asset.RecordTypeId =findRecordTypeId(recordtypename);
        asset.Current_Odometer_Reading__c=odometerReading;
        asset.Last_Service_Km__c=lastServiceKm ;
        return asset;
    }
    //Method to create asset record of record type "Dollies","Forklifts","Loaders","Prime Mover","Trailer".
    public static Asset__c createAssetOfCranes(string assetName,string Id,string recordtypename,Integer engineHrs,Integer lastServicHrs ){
        Asset__c asset = new Asset__c();
        asset.Name=assetName;
        asset.Asset_ID_Number__c=Id;
        asset.RecordTypeId =findRecordTypeId(recordtypename);
        asset.Engine_Hours__c=engineHrs;
        asset.Last_Service_Hrs__c=lastServicHrs ;
        return asset;
    }
    public static Asset__c createAssetChildRecord(string assetName,string Id,string recordtypename,Id parentId){
        Asset__c asset = new Asset__c();
        asset.Name=assetName;
        asset.Asset_ID_Number__c=Id;
        asset.RecordTypeId =findRecordTypeId(recordtypename);
        asset.Parent_Asset__c = parentId;
        return asset;
    }
    public static Asset__c createParentAssetRecord(string assetName,string Id,string recordtypename,Id unitId){
        Asset__c asset = new Asset__c();
        asset.Name=assetName;
        asset.Asset_ID_Number__c=Id;
        asset.RecordTypeId =findRecordTypeId(recordtypename);
        asset.Unit__c=unitId;
        return asset;
    }
    public static Account createAccount(string name){
        Schema.DescribeSObjectResult assetSchema = Schema.SObjectType.Account; 
        Map<String,Schema.RecordTypeInfo> AccountRecordTypeInfo = assetSchema.getRecordTypeInfosByName();
        Account acc = new Account();
        acc.name=name;
        acc.RecordTypeId=AccountRecordTypeInfo.get('Client').getRecordTypeId();
        return acc;
    }
    public static Site__c createSite(string siteName,string relatedClient){
        Site__c testSite = new Site__c();
        testSite.Name= siteName;
        testSite.Account__c = relatedClient;
        return testSite;
    }
    public static Unit__c createUnit(string unitName,string relatedSite){
        Unit__c unit = new Unit__c ();
        unit.Name=unitName;
        unit.Site__c=relatedSite;
        return unit;
    }
    
    //Additional test data creator methods added for wild desert HR module impletations.
    
    public static Position__c createPosition(string posName){
        Position__c p= new Position__c();
        p.Name = posName;
        return p;
    }
    public static Professional_Development__c createPersonalDevType(string pdtName,Integer daysUntilRenewalReq){
        Professional_Development__c  pdt = new Professional_Development__c ();
        pdt.Name =pdtName;
        pdt.Days_until_renewal_is_required__c =daysUntilRenewalReq;
        return pdt; 
         
    }
    public static Professional_Development__c createProfDevRecord(string pdtName,string accountId){
    	 Professional_Development__c  pdt = new Professional_Development__c ();
         pdt.Name =pdtName;
         pdt.Required_By__c = accountId;
         pdt.Requirement_Type__c ='Compulsory - All';
         return pdt;
    }
    public static Development_Records__c createDevRecord(string pdtId,string posId,string accId){
        Development_Records__c  newDev = new Development_Records__c();
        newDev.Professional_Development_Type__c = pdtId;
        //newDev.Position__c = posId;
        //newDev.Client__c = accId;
        newDev.Status__c ='Incomplete';
        return newDev;
    }
     public static Development_Records__c createDevRecordForCloning(string pdtId,string posId,string accId){
        Development_Records__c  newDev = new Development_Records__c();
        newDev.Professional_Development_Type__c = pdtId;
        //newDev.Position__c = posId;
       // newDev.Client__c = accId;
        newDev.Expired__c = false;
        newDev.Status__c ='Complete';
        return newDev;
    }
    public static Employees__c createEmployee(string posId,string unitId,string empName){
        Employees__c  emp = new Employees__c();
        emp.Name = empName;
        emp.PositionLookup__c = posId;
        emp.Assigned_to_Unit__c = unitId;
        emp.First_Name__c ='Test First Name';
        emp.Last_Name__c = 'Test Last Name';
        return emp;    
    
    }
    public static Employees__c createEmployeeForNewTest(string posId,string empName){
    	Employees__c  emp = new Employees__c();
        emp.Name = empName;
        emp.PositionLookup__c =posId;
        emp.First_Name__c='Test First Name';
        emp.Last_Name__c= 'Test Last Name';
        return emp;
    }
    public static Mandatory_Professional_Development__c createMandDevRecord(String pdType,string mandName,String accId,String posId){
        Mandatory_Professional_Development__c  mandDev = new Mandatory_Professional_Development__c ();
        mandDev.Name = mandName;
        mandDev.Account__c =accId;
        mandDev.Position__c =posId;
        mandDev.Professional_Development__c =pdType;
        return mandDev;
    }


}