force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Current_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer_Reading__c</fullName>
    <label>Current Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <label>Engine Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Hrs__c</fullName>
    <label>Last Service Hrs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Km__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Km__c</fullName>
    <label>Last Service Km</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Draft (Order/PR)</fullName>
            </value>
            <value>
                <fullName>PaymenInsurance Complete</fullName>
                <label>Payment &amp; Insurance Complete</label>
            </value>
            <value>
                <fullName>Ready to Collect</fullName>
            </value>
            <value>
                <fullName>Build/On-board</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Off-board</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Where is the asset located?</inlineHelpText>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>WD Assets</relationshipLabel>
    <relationshipName>WD_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/Cranes.recordType-meta.xml
<RecordType>
    <fullName>Cranes</fullName>
    <active>false</active>
    <label>Cranes</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Dollies.recordType-meta.xml
<RecordType>
    <fullName>Dollies</fullName>
    <active>true</active>
    <label>Dollies</label>
</RecordType>

force-app/main/default/objects/Job_Cards__c/Job_Cards__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Cards__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <inlineHelpText>Engine Hours (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Engine Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <label>Open (Approved)</label>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Stacked</fullName>
            </value>
            <value>
                <fullName>Defer/Monitor</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset  #</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site__c/Site__c.object-meta.xml
<CustomObject>
    <label>Site</label>
    <nameField>
        <label>Lease Name/Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Site__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active Site</fullName>
                <default>true</default>
                <label>Active Site</label>
            </value>
            <value>
                <fullName>Inactive Site</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Site__c.field-meta.xml
<CustomField>
    <fullName>Site__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site</label>
    <referenceTo>Site__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Scheduled Start - has contract to start
Active - Currently working in field
Project Incomplete - Still in build phase
Inactive - Not currently contracted (Stacked Roma Base)</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled Start</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Project Incomplete</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/jobCardTriggerTest.cls
//Test Class to test the use cases of "Job Card" object trigger "updateAppropriateAsset".
@isTest
public class jobCardTriggerTest{
    static Asset__c assetRecordOfLightVehicles ;
    static Asset__c assetRecordOfCranes;
    static Asset__c assetRecordOfDollies;
    static Asset__c parentAsset;
    static Asset__c childAsset;
    static Job_Cards__c jobCardOfAssetLightVehicle;
    static Job_Cards__c jobCardOfAssetCranes;
    static Job_Cards__c jobCardOfAssetDollies;
    static Account testAccountforSite;
    static Site__c testSite;
    static Unit__c testUnit;
    static Unit__c testUnit1;
    //Method to create the "Asset" object record. 
    private static void init(){
       assetRecordOfLightVehicles = InilitizeTestData.createAsset('testAsset','1234','Light Vehicles',1000,0);
       assetRecordOfCranes = InilitizeTestData.createAssetOfCranes('testasset','2345','Cranes',25,0);
       assetRecordOfDollies = InilitizeTestData.createAsset('testAsset1','2234','Dollies',2000,0);
       
       database.insert(assetRecordOfLightVehicles);
       database.insert(assetRecordOfCranes );
       database.insert(assetRecordOfDollies);
       testAccountforSite =InilitizeTestData.createAccount('testAccount');
       database.insert(testAccountforSite);
       
       testSite=InilitizeTestData.createSite('testSite',testAccountforSite.id);
       database.insert(testSite);
       testUnit = InilitizeTestData.createUnit('testUnit',testSite.id);
       database.insert(testUnit);
       testUnit1=InilitizeTestData.createUnit('testUnit1',testSite.id);
       database.insert(testUnit1);
       parentAsset=InilitizeTestData.createParentAssetRecord('parentasset','1234','Light Vehicles',testUnit.id);
       database.insert(parentAsset);
       childAsset=InilitizeTestData.createAssetChildRecord('childasset','2345','Light Vehicles',parentAsset.id);
       database.insert(childAsset);
       assetRecordOfLightVehicles.Current_Odometer_Reading__c=10000;
       assetRecordOfCranes.Engine_Hours__c=250;
       assetRecordOfDollies.Current_Odometer_Reading__c=20000;
       update assetRecordOfLightVehicles;
       update assetRecordOfCranes;
       update assetRecordOfDollies; 
    }
    //method to test all use cases.
    public static TestMethod void myUnitTest(){
        init();
        test.startTest();
        jobCardOfAssetLightVehicle=[select id,Status__c from Job_Cards__c where WD_Asset__c=:assetRecordOfLightVehicles.id];
        jobCardOfAssetCranes=[select id,Status__c from Job_Cards__c where WD_Asset__c=:assetRecordOfCranes.id];
        jobCardOfAssetDollies=[select id,Status__c from Job_Cards__c where WD_Asset__c=:assetRecordOfDollies.id];
        
        jobCardOfAssetLightVehicle.Status__c='Completed';
        update jobCardOfAssetLightVehicle;
        jobCardOfAssetCranes.Status__c='Completed';
        update jobCardOfAssetCranes;
        jobCardOfAssetDollies.Status__c='Completed';
        update jobCardOfAssetDollies;
        system.assertEquals([select Last_Service_Km__c from Asset__c where id=:assetRecordOfLightVehicles.id][0].Last_Service_Km__c,10000);
        system.assertEquals([select Last_Service_Hrs__c from Asset__c where id=:assetRecordOfCranes.id][0].Last_Service_Hrs__c ,250);
        system.assertEquals([select Last_Service_Km__c from Asset__c where id=:assetRecordOfDollies.id][0].Last_Service_Km__c,20000);
        system.assertEquals([select Unit__c from Asset__c where id=:parentAsset.id][0].Unit__c ,[select Unit__c from Asset__c where id=:childAsset.id][0].Unit__c);
        
        parentAsset.Unit__c =testUnit1.id;
        update parentAsset;
        system.assertEquals([select Unit__c from Asset__c where id=:parentAsset.id][0].Unit__c ,[select Unit__c from Asset__c where id=:childAsset.id][0].Unit__c);
        test.stopTest();
    }


}