force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Current_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer_Reading__c</fullName>
    <label>Current Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Do_Not_Create_Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Create_Work_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Do Not Create Work Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <label>Engine Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Next_Job_Card_creation_reading__c.field-meta.xml
<CustomField>
    <fullName>Next_Job_Card_creation_reading__c</fullName>
    <label>Next Job Card creation reading</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/Cranes.recordType-meta.xml
<RecordType>
    <fullName>Cranes</fullName>
    <active>false</active>
    <label>Cranes</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Dollies.recordType-meta.xml
<RecordType>
    <fullName>Dollies</fullName>
    <active>true</active>
    <label>Dollies</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Forklifts.recordType-meta.xml
<RecordType>
    <fullName>Forklifts</fullName>
    <active>true</active>
    <label>Forklifts</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Loaders.recordType-meta.xml
<RecordType>
    <fullName>Loaders</fullName>
    <active>true</active>
    <label>Loaders</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Rigs.recordType-meta.xml
<RecordType>
    <fullName>Rigs</fullName>
    <active>true</active>
    <label>Rigs</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <label>Trailer</label>
</RecordType>

force-app/main/default/objects/Job_Cards__c/Job_Cards__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Cards__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <inlineHelpText>Date that Work Order was created</inlineHelpText>
    <label>Date Created</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <inlineHelpText>Engine Hours (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Engine Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Odometer__c.field-meta.xml
<CustomField>
    <fullName>Odometer__c</fullName>
    <inlineHelpText>Odometer (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Odometer</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Record_Count_Cranes__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_Cranes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Record Count Cranes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Record_Count_Dollies__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_Dollies__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Record Count Dollies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Type_of_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Maintenance__c</fullName>
    <inlineHelpText>The Work Order cannot be closed until ALL REQUIREMENTS OF THE SPECIFIED SERVICE HAVE BEEN COMPLETED</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Inspection</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly A</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly B</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly C</fullName>
            </value>
            <value>
                <fullName>Type 1 - 250Hrs</fullName>
            </value>
            <value>
                <fullName>Type 2 - 500Hrs</fullName>
            </value>
            <value>
                <fullName>Type 3 - 1000Hrs</fullName>
            </value>
            <value>
                <fullName>Type 4 - 2000Hrs</fullName>
            </value>
            <value>
                <fullName>KM Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset  #</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateJobCardUtility.cls
//Apex Utility Class written to handle the complexity of "CreateJobCard" trigger on "Asset" object.
public class CreateJobCardUtility {
    static String jobCreationStatus = 'No';

    //Method to create "Job Card" Record if the record tyoe of "Asset" is "Light Vehicle"
    public static String createJobCardForLightVechiles(Asset__c newRecordValue,Asset__c oldRecordValue,Id assetRecordID){
        List<Job_Cards__c> jobs = new  List<Job_Cards__c>();
        jobs=[select id from Job_Cards__c where WD_Asset__c =:assetRecordID ];
        jobCreationStatus = 'No';
        
        if(newRecordValue.Current_Odometer_Reading__c >= newRecordValue.Next_Job_Card_creation_reading__c && newRecordValue.Do_Not_Create_Work_Order__c == False) {
            Job_Cards__c newJob = new Job_Cards__c();
            newJob.RecordTypeId =createJobCardUtility.recordTypeIdOfName('Scheduled Service');
            newJob.Date_Created__c = system.today();
            newJob.Type_of_Maintenance__c = 'KM Service';
            newJob.WD_Asset__c=assetRecordID;
            newJob.Odometer__c=newRecordValue.Current_Odometer_Reading__c;
            newJob.OwnerId = newRecordValue.ownerId;
            database.insert(newJob);
            jobCreationStatus = 'Yes';
        }
        return jobCreationStatus;
    }
    //Method to create "Job Card" Record if the record tyoe of "Asset" is "Cranes","Non-Vehicle Assets" "Rigs","Forklifts","Loaders".
    public static string createJobCardForCrenes(Asset__c newRecordValue,Asset__c oldRecordValue,Id assetRecordID){
        Integer maxRecordCountValue;
        maxRecordCountValue = createJobCardUtility.latestJobCardRecordOfCranes(assetRecordID);
        jobCreationStatus = 'No';
        
        if( newRecordValue.Engine_Hours__c>= newRecordValue.Next_Job_Card_creation_reading__c && newRecordValue.Do_Not_Create_Work_Order__c == False){   
            
            Job_Cards__c newJob = new Job_Cards__c();
            newJob.RecordTypeId =createJobCardUtility.recordTypeIdOfName('Scheduled Service');
            newJob.Date_Created__c = system.today();
            newJob.WD_Asset__c=assetRecordID;
            newJob.Engine_Hours__c =newRecordValue.Engine_Hours__c;
            newJob.OwnerId = newRecordValue.ownerId;
            if(math.mod(maxRecordCountValue,8)==0){
                newJob.Record_Count_Cranes__c = 1;
                newJob.Type_of_Maintenance__c='Type 1 - 250Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==1){
                newJob.Record_Count_Cranes__c = 2;
                newJob.Type_of_Maintenance__c='Type 2 - 500Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==2){
                newJob.Record_Count_Cranes__c = 3;
                newJob.Type_of_Maintenance__c='Type 1 - 250Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==3){
                newJob.Record_Count_Cranes__c = 4;
                newJob.Type_of_Maintenance__c='Type 3 - 1000Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==4){
                newJob.Record_Count_Cranes__c = 5;
                newJob.Type_of_Maintenance__c='Type 1 - 250Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==5){
                newJob.Record_Count_Cranes__c = 6;
                newJob.Type_of_Maintenance__c='Type 2 - 500Hrs';
            }
            if(math.mod(maxRecordCountValue,8)==6){
                newJob.Record_Count_Cranes__c = 7;
                newJob.Type_of_Maintenance__c='Type 1 - 250Hrs';
            }
           if(math.mod(maxRecordCountValue,8)==7){
               newJob.Record_Count_Cranes__c = 8;
               newJob.Type_of_Maintenance__c='Type 4 - 2000Hrs';
            }
            database.insert(newJob);
            jobCreationStatus = 'Yes';
        }
        return jobCreationStatus; 
    }
    //Method to create "Job Card" Record if the record tyoe of "Asset" is "Dollies","Prime Movers","Trailer".
    public static string createJobCardForDollies(Asset__c newRecordValue,Asset__c oldRecordValue,Id assetRecordID){
        Integer maxRecordCountValue;
        maxRecordCountValue = createJobCardUtility.latestJobCardRecordOfDollies(assetRecordID);
        jobCreationStatus = 'No';
        
        if( newRecordValue.Current_Odometer_Reading__c>= newRecordValue.Next_Job_Card_creation_reading__c && newRecordValue.Do_Not_Create_Work_Order__c == False){     
            Job_Cards__c newJob = new Job_Cards__c();
            newJob.RecordTypeId =createJobCardUtility.recordTypeIdOfName('Scheduled Service');
            newJob.Date_Created__c = system.today();
            newJob.WD_Asset__c=assetRecordID;
            newJob.Odometer__c=newRecordValue.Current_Odometer_Reading__c;
            newJob.OwnerId = newRecordValue.ownerId;
            if(math.mod(maxRecordCountValue,4)==0){
                newJob.Record_Count_Dollies__c = 1;
                newJob.Type_of_Maintenance__c='Truck/Trailer/Dolly A';
            }
            if(math.mod(maxRecordCountValue,4)==1){
                newJob.Record_Count_Dollies__c = 2;
                newJob.Type_of_Maintenance__c='Truck/Trailer/Dolly B';
            }
            if(math.mod(maxRecordCountValue,4)==2){
                newJob.Record_Count_Dollies__c = 3;
                newJob.Type_of_Maintenance__c='Truck/Trailer/Dolly A';
            }
            if(math.mod(maxRecordCountValue,4)==3){
                newJob.Record_Count_Dollies__c = 4;
                newJob.Type_of_Maintenance__c='Truck/Trailer/Dolly C';
            }
           
            database.insert(newJob);
            jobCreationStatus = 'Yes';       
        }
        return jobCreationStatus;   
    }
    //Method returns record type id by passing record type name of "Asset" object.
    public static string recordTypeIdOfName(String recordTypeName){
        Schema.DescribeSObjectResult jobCardSchema = Schema.SObjectType.Job_Cards__c; 
        Map<String,Schema.RecordTypeInfo> jobCardRecordTypeInfo = jobCardSchema.getRecordTypeInfosByName();
        return jobCardRecordTypeInfo.get(recordTypeName).getRecordTypeId();
    }
    //Method returns the order of "Job Card" record under particular "Asset" record of record type "Cranes","Non-Vehicle Assets" "Rigs" .
    public static Integer latestJobCardRecordOfCranes(string assetId){
        Integer recordCountValue;
        List<Job_Cards__c> listLatestRecords = new List<Job_Cards__c>();
        listLatestRecords = [select Record_Count_Cranes__c from Job_Cards__c where WD_Asset__c=:assetId order by CreatedDate desc  ] ;
        if(!listLatestRecords.isEmpty()){
            recordCountValue =Integer.valueOf(listLatestRecords[0].Record_Count_Cranes__c);
            return recordCountValue;    
        }
        else{
            return 0;
        }
    }
    //Method returns the order of "Job Card" record under particular "Asset" record of record type "Dollies","Prime Movers","Trailer" .
    public static Integer latestJobCardRecordOfDollies(string assetId){
        Integer recordCountValue;
        List<Job_Cards__c> listLatestRecords = new List<Job_Cards__c>();
        listLatestRecords = [select Record_Count_Dollies__c from Job_Cards__c where WD_Asset__c=:assetId order by CreatedDate desc  ] ;
        if(!listLatestRecords.isEmpty()){
            recordCountValue =Integer.valueOf(listLatestRecords[0].Record_Count_Dollies__c);
            return recordCountValue;    
        }
        else{
            return 0;
        }
    }
   

}