force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Asset_Family__c.field-meta.xml
<CustomField>
    <fullName>Asset_Family__c</fullName>
    <label>Asset Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Air Booster</fullName>
            </value>
            <value>
                <fullName>Air Compressor</fullName>
            </value>
            <value>
                <fullName>BHA Equipment</fullName>
            </value>
            <value>
                <fullName>Blooie Line</fullName>
            </value>
            <value>
                <fullName>Blooie Tank</fullName>
            </value>
            <value>
                <fullName>BOP Equipment</fullName>
            </value>
            <value>
                <fullName>Box Trailers</fullName>
            </value>
            <value>
                <fullName>Bucket</fullName>
            </value>
            <value>
                <fullName>Building/Infrastructure</fullName>
            </value>
            <value>
                <fullName>Catwalk Skid</fullName>
            </value>
            <value>
                <fullName>Catwalk Trailer</fullName>
            </value>
            <value>
                <fullName>Cement Blocks</fullName>
            </value>
            <value>
                <fullName>Choke Manifold</fullName>
            </value>
            <value>
                <fullName>Circulating Skid</fullName>
            </value>
            <value>
                <fullName>Combo Shack</fullName>
            </value>
            <value>
                <fullName>Communication Skid</fullName>
            </value>
            <value>
                <fullName>Container</fullName>
            </value>
            <value>
                <fullName>Cranes</fullName>
            </value>
            <value>
                <fullName>Desilting Unit</fullName>
            </value>
            <value>
                <fullName>Dollies</fullName>
            </value>
            <value>
                <fullName>Drilling Rig</fullName>
            </value>
            <value>
                <fullName>Drill Pipe</fullName>
            </value>
            <value>
                <fullName>Dropdeck</fullName>
            </value>
            <value>
                <fullName>Evaporative Fans</fullName>
            </value>
            <value>
                <fullName>Farming Equipment</fullName>
            </value>
            <value>
                <fullName>Filter Unit</fullName>
            </value>
            <value>
                <fullName>Flare Tank</fullName>
            </value>
            <value>
                <fullName>Flat Top</fullName>
            </value>
            <value>
                <fullName>Flexi-Drive (Transfer Pump)</fullName>
            </value>
            <value>
                <fullName>Flushby RIg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Asset_ID_Number__c.field-meta.xml
<CustomField>
    <fullName>Asset_ID_Number__c</fullName>
    <label>Asset ID Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Inventory_Item__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Item__c</fullName>
    <label>Asset Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EquipListContract</fullName>
                <default>true</default>
                <label>Equip List (Contract)</label>
            </value>
            <value>
                <fullName>Additional_(QA)</fullName>
                <label>Additional (QA)</label>
            </value>
            <value>
                <fullName>Stacked</fullName>
            </value>
            <value>
                <fullName>Obsolete</fullName>
            </value>
            <value>
                <fullName>Rural</fullName>
            </value>
            <value>
                <fullName>3rd Party Equip (Billable)</fullName>
            </value>
            <value>
                <fullName>3rd Party Equip (Non-Billable)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Name_and_Rego_Number__c.field-meta.xml
<CustomField>
    <fullName>Name_and_Rego_Number__c</fullName>
    <formula>IF(ISBLANK(Registration_Number__c), Name , Name + &apos; (&apos; +  Registration_Number__c  + &apos;)&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name and Rego Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/NHVAS_Accredited__c.field-meta.xml
<CustomField>
    <fullName>NHVAS_Accredited__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Box must be ticked if the asset is registered with NHVAS</inlineHelpText>
    <label>NHVAS Accredited</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <label>Serial Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Where is the asset located?</inlineHelpText>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>WD Assets</relationshipLabel>
    <relationshipName>WD_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Driver_Assignment__c/Asset_Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Asset Driver Assignment</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Asset Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Driver Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Driver_Assignment__c/fields/Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment__c</fullName>
    <label>Driver Assignment</label>
    <referenceTo>Driver_Assignment__c</referenceTo>
    <relationshipLabel>Asset Driver Assignments</relationshipLabel>
    <relationshipName>Asset_Driver_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Driver_Assignment__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <label>WD Asset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset__c.Inventory_Item__c</field>
            <operation>notEqual</operation>
            <value>Obselete</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Driver Assignments</relationshipLabel>
    <relationshipName>Asset_Driver_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Asset_Odometer_Reading__c/Asset_Odometer_Reading__c.object-meta.xml
<CustomObject>
    <label>Asset Odometer Reading</label>
    <nameField>
        <displayFormat>AOR-{000000}</displayFormat>
        <label>Asset Odometer Reading Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Asset Odometer Readings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Odometer_Reading__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Asset Odometer Readings</relationshipLabel>
    <relationshipName>Asset_Odometer_Readings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Pre_Start__c/Daily_Pre_Start__c.object-meta.xml
<CustomObject>
    <label>Daily Pre-Start</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Daily Pre-Start #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Pre-Starts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Pre_Start__c/fields/Asset_Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Asset_Driver_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset Driver Assignment</label>
    <referenceTo>Asset_Driver_Assignment__c</referenceTo>
    <relationshipLabel>Daily Pre-Starts</relationshipLabel>
    <relationshipName>Daily_Pre_Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Pre_Start__c/fields/Driver_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Driver_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver Assignment</label>
    <referenceTo>Driver_Assignment__c</referenceTo>
    <relationshipLabel>Daily Pre-Starts</relationshipLabel>
    <relationshipName>Daily_Pre_Starts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/Driver_Assignment__c.object-meta.xml
<CustomObject>
    <label>Driver Assignment</label>
    <nameField>
        <displayFormat>DA-{0000000000}</displayFormat>
        <label>Driver Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Driver Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver_Assignment__c/fields/Transport_Job__c.field-meta.xml
<CustomField>
    <fullName>Transport_Job__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transport Job</label>
    <referenceTo>Transport_Job__c</referenceTo>
    <relationshipLabel>Driver Assignments</relationshipLabel>
    <relationshipName>Driver_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Driver_Assignment__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <formula>Transport_Job__r.Unit__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/Transport_Job__c.object-meta.xml
<CustomObject>
    <label>Transport Job</label>
    <nameField>
        <displayFormat>TJ-{0000000000}</displayFormat>
        <label>Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Job__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Transport Jobs</relationshipLabel>
    <relationshipName>Transport_Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Job__c/fields/Unit_Manager__c.field-meta.xml
<CustomField>
    <fullName>Unit_Manager__c</fullName>
    <formula>Unit__r.Manager__r.FirstName&amp;&quot; &quot;&amp;Unit__r.Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <description>Unit EG: Rig 12 Unit or  Camp 3 Unit
Think of its locations</description>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Manager__c.field-meta.xml
<CustomField>
    <fullName>Unit_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Unit Manager also controls Transport Jobs Mgmt.</inlineHelpText>
    <label>Unit Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <inlineHelpText>Field Camp/Rig - purpose built for contract
Base - Permanent building/Camp 
Department - section of business that may require identifying for expense purposes</inlineHelpText>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Qld Depot</fullName>
                <label>Qld - Depot</label>
            </value>
            <value>
                <fullName>Camp - Qld</fullName>
                <label>Qld - Camp</label>
            </value>
            <value>
                <fullName>Rig - Qld</fullName>
                <label>Qld - Rig</label>
            </value>
            <value>
                <fullName>Depot - Roma</fullName>
                <label>SA - Depot</label>
            </value>
            <value>
                <fullName>Camp - SA</fullName>
                <label>SA - Camp</label>
            </value>
            <value>
                <fullName>Rig - SA</fullName>
                <label>SA - Rig</label>
            </value>
            <value>
                <fullName>Department</fullName>
            </value>
            <value>
                <fullName>Field - Rig</fullName>
            </value>
            <value>
                <fullName>Field - Camp</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Property</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetAssignmentController.cls
public class AssetAssignmentController {
    @AuraEnabled(cacheable=true)
    public static List<Asset_Driver_Assignment__c> getAssetAssignmentList(Id driverAssign) {
        return [SELECT Id, Driver_Assignment__c, WD_Asset__r.Name, WD_Asset__r.Asset_Family__c, WD_Asset__r.Registration_Number__c, WD_Asset__r.Serial_Number__c, 
                WD_Asset__r.Asset_ID_Number__c, WD_Asset__r.Unit__c, WD_Asset__r.Inventory_Item__c, WD_Asset__r.RecordTypeId
                FROM Asset_Driver_Assignment__c
                WHERE Driver_Assignment__c = :driverAssign  
                WITH SECURITY_ENFORCED
        ];
    }


    @AuraEnabled(cacheable=true)
    public static List <Asset__c> AssetLookUp(Id unitID) {
     /*String sQuery =  'SELECT Id, Name FROM Asset__c ORDER BY Name LIMIT 0';
     Transport_Job__c[] ownerID =  [SELECT OwnerId FROM Transport_Job__c WHERE iD = :transportJobID];
 
     //If Owner ID record found
     if (!ownerID.Isempty()) {
        Id strOwnerID = ownerID[0].OwnerId;
         Unit__c[] unitID = [SELECT Id FROM Unit__c WHERE Unit_Type__c = 'Transport' AND Unit_Manager__r.Id = :strOwnerID];
 
         //If Unit Id record found
        if(!unitID.Isempty()){
            Id strUnitID = unitID[0].Id;

             sQuery =  'SELECT Id, Name_and_Rego_Number__c FROM Asset__c WHERE Unit__c = \'' + strUnitID + '\' ORDER BY Name';
        }
     } */

        //If Unit Id record found
        string sQuery;
        //if(unitID <> 'null') {
            sQuery =  'SELECT Id, Name_and_Rego_Number__c FROM Asset__c WHERE Unit__c = \'' + unitID + '\' ORDER BY Name';
        //} else {
        //    sQuery =  'SELECT Id, Name FROM Asset__c ORDER BY Name LIMIT 0';
        //}
        
       
     List < Asset__c > returnList = new List < Asset__c > ();  
     List < Asset__c > lstOfRecords = Database.query(sQuery);
     for (Asset__c obj: lstOfRecords) {
                returnList.add(obj);
            }       
        
     return returnList; 
   }

    @AuraEnabled(cacheable=true)
    public static List <Asset__c> AssetOdometerLookUp() {
     
        //09 OCT 2023: C+S - This lookup will be used for LWC driverAssetOdometerReading
        string sQuery;
        sQuery =  'SELECT Id, Name_and_Rego_Number__c FROM Asset__c WHERE NHVAS_Accredited__c = TRUE ORDER BY Name';
       
       
     List < Asset__c > returnList = new List < Asset__c > ();  
     List < Asset__c > lstOfRecords = Database.query(sQuery);
     for (Asset__c obj: lstOfRecords) {
                returnList.add(obj);
            }       
        
     return returnList; 
   }

   @AuraEnabled(cacheable=true)
   public static List<Unit__c> getOwnerUnit(Id transportJobID) {
       String sQuery;
       Transport_Job__c[] ownerID =  [SELECT OwnerId FROM Transport_Job__c WHERE iD = :transportJobID];
    
        //If owner ID record found
        if (!ownerID.Isempty()) {
            Id strOwnerID = ownerID[0].OwnerId;
            sQuery = 'SELECT Id, Name FROM Unit__c WHERE Unit_Type__c = \'Transport\' AND Unit_Manager__r.Id =\'' + strOwnerID + '\'';
        } 
        
        List < Unit__c > returnList = new List < Unit__c > ();  
        List < Unit__c > lstOfRecords = Database.query(sQuery);
        for (Unit__c obj: lstOfRecords) {
                returnList.add(obj);
            }       
        
        return returnList; 
   }

   @AuraEnabled(cacheable=true)
   public static List <Unit__c> UnitLookUp() {
    String sQuery =  'SELECT Id, Name, UnitType__c from Unit__c WHERE Status__c = \'Active\' AND UnitType__c IN (\'Rig\', \'Camp\', \'Transport\') ORDER BY Name';
      
    List < Unit__c > returnList = new List < Unit__c > ();  
    List < Unit__c > lstOfRecords = Database.query(sQuery);
    for (Unit__c obj: lstOfRecords) {
               returnList.add(obj);
           }       
       
    return returnList; 
  }


   @AuraEnabled(cacheable=true)
   public static List<Asset_Odometer_Reading__c> getOdometerReading(Id ownerId) {

        // 09 OCT 2023: C+S - Changed the query to the new Asset Odometer Reading
       /*return [SELECT Id, WD_Asset__c, WD_Asset__r.Name, WD_Asset__r.Current_Odometer_Reading__c, Odometer_Reading__c 
                FROM Asset_Driver_Assignment__c WHERE Driver_Assignment__r.OwnerId = :ownerId 
                AND  Driver_Assignment__r.Driver_Status__c IN ('Assigned','In Progress') AND Transport_Job_Date__c = TODAY
                WITH SECURITY_ENFORCED
       ];*/
       return [SELECT Id, Asset__c, Asset__r.Name, Current_Odometer__c, Odometer_Today__c, Blank_Odometer_Today_formula__c 
       FROM Asset_Odometer_Reading__c WHERE OwnerId = :ownerId 
       AND CreatedDate = TODAY 
       WITH SECURITY_ENFORCED ORDER BY CreatedDate];
   }

   @AuraEnabled(cacheable=true)
   public static List<Daily_Pre_Start__c> getDailyPrestart(Id assetdriverid) {
       return [SELECT Id FROM Daily_Pre_Start__c WHERE Asset_Driver_Assignment__c = :assetdriverid 
                WITH SECURITY_ENFORCED
       ];
   }
}