force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Date_Of_Last_Service__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Last_Service__c</fullName>
    <label>Date of Last Service</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <label>Engine Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Hrs__c</fullName>
    <label>Last Service Hrs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Km__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Km__c</fullName>
    <label>Last Service Km</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Last_Service_Type__c.field-meta.xml
<CustomField>
    <fullName>Last_Service_Type__c</fullName>
    <label>Last Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A Service</fullName>
            </value>
            <value>
                <fullName>B Service</fullName>
            </value>
            <value>
                <fullName>C Service</fullName>
            </value>
            <value>
                <fullName>Type 1 - 250Hrs</fullName>
            </value>
            <value>
                <fullName>Type 2 - 500Hrs</fullName>
            </value>
            <value>
                <fullName>Type 3 - 1000Hrs</fullName>
            </value>
            <value>
                <fullName>Type 4 - 2000Hrs</fullName>
            </value>
            <value>
                <fullName>10&apos;000km Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/Cranes.recordType-meta.xml
<RecordType>
    <fullName>Cranes</fullName>
    <active>false</active>
    <label>Cranes</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Dollies.recordType-meta.xml
<RecordType>
    <fullName>Dollies</fullName>
    <active>true</active>
    <label>Dollies</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Forklifts.recordType-meta.xml
<RecordType>
    <fullName>Forklifts</fullName>
    <active>true</active>
    <label>Forklifts</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Loaders.recordType-meta.xml
<RecordType>
    <fullName>Loaders</fullName>
    <active>true</active>
    <label>Loaders</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Rigs.recordType-meta.xml
<RecordType>
    <fullName>Rigs</fullName>
    <active>true</active>
    <label>Rigs</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <label>Trailer</label>
</RecordType>

force-app/main/default/objects/Job_Cards__c/Job_Cards__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Cards__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <inlineHelpText>Engine Hours (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Engine Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Odometer__c.field-meta.xml
<CustomField>
    <fullName>Odometer__c</fullName>
    <inlineHelpText>Odometer (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Odometer</label>
    <precision>14</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Type_of_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Maintenance__c</fullName>
    <inlineHelpText>The Work Order cannot be closed until ALL REQUIREMENTS OF THE SPECIFIED SERVICE HAVE BEEN COMPLETED</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Inspection</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly A</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly B</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly C</fullName>
            </value>
            <value>
                <fullName>Type 1 - 250Hrs</fullName>
            </value>
            <value>
                <fullName>Type 2 - 500Hrs</fullName>
            </value>
            <value>
                <fullName>Type 3 - 1000Hrs</fullName>
            </value>
            <value>
                <fullName>Type 4 - 2000Hrs</fullName>
            </value>
            <value>
                <fullName>KM Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset  #</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/JobCardUtility.cls
//Utility class to handle the complexity of "updateAppropriateAsset" trigger on "Job Card" object.
public class JobCardUtility{
    //Method to update related "Asset" record when "Job Card" record's status is set "Completed"
    public static void updateAppropriateAsset(Job_Cards__c newValues,Job_Cards__c oldValues,string jobCardId){
        string relatedAssetId;
        string relatedAssetRecordTypeName;
        relatedAssetId = JobCardUtility.findRelatedAssetId(jobCardId);
       
        if(relatedAssetId!= null){
            relatedAssetRecordTypeName=JobCardUtility.findRelatedAssetRecordTypeName(relatedAssetId);
            List<Asset__c> relatedAssetData = new List<Asset__c>();
          
            //Update Values in related "Asset" record if related "Asset" record type is "Light Vehicles".
            if(relatedAssetRecordTypeName=='Light Vehicles'){
                relatedAssetData=[select Last_Service_Km__c,Date_Of_Last_Service__c,Last_Service_Type__c from Asset__c where Id=:relatedAssetId ];
                relatedAssetData[0].Last_Service_Km__c = newValues.Odometer__c;
                relatedAssetData[0].Date_Of_Last_Service__c = System.Today();
                relatedAssetData[0].Last_Service_Type__c = newValues.Type_of_Maintenance__c;
                database.update(relatedAssetData);
            }
            //Update Values in related "Asset" record if related "Asset" record type is "Cranes","Non-Vehicle Engine","Rigs","Forklifts","Loaders".
            if(relatedAssetRecordTypeName=='Cranes'||relatedAssetRecordTypeName=='Forklifts'||relatedAssetRecordTypeName=='Loaders'||relatedAssetRecordTypeName=='Non-Vehicle Engine'||relatedAssetRecordTypeName=='Rigs'){
                relatedAssetData=[select Last_Service_Hrs__c,Date_Of_Last_Service__c,Last_Service_Type__c from Asset__c where Id=:relatedAssetId ];    
                relatedAssetData[0].Last_Service_Hrs__c = newValues.Engine_Hours__c; 
                relatedAssetData[0].Date_Of_Last_Service__c = System.Today();
                relatedAssetData[0].Last_Service_Type__c = newValues.Type_of_Maintenance__c;
                database.update(relatedAssetData);
            }
            //Update Values in related "Asset" record if related "Asset" record type is "Dollies","Prime Mover","Trailer".
            if(relatedAssetRecordTypeName=='Dollies'||relatedAssetRecordTypeName=='Prime Mover'||relatedAssetRecordTypeName=='Trailer'){
                relatedAssetData=[select Last_Service_Km__c,Date_Of_Last_Service__c,Last_Service_Type__c from Asset__c where Id=:relatedAssetId ];
                relatedAssetData[0].Last_Service_Km__c =newValues.Odometer__c;
                relatedAssetData[0].Date_Of_Last_Service__c = System.Today();
                relatedAssetData[0].Last_Service_Type__c = newValues.Type_of_Maintenance__c;
                database.update(relatedAssetData);
          
            }
       
       }
    
    }
    //Method to find "Asset" rcord id related with "Job Card" Record.
    public static string findRelatedAssetId(string jobCardId){
        List<Job_Cards__c> relatedJobCardAssetId = new List<Job_Cards__c>();
        relatedJobCardAssetId =[select WD_Asset__c from Job_Cards__c where Id=:jobCardId];
        return relatedJobCardAssetId [0].WD_Asset__c;
    }
    //Method to find "Asset" record's Record type name.
    public static string findRelatedAssetRecordTypeName(string relatedAssetId){
        List<Asset__c> relatedAssetInfo = new List<Asset__c>();
        relatedAssetInfo =[select RecordType.name from Asset__c where Id=:relatedAssetId];
        return relatedAssetInfo[0].RecordType.name;
    } 


}