force-app/main/default/objects/Asset__c/Asset__c.object-meta.xml
<CustomObject>
    <label>WD Asset</label>
    <nameField>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Assets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset__c/fields/Current_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Current_Odometer_Reading__c</fullName>
    <label>Current Odometer Reading</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <label>Engine Hours</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset__c/recordTypes/Cranes.recordType-meta.xml
<RecordType>
    <fullName>Cranes</fullName>
    <active>false</active>
    <label>Cranes</label>
</RecordType>

force-app/main/default/objects/Asset__c/recordTypes/Dollies.recordType-meta.xml
<RecordType>
    <fullName>Dollies</fullName>
    <active>true</active>
    <label>Dollies</label>
</RecordType>

force-app/main/default/objects/Job_Cards__c/Job_Cards__c.object-meta.xml
<CustomObject>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{0000}</displayFormat>
        <label>Work Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Cards__c/fields/Engine_Hours__c.field-meta.xml
<CustomField>
    <fullName>Engine_Hours__c</fullName>
    <inlineHelpText>Engine Hours (on the Asset) at the time the Service is auto created</inlineHelpText>
    <label>Engine Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Record_Count_Cranes__c.field-meta.xml
<CustomField>
    <fullName>Record_Count_Cranes__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Record Count Cranes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/Type_of_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Maintenance__c</fullName>
    <inlineHelpText>The Work Order cannot be closed until ALL REQUIREMENTS OF THE SPECIFIED SERVICE HAVE BEEN COMPLETED</inlineHelpText>
    <label>Service Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual Inspection</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly A</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly B</fullName>
            </value>
            <value>
                <fullName>Truck/Trailer/Dolly C</fullName>
            </value>
            <value>
                <fullName>Type 1 - 250Hrs</fullName>
            </value>
            <value>
                <fullName>Type 2 - 500Hrs</fullName>
            </value>
            <value>
                <fullName>Type 3 - 1000Hrs</fullName>
            </value>
            <value>
                <fullName>Type 4 - 2000Hrs</fullName>
            </value>
            <value>
                <fullName>KM Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Cards__c/fields/WD_Asset__c.field-meta.xml
<CustomField>
    <fullName>WD_Asset__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Asset  #</label>
    <referenceTo>Asset__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Job_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssetTriggerTest.cls
//Test class to test the use cases of "Asset" object trigger "CreateJobCard". 
@isTest
public class AssetTriggerTest{
    static Asset__c assetRecordOfLightVehicles ;
    static Asset__c assetRecordOfCranes;
    static Asset__c assetRecordOfDollies;
    //Method to create the "Asset" object record 
    private static void init(){
       assetRecordOfLightVehicles = InilitizeTestData.createAsset('testAsset','1234','Light Vehicles',1000,0);
       assetRecordOfCranes = InilitizeTestData.createAssetOfCranes('testasset','2345','Cranes',100,0);
       assetRecordOfDollies = InilitizeTestData.createAsset('testAsset1','2234','Dollies',2000,0);
       database.insert(assetRecordOfLightVehicles);
       database.insert(assetRecordOfCranes );
       database.insert(assetRecordOfDollies);
    }
    //method to test all use cases.
    private static Testmethod void myUnitTest(){
        init();
        Test.startTest();
            assetRecordOfLightVehicles.Current_Odometer_Reading__c=9000;
            update assetRecordOfLightVehicles;
        
            assetRecordOfCranes.Engine_Hours__c=250;
            update assetRecordOfCranes;
            system.assertEquals([select Type_of_Maintenance__c,Record_Count_Cranes__c  from Job_Cards__c where WD_Asset__c=:assetRecordOfCranes.id order by CreatedDate desc ][0].Record_Count_Cranes__c,1);
            
            assetRecordOfDollies.Current_Odometer_Reading__c=20000;
            update assetRecordOfDollies;
       
            assetRecordOfCranes.Engine_Hours__c=500;
            update assetRecordOfCranes;
            //system.assertEquals([select Type_of_Maintenance__c,Record_Count_Cranes__c  from Job_Cards__c where WD_Asset__c=:assetRecordOfCranes.id order by CreatedDate desc ][0].Record_Count_Cranes__c,1);
           
            assetRecordOfDollies.Current_Odometer_Reading__c=50000;
            update assetRecordOfDollies;
            
            assetRecordOfCranes.Engine_Hours__c=750;
            update assetRecordOfCranes;
            
            
            system.assertNotEquals(createJobCardUtility.latestJobCardRecordOfCranes('testid'),null);
            system.assertNotEquals(createJobCardUtility.latestJobCardRecordOfDollies('testid'),null);
          
    
        Test.stopTest();
    }

}