force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>WD Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WD Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/ServicesReceived__c.object-meta.xml
<CustomObject>
    <label>Services Received</label>
    <nameField>
        <displayFormat>SR-{00000}</displayFormat>
        <label>Services Received</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services Received</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ServicesReceived__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Operating</fullName>
            </value>
            <value>
                <fullName>Rig Move</fullName>
            </value>
            <value>
                <fullName>SBWC</fullName>
            </value>
            <value>
                <fullName>SBWOC</fullName>
            </value>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>Inspection/PMS</fullName>
            </value>
            <value>
                <fullName>Crew Travel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Item_total__c.field-meta.xml
<CustomField>
    <fullName>Item_total__c</fullName>
    <inlineHelpText>Total Hours, Number of Days, Lump Sum  (Number in unit will multiply by rate to get total cost of item.</inlineHelpText>
    <label>Item Total</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ServicesReceived__c/fields/Operating_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hrs__c</fullName>
    <label>Operating Hrs</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/WD_Report__c.object-meta.xml
<CustomObject>
    <label>Job Order</label>
    <nameField>
        <displayFormat>JO-{00000}</displayFormat>
        <label>JO #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WD_Report__c/fields/Inspection_PMS_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Inspection_PMS_Hrs__c</fullName>
    <label>Inspection/PMS Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Operating_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Operating_Hrs__c</fullName>
    <label>Operating Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Repair_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Repair_Hrs__c</fullName>
    <label>Repair Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Rig_Move_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Rig_Move_Hrs__c</fullName>
    <label>Rig Move Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Standby_WC_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Standby_WC_Hrs__c</fullName>
    <label>Standby WC Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Standby_WOC_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Standby_WOC_Hrs__c</fullName>
    <label>Standby WOC Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WD_Report__c/fields/Travel_Hrs__c.field-meta.xml
<CustomField>
    <fullName>Travel_Hrs__c</fullName>
    <label>Travel Hrs</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/skedComputeTotalHrs.cls
//Use by sked_WDR_TotalHrs_trigger
public with sharing class skedComputeTotalHrs {

public WD_Report__c ReturnWDR(List<ServicesReceived__c> listSR, WD_Report__c WDR){

        decimal OperatingHrs = 0;
        decimal RigHrs = 0;
        decimal SBWCHrs = 0;
        decimal SBWOCHrs = 0;
        decimal RepairHrs = 0;
        decimal PMSHrs = 0;
        decimal CrewTravelHrs = 0;
            
            System.debug('***'+listSR);
            for (ServicesReceived__c sr : listSR){
                
                 //Check if record type is not 'Hire/Daily'
                 if(sr.RecordTypeId != '01290000000iGtR'){
                      if (sr.Category__c == 'Operating'){                         
                                    OperatingHrs += sr.Item_total__c;
                      }

                        if (sr.Category__c == 'Rig Move'){
                                    RigHrs += sr.Item_total__c;
                      }

                      if (sr.Category__c == 'SBWC'){
                                   SBWCHrs  += sr.Item_total__c;
                      }
                    
                         if (sr.Category__c == 'SBWOC'){
                                    SBWOCHrs  += sr.Item_total__c;
                      }

                        if (sr.Category__c == 'Repair'){
                                    RepairHrs  += sr.Item_total__c;
                      }

                           if (sr.Category__c == 'Inspection/PMS'){
                                    PMSHrs  += sr.Item_total__c;
                      }

                       if (sr.Category__c == 'Crew Travel'){
                                    CrewTravelHrs  += sr.Item_total__c;
                      }
                 }
            }
            
            WDR.Operating_Hrs__c = OperatingHrs;
            WDR.Rig_Move_Hrs__c = RigHrs;
            WDR.Standby_WC_Hrs__c = SBWCHrs;
            WDR.Standby_WOC_Hrs__c = SBWOCHrs;
            WDR.Repair_Hrs__c = RepairHrs;
            WDR.Inspection_PMS_Hrs__c = PMSHrs;
            WDR.Travel_Hrs__c = CrewTravelHrs;
            
            
    return WDR;
}

}